### ISSUE TITLE
Dynamic DNS not working

### ISSUE THREAD

**Issue by retrofreak83** [zentyal/zentyal#1814]
I am running Zentyal 5.1 and Dynamic DNS updates do not work, as exemplified here:
`Dec 16 21:24:32 MyHostName samba[2707]: [2017/12/16 21:24:32.208146,  0] ../lib/util/util_runcmd.c:316(samba_runcmd_io_handler)
Dec 16 21:24:32 MyHostName samba[2707]:   /usr/sbin/samba_kcc: ldb_wrap open of secrets.ldb
Dec 16 21:24:38 MyHostName named[2107]: samba_dlz: starting transaction on zone MY-DOMAIN.local
Dec 16 21:24:38 MyHostName named[2107]: samba_dlz: spnego update failed
Dec 16 21:24:38 MyHostName named[2107]: client 127.0.0.1#33589/key MY-DOMAIN.local: updating zone 'MY-DOMAIN.local/NONE': update failed: rejected by secure update (REFUSED)
Dec 16 21:24:38 MyHostName named[2107]: samba_dlz: cancelling transaction on zone MY-
DOMAIN.local
Dec 16 21:24:38 MyHostName dhcpd[1884]: DHCPREQUEST for 192.168.20.117 from ff:ee:11:22:33:44 (Brads-iPhone-7) via eth0
Dec 16 21:24:38 MyHostName dhcpd[1884]: DHCPACK on 192.168.20.117 to ff:ee:11:22:33:44 (Brads-iPhone-7) via eth0
Dec 16 21:24:38 MyHostName dhcpd[1884]: Unable to add forward map from Brads-iPhone-7.MY-DOMAIN.local. to 192.168.20.117: REFUSED`

**Comment by mkbrown** [comment]
Ditto. Ubuntu 16.04, Zentyal 5.1.

**Comment by retrofreak83** [comment]
Thanks for you answer. The solution provided there consists of manually patching two Zentyal modules of which the authors state that these are "a bit of a hack and is likely to be overwritten by Zentyal at some point." and "a quick dirty patch". That is why I'm hesitating to apply this.

**Comment by jacalvo** [comment]
Yes, that's why I'm keeping the issue open, because that's something that definitely needs to be integrated in Zentyal so no "dirty patch" is needed (but at the moment this is not straightforward to integrate, because that patch would require to have zentyal-samba as mandatory dependency of zentyal-dhcp, to start with). Pull requests are welcome BTW :)

**Comment by pakair** [comment]
Is there an update on this?

**Comment by jfaubin** [comment]
> Yes, that's why I'm keeping the issue open, because that's something that definitely needs to be integrated in Zentyal so no "dirty patch" is needed (but at the moment this is not straightforward to integrate, because that patch would require to have zentyal-samba as mandatory dependency of zentyal-dhcp, to start with). Pull requests are welcome BTW :)

Do you have ab ETA for the patch?

**Comment by Neustradamus** [comment]
@brunolorente?

**Comment by brunolorente** [comment]
Thank you for reporting this. We have reproduced the issue and are working on a fix.

**Comment by Neustradamus** [comment]
@brunolorente: It is solved?
