### ISSUE TITLE
Problems with file sharing... where names got? 

### ISSUE THREAD

**Issue by mrPsycho** [zentyal/zentyal#1815]
Today i found very strange situation:

```
root@zentyal:# getfacl /home
getfacl: Removing leading '/' from absolute path names
# file: home
# owner: root
# group: root
user::rwx
group::rwx
other::---
root@zentyal:# getfacl /home/phq
getfacl: Removing leading '/' from absolute path names
# file: home/phq
# owner: 2503
# group: 2513
user::rwx
group::---
other::---
```

where is username? why it shows only UID?

**Comment by mrPsycho** [comment]
in the logs of `samba-ac-dc` foud, that it is looking user directories in  `/var/lib/samba/usershares`.

so, i did  `ln -s /home /var/lib/samba/usershares` and fixed my problem. 

but why?

**Comment by Neustradamus** [comment]
@mrPsycho It is solved?

**Comment by mrPsycho** [comment]
no.. how?

**Comment by Neustradamus** [comment]
@mrPsycho: Why have you closed this ticket if it is not solved?

**Comment by mrPsycho** [comment]
because nobody cares, and we are switched to nethserver.

**Comment by mrPsycho** [comment]
because workaround works.
