### ISSUE TITLE
Error creating new users or changing shares

### ISSUE THREAD

**Issue by hermanocorreia** [zentyal/zentyal#1818]
> Quote

    root command set -e mkdir -p '/home/samba/profiles/hermano' chown -R 2540:2513 '/home/samba/profiles/hermano' chmod 0700 '/home/samba/profiles/hermano' setfacl -b '/home/samba/profiles/hermano' setfacl -R -m u:root:rwx,g::---,g:2513:---,u:'hermano':rwx '/home/samba/profiles/hermano' setfacl -R -m d:u:root:rwx,d:g::---,d:g:2513:---,d:u:'hermano':rwx '/home/samba/profiles/hermano' failed. Error output: setfacl: OpÃ§Ã£o -m: Argumento invÃ¡lido caracter aproximado 32 Command output: . Exit value: 2 at /usr/share/perl5/EBox/Sudo.pm line 240

I made an upgrade from version 4.1 to version 5.1.1, and now I am having problems on the AD.

This is a standalone server, and I figured out till now that I cannot create users (comes out with this error), and I cannot change permissions or access to personal shares.

On the webadmin the service on Domain Controller appears stopped and doesn't have the button to restart. Also on the webadmin on the share options is missing the information on the group, and on change I get an error "missing {DAT}".
It seems to be some kind of an AD corruption made by the upgrade. Any way to recover?

Thanks in advance for your help.

[zentyal.log](https://github.com/zentyal/zentyal/files/2350588/zentyal.log)

**Comment by brunolorente** [comment]
Thank you for reporting this. Please note that
• This is not a bug, but configuration related error. Pleas check the official documentation at doc.zentyal.org regarding the feature and ask for help.

**Comment by Neustradamus** [comment]
@hermanocorreia: It is solved?

**Comment by Neustradamus** [comment]
@hermanocorreia: It is solved?
