### ISSUE TITLE
OpenVPN - Change default cipher

### ISSUE THREAD

**Issue by tjspann** [zentyal/zentyal#1821]
![screenshot 24](https://user-images.githubusercontent.com/8395104/45840054-934da880-bcdb-11e8-9e1f-34d672412ff0.png)

If possible I'd like to request the default cipher be changed from BF-CBC to at least AES-128-CBC.

**Comment by Neustradamus** [comment]
https://community.qualys.com/docs/DOC-6321-ssl-labs-grading-2018
