### ISSUE TITLE
Is there any roadmap? 

### ISSUE THREAD

**Issue by mrPsycho** [zentyal/zentyal#1823]
Hello,

nobody can see any visible progress on Development. 
I know, that on free version there is no warranties and guaranties... but... is there any roadmap? 

there are a lot of bugs in current version. 
and no support at all, so the only one way is to go to nethserver, as the closest solution with same features.  

and i want to know - is there any plans to upgrade zentyal?

**Comment by Neustradamus** [comment]
+1

**Comment by ivosm** [comment]
I use Zentyal for years and I like it but when I wanted, as other did, to help by reporting some bugs like totally broken networking after use of some bundle configuration but one day all the reported bugs were "solved" by switching off the old bug management server and starting to use the "Issues" here with no bugs there. This is for me much worse than missing roadmap.
I understand, that Zentyal project unfortunately collapsed into one man show and appreciate very much that jacalvo continues working on it but this approach makes it slowly very risky for using it. 
So for me, the completely missing communication (e.g. no one sentence about what happened with all these reported bugs, no one sentence what are the plans, is at least jacalvo trusts the future of Zentyal, ...)  is what becomes slowly a blocker for using it further. Very, very, very sad. 
BTW.: There is some old general roadmap and a visible work (commits) in master branch, which could make possible to follow this old roadmap and release in some months the 6.0 version based on Ubuntu 18.04. but, who knows ....

**Comment by jacalvo** [comment]
Zentyal 6.0 based on Ubuntu 18.04 has been released :)
