### ISSUE TITLE
Feature Request: migration from MySQL 5.x to MariaDB 10.x or PostgreSQL 10.x

### ISSUE THREAD

**Issue by unquietwiki** [zentyal/zentyal#1825]
Oracle likes to be funny with their software licensing; and I've seen a recent use case for PostgreSQL in saving [IP address data](https://github.com/digitalocean/netbox/). A migration to MariaDB 10.x, or PostgreSQL 10.x; should be considered.

- https://mariadb.com/kb/en/library/upgrading-from-mysql-57-to-mariadb-102/ -> the few reported limitations of going from MySQL 5.7 to MariaDB 10.2
- https://pypi.org/project/pg_chameleon/ -> looks like it could handle a conversion to PGSQL

**Comment by brunolorente** [comment]
Thank you for reporting this. Please note that
• This doesn't currently fit our roadmap because other priorities exists.

Closing the issue.
