### ISSUE TITLE
Source issue: conflicting sogo files

### ISSUE THREAD

**Issue by unquietwiki** [zentyal/zentyal#1828]
- https://github.com/zentyal/zentyal/blob/master/main/sogo/stubs/sogo.conf.mas
- https://github.com/zentyal/zentyal/blob/master/main/sogo/stubs/SOGo.conf.mas

These files cancel each other out on Windows for editing, and appear to conflict with each other in content. It's preventing git rebase, and most likely a deployment problem waiting to happen. Help! Thanks.

**Comment by Neustradamus** [comment]
It was https://tracker.zentyal.org/issues/5237
