### ISSUE TITLE
debian.cnf missing on ubuntu 18.04

### ISSUE THREAD

**Issue by yxmline** [zentyal/zentyal#1832]
debian.cnf missing on ubuntu 18.04

sudo apt-get install zentyal zentyal-core zentyal-software

mysql: [ERROR] Could not open required defaults file: /etc/mysql/debian.cnf
mysql: [ERROR] Fatal error in defaults handling. Program aborted!
Creating the zentyal database
mysql: [ERROR] Could not open required defaults file: /etc/mysql/debian.cnf
mysql: [ERROR] Fatal error in defaults handling. Program aborted!
mysql: [ERROR] Could not open required defaults file: /etc/mysql/debian.cnf
mysql: [ERROR] Fatal error in defaults handling. Program aborted!
mysql: [ERROR] Could not open required defaults file: /etc/mysql/debian.cnf
mysql: [ERROR] Fatal error in defaults handling. Program aborted!
mysql: [ERROR] Could not open required defaults file: /etc/mysql/debian.cnf
mysql: [ERROR] Fatal error in defaults handling. Program aborted!
Connection DB Error: Access denied for user 'zentyal'@'localhost' (using password: YES)
Connection DB Error: Access denied for user 'zentyal'@'localhost' (using password: YES)

ubuntu no debian.cnf file

ubuntu mysql conf list
ll /etc/mysql/
conf.d/
my.cnf -> /etc/alternatives/my.cnf
my.cnf.fallback
mysql.cnf
mysql.conf.d/

cannot creating zentyal database

**Comment by jacalvo** [comment]
How did you install that Ubuntu 18.04? That file is present in our installations...

**Comment by yxmline** [comment]
https://wiki.zentyal.org/wiki/Installation_Guide
`curl download.zentyal.com/install | sudo sh`

**Comment by brunolorente** [comment]
Thank you for reporting this. Please note that
• This is not a bug, but configuration related error. Please check the official documentation at doc.zentyal.org regarding the feature and ask for help via forum.zentyal.org. Closing the issue.
