### ISSUE TITLE
Bug #5281: Problem with ejabberd (XMPP) to enable vhost etc

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1833]
-> https://tracker.zentyal.org/issues/5281

**Comment by jacalvo** [comment]
Please note that if you continue hitting this issue in the 6.0 version, you should provide all the necessary information that will help us to reproduce it in this ticket. If you fail to do so, we will close the ticket.

**Comment by brunolorente** [comment]
Please note that we need additional information to start working on this.

**Comment by Neustradamus** [comment]
More information about vhosts, it is in this page: https://docs.ejabberd.im/admin/configuration/

**Comment by brunolorente** [comment]
Quoting to my mate:

> Please note that if you continue hitting this issue in the 6.0 version, you should provide all the necessary information that will help us to reproduce it in this ticket. If you fail to do so, we will close the ticket.

Please, don't doubt to open a new issue when you have a log trace or something similar.

Regards,

**Comment by Neustradamus** [comment]
You will not add vhost options in Web admin?

- main domain
- second domain
- third domain
- ...

**Comment by Neustradamus** [comment]
Virtual Hosting: https://docs.ejabberd.im/admin/configuration/#virtual-hosting

**Comment by Neustradamus** [comment]
@brunolorente: Do not forget this ticket about XMPP too for the new release.
