### ISSUE TITLE
Bug #5295: Problem with ejabberd (XMPP) when the hostname is changed

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1835]
-> https://tracker.zentyal.org/issues/5295

**Comment by jacalvo** [comment]
Please note that if you continue hitting this issue in the 6.0 version, you should provide all the necessary information that will help us to reproduce it in this ticket. If you fail to do so, we will close the ticket.

**Comment by Neustradamus** [comment]
Any news?

**Comment by Neustradamus** [comment]
@brunolorente : Install a Zentyal server, enable the XMPP module, change the hostname, look now the XMPP server : problem.

**Comment by Neustradamus** [comment]
@brunolorente: It is always a good bug, please try it: it is important.
