### ISSUE TITLE
Let’s Encrypt support

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1836]
Can you add the Let’s Encrypt support?

http://letsencrypt.org/

**Comment by Neustradamus** [comment]
@brunolorente?

**Comment by dmartini1337** [comment]
Let´s Encrypt support would be very nice!

**Comment by brunolorente** [comment]
Thank you for the proposal, this is a good idea and we have added
it on our ToDo list. Stay tuned for updates as we progress in the
implementation.

**Comment by Neustradamus** [comment]
@brunolorente: Thanks, I am happy to see that the development has been relaunched.

**Comment by brunolorente** [comment]
Hi @Neustradamus ,

In the official documentation of Zentyal 6.1 we added a new section called "Let's Encrypt configuration2 where we explained how to use Let's Encrypt in Zentyal.

Also, for your information, we still have this item in our to-do list, but, we have other priorities right now.

Best regards, Bruno Lorente

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89: Can you reopen this unsolved ticket?
