### ISSUE TITLE
Missing Dynamic RPC Ports in Firewall rules

### ISSUE THREAD

**Issue by ringe** [zentyal/zentyal#1837]
I couldn't get why the new Windows 10 client had timeout on the user profiles (according to the windows event log). Also, the domain logon took forever.

So I opened the firewall for all traffic from the internal network, and no issues.

Then I found this page:
https://wiki.samba.org/index.php/Samba_AD_DC_Port_Usage

And I added the Dynamic RPC Ports range to the Samba service definition in the network section of the Zentyal admin panel. Then set the firewall back to original settings.

Boom. It works.

I suggest adding the ports mentioned by default.

**Comment by ringe** [comment]
Also, I had to add port 901 to the Samba service, in order to get GPO updates working.

**Comment by Neustradamus** [comment]
@jacalvo: and the 901 port?
https://www.samba.org/samba/docs/old/Samba3-HOWTO/SWAT.html

**Comment by Neustradamus** [comment]
@brunolorente: About the missing 901 port?
https://www.samba.org/samba/docs/old/Samba3-HOWTO/SWAT.html

**Comment by Neustradamus** [comment]
@ringe: It is solved or not?
