### ISSUE TITLE
Apache2 SOGo.conf problem

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1840]
There are 2 configuration files:
* /etc/apache2/conf.d/SOGo.conf
* /etc/apache2/conf-available/SOGo.conf (+ /etc/apache2/conf-enabled/SOGo.conf of course)

**Comment by Neustradamus** [comment]
In the same time update the source file with the last version: https://github.com/inverse-inc/sogo/blob/master/Apache/SOGo.conf in https://github.com/zentyal/zentyal/blob/master/main/sogo/stubs/SOGo.conf-apache.mas

**Comment by jacalvo** [comment]
/etc/apache2/conf.d/SOGo.conf is installed by the sogo package, not by zentyal-sogo, you can safely remove it as conf.d/* is not included (only conf-enabled/*).

About the proposed changes in SOGo.conf-apache.mas, if you think there is anything to be fixed or improved, and it doesn't break anything, please open a pull request with them and they will be reviewed before merged.
