### ISSUE TITLE
Ejabber and shared_roster

### ISSUE THREAD

**Issue by KOV70** [zentyal/zentyal#1842]
In Zen5 don`t work shared_roster. After upgarde to zen6 nothing changed. Pidgin does not show groups and users.

In log: ejabber restarted, then 2 users connect (karov and cheos, group IT).

[ejabberd.log](https://github.com/zentyal/zentyal/files/2599891/ejabberd.log)

Can any other data help to solve the problem?

**Comment by Neustradamus** [comment]
What is your ejabberd version?

**Comment by KOV70** [comment]
Weird question. In version 6 of zentiyal, version 18 of jabber, [https://github.com/zentyal/zentyal/blob/master/main/jabber/ChangeLog](url)

**Comment by Neustradamus** [comment]
@brunolorente?

**Comment by Neustradamus** [comment]
@KOV70: Please update this ticket name by:
Ejabberd and shared_roster

And the second one: https://github.com/zentyal/zentyal/issues/1899
Ejabberd and shared_roster - part 2

Thanks in advance.
