### ISSUE TITLE
Restore settings form older versions

### ISSUE THREAD

**Issue by anselal** [zentyal/zentyal#1844]
Hi there,

I am running a very old version of Zentyal, I think it is 2.2.1 because it is based on Ubuntu 10.

I did a backup of the configuration and tried to restore it on a VM running Zentyal 6 (development) but it failed with an error that the versions do not match.

Is there an easy way to do the upgrade ?

**Comment by Neustradamus** [comment]
I know this wiki page but...
https://wiki.zentyal.org/wiki/Updating_your_Zentyal_Server

**Comment by anselal** [comment]
Unfortunately this does not work for me.

I better kill myself than upgrading from ubuntu 10 all tje way up to 18.

**Comment by jacalvo** [comment]
Please note that upgrading from Zentyal 2.2 to the latest version is not a simple process: the base distribution has changed four times (from Ubuntu Server 10.04 to Ubuntu Server 18.04), the directory service has changed from LDAP to Samba, etc. 

Depending on your scenario, you could try phased migration (from 2.2 to 3.0, from 3.0 to 3.2, from 3.2 to 4.0, etc.), clean install with (partial) data migration or fully clean install. If you want to try phased migration, you should see the migration notes for each upgrade, backup your deployment and test each migration thoroughly in lab.

If you want to evaluate getting help from our Support Team for the migration, do contact sales (via http://www.zentyal.com/about-us/contact-us/).

**Comment by Neustradamus** [comment]
@anselal: How have you done?

**Comment by anselal** [comment]
It was a PITA migrating. Zentyal 6 was essentially slower in my machine. Besides that, Zentyal 6 has by default disabled the option "Filtering rules from external networks to internal networks" for some reason and it was very hard to find how to enable it.

I don't know why they disabled it and why it was not documented.

I had to edit `/usr/share/zentyal/modules/firewall.yaml` and add the option `ExternalToInternalRuleTable` in the `models` section.

Why the heck did you disable that option in the first place ???

After migrating all the option I had some minor issues with some rules so I left the firewall as is with the old version...

If someone knows a better way to migrate please report here.

**Comment by Neustradamus** [comment]
@anselal: Thanks for your reply!
You do not have informations about your minor issues?
Changes can be integrated, I think...

@brunolorente: What do you think about "ExternalToInternalRuleTable"?

**Comment by anselal** [comment]
It's been a long time since I tried my config but for some reason I had issues with accessing some resources on the internal network. 

Maybe I ported something wrong, couldn't tell at that time and had no time to investigate
