### ISSUE TITLE
[Forum] Need SMF update and spams removal

### ISSUE THREAD

**Issue by userdevel** [zentyal/zentyal#1846]
Like there is here: https://forum.zentyal.org/index.php/topic,32404.msg109277.html#msg109277

Can you update the Simple Machines Forum (SMF) from 2.0.5 to 2.0.15?

"It is possible to update SMF for block spams etc?

SMF 2.0.15 Released
Mon, 20 Nov 2017 00:47:44 GMT
http://www.simplemachines.org/

Thanks in advance."

**Comment by jacalvo** [comment]
Please note that as GitHub is aimed exclusively for reporting Zentyal Server-related bugs or creating pull requests, this ticket will be closed as irrelevant. If you have any questions, doubts or suggestions, you can use other available community channels or contact us via http://www.zentyal.com/about-us/contact-us/

**Comment by Neustradamus** [comment]
@brunolorente: What do you think?
No changes since this ticket.
