### ISSUE TITLE
Zentyal 6 email blocking

### ISSUE THREAD

**Issue by doricece** [zentyal/zentyal#1847]
i have upgraded my Zentyal  5.1 to Zentyal 6 but every time i enable IDS/IPS module i have problems sending emails.
what i see in the mail log is:
"Host or domain name not found. Name service error for name=xxxx.com type=MX: Host not found, try again"

As soon as i disable IDs from the external interface the problem disappears

**Comment by Tiago2912** [comment]
Olá jacalvo, você consguiu solucionar o problema com o modulo IDS\IPS?
