### ISSUE TITLE
 USB WiFi Ralink MT7601U Does not work but sees WiFi networks (Resolved)

### ISSUE THREAD

**Issue by Giflop** [zentyal/zentyal#1848]
Здравствуйте формучане! 
Решил на Zentyal развернуть контроль домена совместно с прокси сервером.
Организовать работу входящего потока с помощью сетевого устройства TP-Link TL-WN727N (Ralink MT7601U), а выходящая линия на встроенной (PCI) сетевой карты, штатная в общем. Но карта внешняя не подключается к сетям WiFi но их видит. Устанавливал ("собирал" для модуля драйвер Ralink MT7601U) в итоге без успешно, ничего не получилось. Какие нужны выводы ? Что нужно предоставить ? wpa_supplicant попробовать настроить ?  Ах да) Zentyal 5.1. Извините за малую информативность.

Добрый вечер! Победа лежала на поверхности бытия скажем так)
Оказывается проблема решается установкой "менеджера сетей" командой:
Code: 
apt-get install network-manager-gnome

После установки необходимо перезагрузится и появится на панели задачи соответствующий значок с помощью которого можно осуществить подключения к любым беспроводным сетям. 
При этом монтаж необходимых директорий для работы WiFi "свистков" через терминал не нужен.
Все устройства хорошо распознаютъся и работают с сетями.
Все операции проводил на чистой версии Zentyal 5.1, что бы отсутствовали помехи со стороны тех компонентов которые ранее устанавливал.  

Hello formen!
I decided on Zentyal to deploy domain control together with a proxy server.
Organize the work of the incoming stream using the TP-Link TL-WN727N network device (Ralink MT7601U), and the outgoing line to the integrated (PCI) network card, staffed in general. But the external card does not connect to WiFi networks but sees them. I installed ("assembled" for the module the Ralink MT7601U driver) in the end without success, nothing happened. What approaches are needed? What you need to provide? wpa_supplicant try to configure? Oh yeah) Zentyal 5.1. Sorry for the little information.

Decision

Good evening! Victory lay on the surface of being say so)
It turns out the problem is solved by installing the network manager:
Code: 
apt-get install network-manager-gnome

After installation, you need to reboot and appear in the taskbar to help you connect to any wireless networks.
At the same time, installation of the necessary directories for the operation of WiFi “whistles” through the terminal is not needed.
All devices are well recognized and work with networks.
All operations carried out on a clean version of Zentyal 5.1, so that there would be no interference from those components that were previously installed.

**Comment by Neustradamus** [comment]
@brunolorente: Can you see for "network-manager-gnome"?
