### ISSUE TITLE
is there any way to export all users from DC to csv?

### ISSUE THREAD

**Issue by mrPsycho** [zentyal/zentyal#1852]
hello.

to workaroud all my tikets (#1849, #1817) - i'm going to reinstall domain controller from scratch. 

to do so i need export all users in domain. Preferably, with their passwords. 

Is there any solution?

**Comment by brunolorente** [comment]
Hi @mrPsycho 

What Zentyal version are you using? I've been working in several perl scripts that are able to import/export users and groups from several versions (from 4.1).

Regards!

**Comment by mrPsycho** [comment]
hello! 
we are using latest 6.

**Comment by Neustradamus** [comment]
@brunolorente?

**Comment by mrPsycho** [comment]
oh, cool)
