### ISSUE TITLE
LDAP over TLS (STARTTLS) and LDAP over SSL (LDAPS)

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1855]
How we can only enable a secure LDAP?

**Comment by Neustradamus** [comment]
Yes but by default: 636 instead of 389 and 3269 instead of 3268.

LDAP 389/tcp
LDAP over SSL 636/tcp
Global catalog LDAP 3268/tcp
Global catalog LDAP over SSL 3269/tcp

And disabled insecured ports.

**Comment by Neustradamus** [comment]
@brunolorente?

**Comment by loxK** [comment]
I can connect using STARTTLS on "non SSL" port with Apache Directory Studio

**Comment by Neustradamus** [comment]
@loxK : What modifications have you done?

**Comment by loxK** [comment]
none

**Comment by brunolorente** [comment]
Thank you for reporting this. Please note that
• this is not a bug, but configuration related error. Please check the official documentation at doc.zentyal.org regarding the feature and ask for help via forum.zentyal.org. 

Closing the issue.

**Comment by Neustradamus** [comment]
How it is possible to have a perfect Zentyal with:
- LDAP over TLS (STARTTLS)
- LDAP over SSL (LDAPS)
And disabled insecured ports.

For have:
- LDAP over SSL 636/tcp
- Global catalog LDAP over SSL 3269/tcp

This ticket is not solved.
