### ISSUE TITLE
Webserver module comeback?

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1856]
A lot of people request the comeback of the webserver module.

**Comment by mrPsycho** [comment]
one of solution - is to integrate https://yunohost.org

**Comment by brunolorente** [comment]
Thank you for reporting this. Please note that 
• At the moment, this doesn't currently fit our roadmap because other priorities exist.

Closing the issue.

**Comment by Neustradamus** [comment]
@brunolorente: Please do not close ticket if it is not solved.
Can you re-open it?
