### ISSUE TITLE
Is it possible to completely remove apache2 in favor of nginx?

### ISSUE THREAD

**Issue by Ace-COM** [zentyal/zentyal#1857]
Hello guys,

I am more into nginx than apache2 and I use nginx on zentyal to access all the functionalities within and behind (proxy) Zentyal server 6. So there is a question while Zentyal have them both installed out of the box:

**Is it possible to completely remove apache2 without ruining some functionalities of Zentyal Server?**

I would really like to get rid of it because everytime I restart the server I have to 
manually stop apache2
start nginx
start apache2 again because I am not sure it is not needed for something

Just to let you know: I use zentyal server as a gateway to my servers with a virtual host/proxies set up and an SSL offloading server (with LetsEncrypt). So Apache is completely useless for me, of course if it does not have any other functions...

I would like to know the options... if complete removal of apache2 would have no impact on the functionalities then I would vote for it and keep only nginx on the box. I may even try to contribute with nginx setup module (vhosts and proxy setup - maybe even with LetsEncrypt support) as this is the configuration I use at the time being.

What is your opinion?

Best regards

Sfx

**Comment by Neustradamus** [comment]
SOGo works with Apache 2.

**Comment by Ace-COM** [comment]
Isn't it only working as a proxy for SOGo? I am running Nginx as a proxy for SOGo and it seems to be completely fine, though I am not 100% sure it may not have some quirks I just do not see...

**Comment by hawkeyefla** [comment]
Either make a /etc/nginix/snippets/sogo.conf and include it in your sites-available configuration, or just add it right into your site-available.  This is what I have an webmail works flawlessly with nginx.

location	^~/SOGo	{
				proxy_pass http://127.0.0.1:20000;
				proxy_redirect http://127.0.0.1:20000 default;
# forward user's IP address
				proxy_set_header X-Real-IP $remote_addr;
				proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
				proxy_set_header Host $host;
				proxy_set_header x-webobjects-server-protocol HTTP/1.0;
				proxy_set_header x-webobjects-remote-host 127.0.0.1;
				proxy_set_header x-webobjects-server-name $server_name;
				proxy_set_header x-webobjects-server-url $scheme://$host;
				proxy_connect_timeout 90;
				proxy_send_timeout 90;
				proxy_read_timeout 90;
				proxy_buffer_size 4k;
				proxy_buffers 4 32k;
				proxy_busy_buffers_size 64k;
				proxy_temp_file_write_size 64k;
				client_max_body_size 50m;
				client_body_buffer_size 128k;
				break;
				}
	location 	/SOGo.woa/WebServerResources/	{
				alias /usr/lib/GNUstep/SOGo/WebServerResources/;
				allow all;
				}
	location	/SOGo/WebServerResources/	{
				alias /usr/lib/GNUstep/SOGo/WebServerResources/;
				allow all;
				}
	location	^/SOGo/so/ControlPanel/Products/([^/]*)/Resources/(.*)$	{
				alias /usr/lib/GNUstep/SOGo/$1.SOGo/Resources/$2;
				}
	location	^/SOGo/so/ControlPanel/Products/[^/]*UI/Resources/.*\.(jpg|png|gif|css|js)$	{
				alias /usr/lib/GNUstep/SOGo/$1.SOGo/Resources/$2;
				}

**Comment by Neustradamus** [comment]
@brunolorente?

**Comment by brunolorente** [comment]
Thank you for reporting this. Please note that some Zentyal services run over Apache, i'm talking about SOGo and its related feature... so I won't recommend you to remove it.

You could try to remove it, but in a future update... you'll probably have issues...

**Comment by Neustradamus** [comment]
SOGo and nginx, it works: http://wiki.sogo.nu/nginxSettings.
