### ISSUE TITLE
[WEBSITES/forum/wiki/doc/Planet] links problems + missing https...

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1858]
The website .org/.com footer:
- Bug tracker bad link : https://tracker.zentyal.org/projects/zentyal must be https://github.com/zentyal/zentyal/issues
- Dead RSS: http://www.zentyal.com/feed/
- Twitter: https://twitter.com/#!/zentyal -> https://twitter.com/zentyal

The forum header:
- Code: https://github.com/Zentyal/zentyal ->https://github.com/zentyal/zentyal
- Tracker: http://tracker.zentyal.org/ -> https://github.com/zentyal/zentyal/issues
- Zentyal Labs link: to be removed
- All zentyal.org links have not https
- https://zentyal.org/ https://planet.zentyal.org/ https://zentyal.com/ are missing

The wiki/doc/planet header:
- Code: https://github.com/Zentyal/zentyal ->https://github.com/zentyal/zentyal
- Tracker: https://tracker.zentyal.org/projects/zentyal ->https://github.com/zentyal/zentyal/issues

The planet: dead since 2014?

**Comment by brunolorente** [comment]
Hi,

We have been remastering and migrating all of our websites, so It probably was a temporary issue.

Closing this.
