### ISSUE TITLE
error while check  "Transparent Proxy" in ver 6

### ISSUE THREAD

**Issue by rashedrefaat** [zentyal/zentyal#1859]
when trying to check the option "Transparent Proxy" in ver 6 i got the below error : 

Can't locate object method "throw" via package "Can't call method "value" on an undefined value at /usr/share/perl5/EBox/Squid/Model/GeneralSettings.pm line 111. " (perhaps you forgot to load "Can't call method "value" on an undefined value at /usr/share/perl5/EBox/Squid/Model/GeneralSettings.pm line 111. "?) at /usr/share/perl5/EBox/Model/DataTable.pm line 1367. ...propagated at /usr/share/perl5/EBox/CGI/Controller/DataTable.pm line 232

**Comment by brunolorente** [comment]
Sorry @rashedrefaat but we cannot reproduce the issue

**Comment by Neustradamus** [comment]
@rashedrefaat: Have you found a solution?
