### ISSUE TITLE
update from 5.1.3 to 6 broke samba

### ISSUE THREAD

**Issue by mrPsycho** [zentyal/zentyal#1860]
it doesn’t start at boot. 
only way to start - manually stop ‘winbind’ and ‘nmbd’ and then start ‘samba-ad-dc’

and this was on clean system without any additional software!!! :((

**Comment by mrPsycho** [comment]
my workaround:
`
systemctl disable nmbd smb winbind
systemctl enable samba-ad-dc
`

after this samba DC starts as it should.

**Comment by Neustradamus** [comment]
@brunolorente: Have you seen?

**Comment by citystar-at** [comment]
seems like the same problem as Error updating 5.1.2 to 6 samba dependency. #1843

i did the following after upgrading:
sudo service smbd stop
sudo service nmbd stop
sudo service winbind stop
sudo dpkg --configure -a

systemctl mask smbd nmbd winbind
systemctl disable smbd nmbd winbind

then reboot

**Comment by Neustradamus** [comment]
@brunolorente: Have you seen?

**Comment by Neustradamus** [comment]
@brunolorente: Have you solved it in upgrade process?
