### ISSUE TITLE
Openvpn dont show vpn client/user ip in dashboard

### ISSUE THREAD

**Issue by lohmuller** [zentyal/zentyal#1862]
In the dashboard dont show the vpn client IP, only the public IP... 
![Image](https://i.imgur.com/oNfPutul.png)

I think is possible change this code to show
https://github.com/zentyal/zentyal/blob/9f7bd886f04c0976a072d421ef3019df4be46ba9/main/openvpn/src/EBox/OpenVPN.pm#L1272-L1293

**Comment by brunolorente** [comment]
Thank you for the proposal, this is a good idea and we are already working on including it in the next Zentyal Server version. 

Closing this for now.

**Comment by Neustradamus** [comment]
@brunolorente: Please do not close a ticket before the solution.
