### ISSUE TITLE
Can't install in Google Cloud; may impact other cloud hosts

### ISSUE THREAD

**Issue by unquietwiki** [zentyal/zentyal#1863]
Steps to reproduce...

- Install Ubuntu 18.04 LTS via Google Cloud
- Setup necessary firewall rules to open up at least port **tcp/8443** for web browser access.
- [Run installer script](https://wiki.zentyal.org/wiki/Installation_Guide#Zentyal_Installer_script)
- Browse to web page, and tell it to use DHCP on the network interface, when asked.
- Instance will attempt to re-do networking; and fail to become accessible.

**Comment by brunolorente** [comment]
Thank you for reporting this. Please note that

• This doesn't currently fit our roadmap because is a third party integration. Please check the official documentation at [doc](doc.zentyal.org) regarding the feature and ask for help via [forum](forum.zentyal.org). 

Closing the issue.

**Comment by Neustradamus** [comment]
@unquietwiki: It is solved now?

**Comment by unquietwiki** [comment]
@Neustradamus I don't have the environment setup for that anymore; I don't even work for the company I was trying that anymore either. Hopefully someone else can check it out; due apologies.
