### ISSUE TITLE
Can't call method "subModel" on an undefined value at /usr/share/perl5/EBox/Samba.pm line 336

### ISSUE THREAD

**Issue by mmartinello** [zentyal/zentyal#1865]
After **updating Zentyal from 5.1 to 6.0** the package **zentyal-samba** does not complete the update process due to this error:

```
root@server-z1:/# dpkg --configure -a
Setting up zentyal-samba (6.0.1) ...
Can't call method "subModel" on an undefined value at /usr/share/perl5/EBox/Samba.pm line 336.
dpkg: error processing package zentyal-samba (--configure):
 installed zentyal-samba package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 zentyal-samba
```

I tried to uninstall and reinstall **zentyal-samba** but the problem is the same.
The Samba module is unusable, so this is a big problem.
I searched for this problem but I did not find anything resolutive.

Could you help me please?
Thanks!

**Comment by mmartinello** [comment]
I solved purging the package **zentyal-samba** and reinstalling it from scratch.
But after this the user and group list in the Samba module became empty, so this is not a valid resolution.

**Comment by TravisRothlisberger** [comment]
The conditional at line 333 in Samba.pm is only used to add a service configuration for samba at TCP ports 49152 - 65535. I worked around this by temporarily modifying the conditional to if (0) { ... so that it wouldn't try and execute this. I then added the service configuration manually in the web interface. Everything seems to be OK so far.

**Comment by brunolorente** [comment]
Thank you for reporting this, we cannot reproduce the issue so we think that is an isolated issue.

**Comment by Neustradamus** [comment]
@mmartinello: Have you found a solution?
