### ISSUE TITLE
5.1.3: link-button to issue tracker not working

### ISSUE THREAD

**Issue by MichaelTheSwGuy** [zentyal/zentyal#1867]
Hi,
the button on the dashboard leads to
https://github.com/zentyal/zentyal/issuesprojects/zentyal/issues/new?utm_source=zentyal&utm_medium=dashboard&utm_campaign=newticket
which should be
https://github.com/zentyal/zentyal/issues/new?utm_source=zentyal&utm_medium=dashboard&utm_campaign=newticket
The link looks right on mouseover, but somehow that extra "projects/zentyal/issues" makes it's way into it.
Regards, Michael

**Comment by Neustradamus** [comment]
Or only: https://github.com/zentyal/zentyal/issues/new

**Comment by colonelpopcorn** [comment]
This looks more like a redirect issue on the server for the zentyal project website. The link is actually [here](https://github.com/zentyal/zentyal/blob/0c45df9a1349956c6f3434f09883c3dc392bfb28/main/core/src/templates/dashboard/links-widget.mas#L29) and points to [here](https://tracker.zentyal.org/projects/zentyal/issues/new?utm_source=zentyal&utm_medium=dashboard&utm_campaign=newticket). Not sure if this is something that can be fixed here.

**Comment by brunolorente** [comment]
Thank you for reporting this. We have reproduced the issue and are working on a fix.

**Comment by brunolorente** [comment]
fixed in commit 958d1bab74c12f0a187ff381c931cc47ec1dcd12
