### ISSUE TITLE
DNS Update failed after adding additional domain controller

### ISSUE THREAD

**Issue by kedarapte27** [zentyal/zentyal#1870]
Hi,
I create da primary domain controller using Zentyal 6.0. I was able to use it as expected. When I added one more zentyal server 6.0 as an additional domain controller got the below error. I am able to see the additional domain controller in the web console, users are getting replicated, groups etc.. everything works, but I am unable to ping the primary domain controller from the additional domain controller with hostname.

Below is the error

xxx@adc2:~$ sudo tail -f /var/log/zentyal/zentyal.log 
eval {...} at /usr/share/zentyal/global-action line 30
2019/04/10 14:49:00 ERROR> GlobalImpl.pm:686 EBox::GlobalImpl::saveAllModules - Failed to restart dns after save changes: root command nsupdate -g -t 10 /var/lib/zentyal/tmp/WjmqLzkGoB failed. 
Error output: update failed: REFUSED

Command output: . 
Exit value: 2
2019/04/10 14:49:00 ERROR> GlobalImpl.pm:727 EBox::GlobalImpl::saveAllModules - The following modules failed while saving their changes, their state is unknown: dns  at The following modules failed while saving their changes, their state is unknown: dns  at /usr/share/perl5/EBox/GlobalImpl.pm line 727
EBox::GlobalImpl::saveAllModules('EBox::GlobalImpl=HASH(0x55b89c6f9390)', 'progress', 'EBox::ProgressIndicator=HASH(0x55b89bcde560)') called at /usr/share/perl5/EBox/Global.pm line 95
EBox::Global::AUTOLOAD('EBox::Global=HASH(0x55b89bcddfc0)', 'progress', 'EBox::ProgressIndicator=HASH(0x55b89bcde560)') called at /usr/share/zentyal/global-action line 32
eval {...} at /usr/share/zentyal/global-action line 30

**Comment by mmiat** [comment]
me too, also as #1819

**Comment by mmiat** [comment]
in my case, I fixed after last update and a reboot

**Comment by brunolorente** [comment]
It seems like a dnsadmins group issue, you need to check the 'DnsAdmins' group in every server in order to verify wheter the DNS user of each server has a membership for this group. You also may check the following [link](https://wiki.samba.org/index.php/Verifying_and_Creating_a_DC_DNS_Record)

**Comment by Neustradamus** [comment]
@kerk12, @kedarapte27, @mmiat: It is solved?

**Comment by Neustradamus** [comment]
@kerk12, @kedarapte27, @mmiat: It is solved?

**Comment by mmiat** [comment]
@Neustradamus for me yes

**Comment by kedarapte27** [comment]
Yes for me.

**Comment by Neustradamus** [comment]
@mmiat, @kedarapte27: What have you done exactly?
Maybe it is needed to add a service restart?

**Comment by mmiat** [comment]
@Neustradamus simply update and reboot
