### ISSUE TITLE
Zentyal 5.1 : Promote Additional DC as Primary result in erease all objects - How to Promote an Addition DC as Primary?

### ISSUE THREAD

**Issue by jaganz** [zentyal/zentyal#1871]
Hi,

After a problem with our dc1 (created as primary dc) we have created a new dc called dc1new restored from another addition dc called dc2 , then we have seized all roles from dc1 to dc1new , all seems good but on dc1new web interface continue to show that dc1new is an additional domain and info is about the dc2 ...  we have some major and minor problem, major that can't backup and restore the dc, or we can't dcpromo a windows server 2008 R2...

We have created a test environment to simulate the promote of dc1new as primary dc , but change dc1new as primary result (as warned) in resetting all objects and all objects destroyed.

What is the correct path to do this and preserve the active directory object?

I have resumed an old bug track with the same question (https://web.archive.org/web/20140126031400/http://trac.zentyal.org/ticket/8009) and the last answer was "buy a subscription and open a ticket" ... is this still the zentyal policy or the bug has been fixed?

thak you

**Comment by brunolorente** [comment]
Hi,

Thank you for reporting this. This is an expected behavior, you can't restore a config backup of your server if you have configure it as ADC, this piece of code will explain what I mean:

`my $modeDC = $self->dcMode();
    unless ($modeDC eq EBox::Samba::Model::DomainSettings::MODE_DC()) {
        # Restoring an ADC will corrupt entire domain as sync data
        # get out of sync.
        EBox::info(__("Restore is only possible if the server is the unique " .
                      "domain controller of the forest"));
        $self->getProvision->setProvisioned(0);
        return;
    }`

You'll find the code above on Samba.pm
