### ISSUE TITLE
OpenVPN stub - can't validate certificate cn prefix correctly

### ISSUE THREAD

**Issue by dbseoane** [zentyal/zentyal#1874]
The template file of the OpenVPN configuration server has the parameter verify-x509-name incorrectly configured to allow a prefix certificate. In the current way, it only allow to connect with a certificate having the exact CN match, not a prefix.
```
# client certificate common name authentication
% if (defined $ tlsRemote) {
verify-x509-name <% $ tlsRemote%> name
%}
```

To work properly, it is necessary to change it in the following way:
```
# client certificate common name authentication
% if (defined $ tlsRemote) {
verify-x509-name <% $ tlsRemote%> name-prefix
%}
```

**Comment by brunolorente** [comment]
Hi @dbseoane, thank you for your comment,

Under our point of view, your suggestion is valid, but we think that the complete CN check improves the server security, why? On this way, Zentyal prevents several ways of use of malicious certificates.

On the other hand, as I said, your suggestion is valid, so... feel free to use it if you need.
