### ISSUE TITLE
[DNS] Allow sharing IP

### ISSUE THREAD

**Issue by loxK** [zentyal/zentyal#1878]
I need to have some domains configured to the same IP. 
Zentyal WebUI refuses it.

**Comment by brunolorente** [comment]
If you need to do something with the DNS module which the Zentyal Admin Interface doesn't support, you could use the [Zentyal stubs](https://doc.zentyal.org/en/appendix-c.html#stubs). In many cases you will be able to achieve your goal using this feature, in others, it could be a manufacturer limitation or Zentyal limitation.

On the other hand, if you are using the Domain Controller module, you could use the 'samba-tool' command or the RSAT, here you have more info: https://wiki.samba.org/index.php/DNS_Administration

In other cases, once again, keep in mind that you can use the stubs to modify the behavior of a module like this link explains: https://doc.zentyal.org/en/appendix-c.html#stubs

**Comment by Neustradamus** [comment]
@brunolorente: It is not possible to add options in Web admin?

**Comment by Neustradamus** [comment]
Thanks @brunolorente for this change!
One problem in less:
- https://github.com/zentyal/zentyal/commit/68f2b755aca6c202f7fb384bff11f48e5d2f9ba7
