### ISSUE TITLE
VPNs expire with CRL every 30 days

### ISSUE THREAD

**Issue by tomasz89** [zentyal/zentyal#1883]
I noticed that every 30 days the VPN clients would not be able to connect. The OpenVPN logs state "error=CRL has expired".

This lead me to look at the CRL:
openssl crl -text -noout -in /var/lib/zentyal/CA/crl/latest.pem

Two fields is particular stuck out:
        Last Update: xxx
        Next Update: xxx + 1 month

And sure enough those dates and times aligned with when things worked and stopped working. So I wanted to change that update to be >30 days (3650 should do me).

I edited /var/lib/zentyal/conf/openssl.cnf and changed the CRL default time:
default_crl_days= 3650			# how long before next CRL

I now have a fairly length time before I am forced to re-evaluate my CRLs.

**Comment by tomasz89** [comment]
#1882 Bundled the fix in here.

**Comment by brunolorente** [comment]
Hi @tomasz89 thank you for reporting this. We have reproduced the issue and
are working on a fix.

**Comment by brunolorente** [comment]
Hi @ tomasz89 ,

The bug have been fixed for Zentyal 6.1 and Zentyal 6.2 in 7d66ea222e3efe8cf335d576686ece3bc297be84, also, we have added a section in the official Zentyal 6.2 documentation (it will be released very soon) regarding to this behaviour.

Many thanks for reporting it and your patience.
