### ISSUE TITLE
Jabber is XMPP since 2004

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1885]
If you did not know, Jabber has been renamed to XMPP in 2004.
Maybe time to rename the module?
And solve the bug when the hostname is changed, it will be perfect too:
- https://github.com/zentyal/zentyal/issues/1835

**Comment by brunolorente** [comment]
Hi @Neustradamus,

XMPP is the protocol which ejarbberd (which is used by Jabber module in Zentyal Server) uses to work.

useful links:

- https://www.ejabberd.im/
- https://en.wikipedia.org/wiki/XMPP

Closing as invalid.

**Comment by Neustradamus** [comment]
Yes, Jabber has been renamed XMPP in 2004.
I hope a XMPP module instead of Jabber module in Zentyal :)

- https://xmpp.org/about/history.html History of XMPP on XSF
- https://xmpp.org/ XMPP Standards Foundation
- https://en.wikipedia.org/wiki/XMPP (I am a very old contributor of this page)
- https://gajim.org/ Gajim XMPP client
- https://psi-im.org/ Psi XMPP client
