### ISSUE TITLE
Include account expires in user edit page.

### ISSUE THREAD

**Issue by tlparolin** [zentyal/zentyal#1886]
Is there any way to include in zentyal ui, a field for change user account expiration info?
(like rsat, account expires: never or schedule a date.)

**Comment by brunolorente** [comment]
You can't check out this info in Zentyal GUI, but you could use the samba-tool command to set the expiration of the user. 

On the other hand, you can use the ldbedit command looking for an account and check out the accountExpiration attribute for that account

**Comment by tinokorth** [comment]
Hello @brunolorente,

the expiration setting you can query with samba-tool and the internal expiration in Zentyal seens not to be directly connected to each other.
We've got the problem that accounts are expiring, but the expiration date is far far in the future.

So we've to change the password of the user and after that he is able to login.

So it's really interesting to see a bit more informations about a user.

BR, Tino
