### ISSUE TITLE
Logrotate for Squid generating daily error 'to_localhost' ACL

### ISSUE THREAD

**Issue by tomasz89** [zentyal/zentyal#1887]
Anacron is sending daily emails on logrotation:
/etc/cron.daily/logrotate: WARNING: (B) '127.0.0.0/8' is a subnetwork of (A) '127.0.0.0/8'

This is because the newer version of squid has these rules implicitly and does not need them stipulated in the configuration file.

**Comment by tomasz89** [comment]
#5ee41e649cf330b72dca816288a7c2f93979dec5

**Comment by tomasz89** [comment]
#1882 fix bundled in this pull request.

**Comment by brunolorente** [comment]
Thank you for reporting this. We have reproduced the issue and
are working on a fix.

**Comment by tomasz89** [comment]
Here it is again (as the bundle included) but for some reason it's still not in 6.1:

--- squid.conf.mas.bak	2019-11-03 07:07:36.963806559 +1030
+++ squid.conf.mas	2019-11-03 07:08:02.545933617 +1030
@@ -416,7 +416,6 @@
 
 
 acl from_localhost src 127.0.0.0/8 ::1
-acl to_localhost dst 127.0.0.0/8 ::1
 acl manager url_regex -i ^cache_object:// +i ^https?://[^/]+/squid-internal-mgr/
 acl SSL_ports port 443          # https, snews
 acl SSL_ports port 873          # rsync

**Comment by brunolorente** [comment]
Fixed in 391b9a6a692793909722dccb1fc30560580306f8
