### ISSUE TITLE
Single Label Domains

### ISSUE THREAD

**Issue by aaloise** [zentyal/zentyal#1888]
Consider allowing Zentyal to join single label domais. Currently I'm unable to use Zentyal as a DC because our domain doesn't have a suffix.

I found a possible workaround, but doesn't seem to work.

https://forum.zentyal.org/index.php/topic,20057

**Comment by brunolorente** [comment]
Thank you for reporting this. Please note that this doesn't currently fit our roadmap because FIXME.
Closing the issue.

**Comment by Neustradamus** [comment]
@brunolorente: It is not possible to add an option in the webadmin to enable it?
