### ISSUE TITLE
DNS issue with PTR?

### ISSUE THREAD

**Issue by killmasta93** [zentyal/zentyal#1900]
Hi,
I was wondering if zentyal has pushed update on the issue 
 for the DNS, i can resolve the name but when i try to resolve by IP it cannot find it, in theory the DHCP should inject it.

I was reading this topic https://forum.zentyal.org/index.php?topic=31202.0
but it seems that sometimes it works 

Thank you

**Comment by brunolorente** [comment]
Hi @killmasta93 ,
We have fixed it in 5196c98 and then, we fixed a permissions issue in 74e9248. I recommend you to update to 6.1

Thank you!
