### ISSUE TITLE
Add an option in webadmin to have multiple domains to same ip address

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1902]
> I have Zentyal Development Edition 5.1.
> I need more DNS domains that link to same address IP.
> 
> The Zentyal domain is "bs.lan" and I need set some DNS, for example "gitea.bs.lan" and "site.com" to same ip address (192.168.1.6).
> 
> For "gitea.bs.lan" I doesn't have problems: I can add it as new Hostname of "bs.lan" domain of DNS section and set the IP address.
> I don't know how to configure "site.com". If I add the new domain "site.com", then I cannot set the same IP address because I have the "The IP '192.168.1.6' is already in 'gitea.bs.lan'" message error.

Linked to:
- https://forum.zentyal.org/index.php?topic=32414.0
- https://forum.zentyal.org/index.php?topic=33635.0

Solution:
> There is a configuration key located in '/etc/zentyal/dns.conf' called 'allow_duplicated_ips' that will allow you to configure the same IP address in multiple domains, you just need to change its value for 'yes' and then, restart the webadmin module running 'sudo zs webadmin restart'. 

Linked to:
- https://github.com/zentyal/zentyal/issues/1878

**Comment by brunolorente** [comment]
Hi @Neustradamus,

We did the current module setup to prevent user failures, but we are going to revert it. We will fix it into the next DNS package release.

**Comment by brunolorente** [comment]
Stay tuned for updates as we progress in the implementation.

**Comment by Neustradamus** [comment]
@brunolorente: thanks for your reply but please do not close before solution...

**Comment by Neustradamus** [comment]
@brunolorente: Please open this ticket? You will forget because it is already closed.

**Comment by Neustradamus** [comment]
Thanks @brunolorente for this change!
One problem in less:
- https://github.com/zentyal/zentyal/commit/68f2b755aca6c202f7fb384bff11f48e5d2f9ba7
