### ISSUE TITLE
Dovecot with NTLM and GSS-SPNEGO authentication mechanisms (Samba's winbind daemon)

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1906]
Dovecot supports NTLM and GSS-SPNEGO authentication mechanisms using Samba's winbind daemon. It is useful when you need to authenticate users against a Windows domain (either AD or NT).

Source: https://wiki.dovecot.org/Authentication/Mechanisms/Winbind

Zentyal configuration file:
- https://github.com/zentyal/zentyal/blob/master/main/mail/extra/dovecot-pam

**Comment by brunolorente** [comment]
Hi @Neustradamus ,

Thank sfor your proposal, but we think about the integration between Domain Controller module and Mail is stable and robust, so, we have decided to not implement your request, however, remember that you can use the proper stub to achieve this in your own Zentyal servers.

One more time, many thanks for your contribution.
