### ISSUE TITLE
6.1 and raid

### ISSUE THREAD

**Issue by mrPsycho** [zentyal/zentyal#1907]
Hello,

suddenly noticed that on site 6.1 already possible to install... and i tried it with no luck if i try to partition how i want it. 

when i press manul on partition menu - red screen appears. 

![photo_2019-11-02_15-50-32](https://user-images.githubusercontent.com/883964/68071944-96ddab00-fd88-11e9-8de9-80193cf199b3.jpg)

how it is possible to install zentyal on software raid?

**Comment by brunolorente** [comment]
Hi @mrPsycho,

Thank you for reporting this. Please note that this is not a bug, but configuration related error. 

This is a configuration mistake, the installation works properly for each Ubuntu partitioning schema like RAID0, RAID1, RAID4, etc...

You probably didn't select any raid volume as root system. Anyway, you could ask for help via [forum.zentyal.org](https://forum.zentyal.org/).

**Comment by mrPsycho** [comment]
i solved by installing ubuntu on raid (via internal configurator) and then installing zenytal as package. 
but internal installer in zentyal - sucked.

**Comment by Neustradamus** [comment]
@brunolorente, @djovn89, @testdeploys, @mrPsycho: It is possible to add possibility in Zentyal installer?

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89, @testdeploys, @mrPsycho: It is possible to add possibility directly in Zentyal installer?
