### ISSUE TITLE
nginx and SOGo instead of Apache HTTPd and SOGo

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1909]
It is possible to replace Apache HTTPd to nginx for SOGo?

- http://wiki.sogo.nu/nginxSettings
- https://mailcow.github.io/mailcow-dockerized-docs/firststeps-rp/#nginx

**Comment by brunolorente** [comment]
No,
Nginx is reserved in Zentyal for other purposes so we are going to maintain it running with Apache

Best regards

**Comment by Neustradamus** [comment]
It will be nice to have nginx for SOGo too.
- Less memory usage
- One software is less

The Apache HTTPd can be used by webserver part:
- https://github.com/zentyal/zentyal/issues/1856
But it can be nginx of course.
