### ISSUE TITLE
Apache HTTPd: SSL cert problem in error.log

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1914]
In /var/log/apache2/error.log:
> [XXX XXX XX XX:XX:XX.XXXXXX XXXX] [ssl:warn] [pid XXXXX:tid XXXXXXXXXXXXXXX] AH01909: zentyal.zentyal-domain.lan:443:0 server certificate does NOT include an ID which matches the server name
> [XXX XXX XX XX:XX:XX.XXXXXX XXXX] [ssl:warn] [pid XXXXX:tid XXXXXXXXXXXXXXX] AH01909: zentyal.zentyal-domain.lan:443:0 server certificate does NOT include an ID which matches the server name

**Comment by brunolorente** [comment]
Hi @Neustradamus ,

To avoid these kind of messages you need a certificate issued by a recognized CA. We recommend to take a look at the Zentyal documentation where it is explained how to implement Let's Encrypt in Zentyal.
