### ISSUE TITLE
Improvements for ejabberd

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1916]
Option to disable old points, for more security in ejabberd.yml
    - "no_sslv2"
    - "no_sslv3"
    - "no_tlsv1"
    - "no_tlsv1_1"
Of course, there is "no_tlsv1_2" too.

Change LDAP by LDAP with TLS:
- https://docs.ejabberd.im/admin/configuration/#ldap-connection
ldap_port: 389
->
ldap_port: 636
ldap_encrypt: tls

Look for:
ldap_tls_verify: false|soft|hard
ldap_tls_cacertfile: Path
ldap_tls_depth: Number

DNS -> Services (SRV records)
- https://wiki.xmpp.org/web/SRV_Records

ejabberd webadmin? 5280?
- https://github.com/processone/ejabberd/blob/master/ejabberd.yml.example#L27

Rename:
- Jabber -> XMPP
- Jabber domain -> XMPP domain
- SSL support -> TLS support
- SSL connection method to this server. -> TLS connection method to this server.
- Allow SSL -> Allow TLS
- Force SSL -> Force TLS

**Comment by Neustradamus** [comment]
@brunolorente: Thanks for your changes but it is not complete, please read again!

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89, @testdeploys: Can you look it?
It is not complete!

**Comment by brunolorente** [comment]
Hi @Neustradamus,

We considered your suggestion but we discarted some of your points due the Zentyal architecture. Many other points have a higher priority.

Anyway, remember that you can create Pull Requests to improve the Zentyal features or help the community by creating a post with your hardening/tips contribution in our forum.

Happy New Year!
