### ISSUE TITLE
Upgrade Samba

### ISSUE THREAD

**Issue by Neustradamus** [zentyal/zentyal#1919]
Can you upgrade Samba?
- http://www.linuxfromscratch.org/blfs/view/svn/basicnet/samba.html
- https://lists.samba.org/archive/samba/2019-April/222191.html
- https://github.com/thctlo/samba4

**Comment by brunolorente** [comment]
Hi @Neustradamus,

We offer the same version than Ubuntu. Zentyal is based on the latest Ubuntu LTS (18.04.3) so we are using samba 4.7
