### ISSUE TITLE
How should a security issue be reported?

### ISSUE THREAD

**Issue by pcttech** [zentyal/zentyal#1921]
What is the preferred mechanism to report security issues that may not be appropriate to disclose publicly on GitHub? I've found a (likely-minor) security issue that I would like to responsibly disclose, but I have not found any information on how to share such reports with the Zentyal team privately.

Thanks!

**Comment by brunolorente** [comment]
Hi @pcttech 

First of all, many many thanks for your interest!

In order prevent spammers, you could send me the info via PM through [our forum](https://forum.zentyal.org/).

My username is blorente

**Comment by pcttech** [comment]
I registered but I am not allowed to send private messages yet. What's next?

**Comment by brunolorente** [comment]
Ok,

Tomorrow I'll talk with the forum admin about this

**Comment by Neustradamus** [comment]
@brunolorente: Can you update the forum software too?

More one year after, it is not done:
- https://github.com/zentyal/zentyal/issues/1846

**Comment by brunolorente** [comment]
@pcttech, you should be able to send me PMs at the forum.

**Comment by Neustradamus** [comment]
Warning : The forum is not secured (very old, with security vulnerabilities)

@brunolorente: I have requested you a better possibility to contact you here:
- https://github.com/zentyal/zentyal/issues/1931

**Comment by Neustradamus** [comment]
Solved 1 year and 3 months after...
