### ISSUE TITLE
Spelling mistake on Initial Setup screen

### ISSUE THREAD

**Issue by ryanhunt** [zentyal/zentyal#1922]
On first login to the webui, I'm presented with a screen that says:

"Thank your for choosing Zentyal, only few steps left to start enjoying it:"

I think it meant to say

"Thank **you** for choosing Zentyal, only **a** few steps left to start enjoying it:"

**Comment by brunolorente** [comment]
Hi @ryanhunt, thank you for reporting this.
We are going to add it to our roadmap.

Regards!
