### ISSUE TITLE
OpenVPN rejects certificates whose CN starts with specified CN prefix

### ISSUE THREAD

**Issue by Facsimiler** [zentyal/zentyal#1923]
**Describe the bug**
Under `VPN/Servers/Configuration`, there's a property **Client authorization by common name**, which states:

_If disabled, any client with a certificate generated by Zentyal will be able to connect. If enabled, only certificates whose common name begins with the selected value will be able to connect._

If this field is set to `disabled`, then _OpenVPN_ clients using a _Zentyal_-issued certificate are able to connect just fine.

However, if a certificate containing a _common name_ (_CN_) prefix is specified, then _OpenVPN_ clients using certificates with that prefix are rejected.

**To Reproduce**
1. Ensure that the _Logs_, and _VPN_ modules are installed, configured and enabled.
1. Ensure logging for _VPN_ is enabled.
1. Go to `Certification Authority/General` and issue a new certificate with the common name `SomeExamplePrefix`.
1. On the same screen, issue another certificate with the common name `SomeExamplePrefixForSomeClient`.
1. Go to `VPN\Servers` and configure a single server, advertising the whole _Zentyal_ sub-network. Under the server's `Configuration`, select the `SomeExamplePrefix` certificate under `Client authorization by common name`. (All other values should be set as required.)
1. Download the client bundle, using `SomeExamplePrefixForSomeClient` as the client's certificate. (All other values should be set as required.)
1. Install `OpenVPN` on a client, and use the downloaded client bundle to connect to the server, from a network other than the one _Zentyal_ administers.
1. Observe that a connection cannot be made and that _Zentyal_ reports (in the VPN logs): `Certificate common name not authorized`. (**Note**: It might be that _Zentyal_ is looking at the wrong attribute, since it identifies the `remote certificate` by its _Country_ code, `C=US`, in my case.)
1. Return to `VPN/Servers/Configuration` and change the `Client authorization by common name` certificate to `disabled`.
1. Attempt a VPN connection on the client once more, noting that it succeeds and that _Zentyal_ reports a successful connection with a `remote certificate` value of `SomeExamplePrefixForSomeClient`.

I've recently upgraded to 6.1 (from 4.0) and it used to work just fine.

**Expected behavior**
_VPN_ connections using client certificates whose _CN_ field _begins_ with the _CN_ field of the specified `Client authorization by common name` certificate (such certificates also being issued, and not revoked, by the _Zentyal_ administered _Certification Authority_, _CA_) should be accepted; all other client certificates should be rejected.

**Screenshots**
n/a

**Zentyal OS (please complete the following information):**
 - Version: 6.1
 - Version of the module which has the bug: `zentyal-openvpn` 6.1
 - Modules installed: _Network_, _Firewall_, _Antivirus_, _DNS_, _DHCP_, _Logs_, _NTP_, _VPN_, _Domain Controller and File Sharing_, _RADIUS_.

**Other OS (please complete the following information):**
 - OS: Ubuntu server
 - Version: 18.04.3 LTS, 64-bit

**Additional context**
In case it's relevant, I'm using the TUN interface (rather than TAP). Let me know if you need any further configuration settings.

**Comment by brunolorente** [comment]
Hi @Facsimiler 

When you set the certificate of the client in the configuration, the parameter added to the configuration is 'verify-x509-name', and this parameter can be configured with some other options like 'name-prefix'. For more information, please read the documentation https://openvpn.net/community-resources/reference-manual-for-openvpn-2-4/

Thank you for your time!

**Comment by Facsimiler** [comment]
This verification should be done on the server side (if clients can authenticate themselves, then there is no security), using the information entered on _Zentyal_'s VPN server configuration page. If I have to edit the server config manually to support the configuration I've entered, then why have that configuration page? Also, it's going to get overwritten when the master version is replaced. I don't think this issue is resolved, and I don't think it should be closed.

**Comment by Facsimiler** [comment]
@brunolorente

This fix is important for a number of reasons, but the primary one is to be able to revoke the certificate of a _specific_ client.

For example, let's say I have a _Zentyal_ VPN server, for which there are four clients. Each client is assigned a separate certificate, named `clientA`, `clientB`, `clientC` and `clientD`. I need to create another certificate, named `client`, which is identified as the **Client authorization by common name** field's value in that server's configuration in _Zentyal_. (I have no idea why it needs to be certificate name, it could just as easily be a string, but that's what _Zentyal_ has required for some time.)

Now, only clients whose certificate name _begins_ with `client` can connect to the server. If the client has a certificate whose name begins `mylaptop`, then it will not be allowed to connect, because its certificate's name does not begin with `client`.

However, it is also necessary for the clients to have certificates that are signed by the server's CA and that the certificates have not been revoked. Let's say that the laptop whose certificate is `clientC` is lost or stolen, and I want to ensure that it cannot be used to access my VPN network. Simple: we just revoke the `clientC` certificate, and all the other clients can still connect, but since `clientC` is now on the CRL, it can no longer correct.

With the server configured as at present (with the bug in effect), all clients must use either the same certificate (named `client`, for the case in which the **Client authorization by common name** field identifies the `client` certificate) or they can connect using _any_ certificate signed by the CA, which might not have been intended for VPN access. Either way, my options for controlling the security of the server are now far more complicated.

It appears that this bug was introduced when the `tls-remote` setting was replaced by the `verify-x509-name` setting in commit e7495dc57da8d9bc405af07dac2723cddc8ce4d6.

I will shortly be sumitting a PR which fixes this bug.

**Note**: this change is made only to the _server_'s VPN configuration, not to that of each _client_, which still must validate the server certificate using `name`, instead of `name-prefix`.

**Comment by brunolorente** [comment]
OK @Facsimiler your explanation makes sense, I have seen your PR but we are going to need a bit of time to evaluate other considerations. Until we fix it i'm going to maintain this ticket opened.

MANY many thanks for your time!

**Comment by Facsimiler** [comment]
@brunolorente Sure. Given that this involves the security of the VPN server, it makes sense that you'd want to consider everything in more detail. Please let me know if there's anything I can do to assist with that.

Thanks for re-opening this issue!

**Comment by Facsimiler** [comment]
Thanks @brunolorente! I'll make sure I pickup the new version when it's released...
