### ISSUE TITLE
Zentyal-virt-report error

### ISSUE THREAD

**Issue by dudumao520** [zentyal/zentyal#1924]
**Describe the bug**
Failed to start the virtual machine. After the configuration is completed, the error "error > sudo. PM: 240 ebox:: sudo:: ﹣ rooterror - root command / var / lib / zentyal / machines / test001 / manage. Sh start failed."

**All screenshots**
![001](https://user-images.githubusercontent.com/12032241/69931255-8b091400-1501-11ea-845d-dd55ee7be126.png)
![002](https://user-images.githubusercontent.com/12032241/69931256-8cd2d780-1501-11ea-815d-9be39f74b1ba.png)
![003](https://user-images.githubusercontent.com/12032241/69931259-8f353180-1501-11ea-95c3-fff4ac9dfb30.png)
![004](https://user-images.githubusercontent.com/12032241/69931260-8fcdc800-1501-11ea-9abd-deb5783b829c.png)
![005](https://user-images.githubusercontent.com/12032241/69931261-90665e80-1501-11ea-88eb-8fe9a80dc747.png)

**Comment by dudumao520** [comment]
zentyal 6.1 DEV Edition

**Comment by dudumao520** [comment]
> **Describe the bug**
> Failed to start the virtual machine. After the configuration is completed, the error "error > sudo. PM: 240 ebox:: sudo:: ﹣ rooterror - root command / var / lib / zentyal / machines / test001 / manage. Sh start failed."
> 
> **All screenshots**
> ![001](https://user-images.githubusercontent.com/12032241/69931255-8b091400-1501-11ea-845d-dd55ee7be126.png)
> ![002](https://user-images.githubusercontent.com/12032241/69931256-8cd2d780-1501-11ea-815d-9be39f74b1ba.png)
> ![003](https://user-images.githubusercontent.com/12032241/69931259-8f353180-1501-11ea-95c3-fff4ac9dfb30.png)
> ![004](https://user-images.githubusercontent.com/12032241/69931260-8fcdc800-1501-11ea-9abd-deb5783b829c.png)
> ![005](https://user-images.githubusercontent.com/12032241/69931261-90665e80-1501-11ea-88eb-8fe9a80dc747.png)

Zentyal Dev Edition 6.1 UBU18.04 LTS

**Comment by brunolorente** [comment]
We couldn't reproduce this issue, and this is the first time that we have been notified about this...

Additionally you can check your zentyal.log and libvirt/* in order to find more info.

Anyway, many thanks for your report @dudumao520 !

**Comment by Neustradamus** [comment]
@dudumao520: It is solved?
