### ISSUE TITLE
REinit DNS 

### ISSUE THREAD

**Issue by mrPsycho** [zentyal/zentyal#1927]
**Is your feature request related to a problem? Please describe.**
I have several issues with zentyal, and all of them are related to DNS.

**Describe the solution you'd like**
A way how to reinit DNS service. 

**Describe alternatives you've considered**
now only full reinstall will work... slow and not cool to use.

**Comment by brunolorente** [comment]
Hi @mrPsycho 

We just added the issue templates, and we have already release a new DNS package 1 minute ago, so... if you wish, try the new package, and then if you have some issue, please use our template, I think we can work better using this feature.

Many thanks for your time!

**Comment by mrPsycho** [comment]
Ok, raised #1928
