### ISSUE TITLE
samba shares.conf overwritten after reboot 

### ISSUE THREAD

**Issue by killmasta93** [zentyal/zentyal#1934]
**Describe the bug**
samba shares.conf overwritten after reboot, aftering adding config in /etc/samba/shares.conf gets overwritten after reboot

**Zentyal OS (please complete the following information):**
 - Version: [ 6.1]
 - Version of the module which has the bug [e.g. zentyal-dns-5.0.3]
 - Modules installed [DNS, DHCP AD

**Comment by djoven89** [comment]
Hi @killmasta93 

That's a normal behaviour, please, read about '**stubs**' in the documentation. [Here](https://doc.zentyal.org/en/appendix-c.html#stubs) you have the section that you need.

Best regards, Daniel Joven.

**Comment by killmasta93** [comment]
Thank you so much that did the trick
