### ISSUE TITLE
Zentyal 6[.1] installation issue 2

### ISSUE THREAD

**Issue by wintelkiller** [zentyal/zentyal#1936]
1. During Installation of Zentyal 6[.1] as a secondary domain controller, there is no "/etc/samba/smb.conf" file present. So SMBD and NMBD processes deny to start.
2. Also there is no possibility of LDAP clients to connect properly to the service on the primary server.

**Comment by djoven89** [comment]
Hi @wintelkiller,

Please, use the available template to create the issue, otherwise, we will close the issue.

**Comment by djoven89** [comment]
Closing the issue because you didn't follow the template.
