### ISSUE TITLE
Samba Issue with shadow copy

### ISSUE THREAD

**Issue by killmasta93** [zentyal/zentyal#1937]
**Describe the bug**
The time in the shadow copy does not show correct on the windows previous versions, as soon as i put shadow:localtime = yes and restart samba does not show previous versions which therefore i have to put shadow:localtime = no
Currently using pyznap for the snapshots of the ZFS file system
see pictures on the times not correct but both windows and zentyal have the correct time just the previous versions are now. The hour difference is about 5 hours behind  the last snapshot was 6:10pm on zentyal and on the previous versions on windows show 1:10 pm 
![image](https://user-images.githubusercontent.com/13953629/71855394-ea34e800-30ae-11ea-842f-4f6668d19a2e.png)
![image](https://user-images.githubusercontent.com/13953629/71855410-f1f48c80-30ae-11ea-8e1f-06e4acff3abc.png)

This is my samba share

```
[test]
    path = /data
    browseable = yes
    force create mode = 0660
    force directory mode = 0660
    valid users = @"Domain Users"
    read list =
    write list = @"Domain Users"
    admin users =
    vfs objects = acl_xattr full_audit recycle shadow_copy2
#    full_audit:failure = connect opendir disconnect unlink mkdir rmdir open rename
full_audit:prefix = %u|%I|%S
full_audit:failure = connect
full_audit:success = mkdir rename unlink rmdir pwrite pread connect disconnect
full_audit:facility = local5
full_audit:priority = notice
    recycle: inherit_nt_acl = Yes
    recycle: versions = Yes
    recycle: excludedir = /tmp|/var/tmp
    recycle: keeptree = Yes
    recycle: repository = RecycleBin
    recycle: directory_mode = 0700
shadow: snapdir = .zfs/snapshot
shadow: sort = desc
# Specify snapshot name: frequent, hourly, daily... as desired
shadow: format = _%Y-%m-%d_%H:%M:%S
shadow: snapprefix = ^pyznap
shadow: delimiter = _
shadow:localtime = no
```

**Zentyal OS (please complete the following information):**
 - Version:  6.1
 - Version of the module which has the bug Samba version 4.7.6-Ubuntu
 - Modules installed. DNS, DC

Thank you

**Comment by killmasta93** [comment]
edit: checking the logs found this as soon as i put shadow:localtime = yes

```
[2020/01/07 00:03:54.479092,  2] ../source3/smbd/vfs.c:1367(check_reduced_name)
  check_reduced_name: Could not get conn_rootdir
[2020/01/07 00:03:54.479124,  3] ../source3/smbd/filename.c:1644(filename_convert_internal)
  filename_convert_internal: check_name failed for name @GMT-2020.01.05-17.37.21 with NT_STATUS_ACCESS_DENIED
[2020/01/07 00:03:54.479138,  3] ../source3/smbd/smb2_server.c:3139(smbd_smb2_request_error_ex)
  smbd_smb2_request_error_ex: smbd_smb2_request_error_ex: idx[1] status[NT_STATUS_ACCESS_DENIED] || at ../source3/smbd/smb2_create.c:293
```

**Comment by djoven89** [comment]
Hi @killmasta93 ,

Please note that the issue you have is with a custom Samba configuration but not with a feature that Zentyal provides. For this cases you have to use the Zentyal's forum instead of Github.
