### ISSUE TITLE
Sharing folders in SOGo is not working.

### ISSUE THREAD

**Issue by wirdo89** [zentyal/zentyal#1939]
**Describe the bug**
When sharing a folder inside SOGo the permissions are gone right after saving it.

**To Reproduce**
Click on the 3 dots and share a certain folder.
Search for the user which needs the permissions, select the needed check boxes and save.

Once saved you can either open the dialog again or refresh which results in the permissions being gone.

**Expected behavior**
I expected the folder to share amongst the user I added. 

**Zentyal**
 - Version: 6.0.3 (Commercial)
 - Version of the module which has the bug: SOGO
 - Modules installed: Firewall, DNS, Backup, SAMBA, MAIL.

**Additional context**
I've been contact with SOGo as well and they cannot reproduce this issue at their current (latest) build.

**Log file after creating the share**
Jan 10 12:16:00 sogod [30253]: 192.168.12.13 "POST /SOGo/so/user/Mail/0/folderGedeelde_SP_map/folderAdministratie/view
HTTP/1.1" 200 856/48 0.366 - - 0
Jan 10 12:16:02 sogod [30253]: 192.168.12.13 "GET /SOGo/so/user/Mail/0/folderGedeelde_SP_map/folderAdministratie/acls
HTTP/1.1" 200 109/0 0.265 - - 0
2020-01-10 12:16:06.128 sogod[30253:30253] ERROR(-[NGLdapSearchResultEnumerator nextObject]): does not support result references yet ..
Jan 10 12:16:06 sogod [30253]: 192.168.12.13 "GET
/SOGo/so/user/usersSearch?search=user2 HTTP/1.1" 200 219/0 0.173 - - 0 Jan 10 12:16:08 sogod [30253]: 192.168.12.13 "GET /SOGo/so/user/Mail/0/folderGedeelde_SP_map/folderAdministratie/addUserInAcls
?uid=user2 HTTP/1.1" 204 0/0 0.429 - - 0 Jan 10 12:16:08 sogod [30253]: 192.168.12.13 "GET /SOGo/so/user/Mail/0/folderGedeelde_SP_map/folderAdministratie/userRights?ui
d=user2 HTTP/1.1" 200 255/0 0.384 - - 0
Jan 10 12:16:08 sogod [30248]: <0x0x559a4ee8d4d0[SOGoActiveSyncDispatcher]>
Sleeping 30 seconds while detecting changes for user assist in Ping...
Jan 10 12:16:12 sogod [30253]: 192.168.12.13 "POST /SOGo/so/user/Mail/0/folderGedeelde_SP_map/folderAdministratie/saveUserRight
s HTTP/1.1" 200 0/408 0.477 - - 0
Jan 10 12:16:16 sogod [30253]: 192.168.12.13 "POST /SOGo/so/user/Mail/0/folderGedeelde_SP_map/folderAdministratie/expunge
HTTP/1.1" 204 0/0 0.225 - - 0
Jan 10 12:16:16 sogod [30253]: 192.168.12.13 "GET /SOGo/so/user/Mail/view HTTP/1.1" 200 20288/0 0.031 78865 74% 0

**Comment by wirdo89** [comment]
I also wonder (perhaps it's not the right place here); Shouldn't we have been offered the 6.1 update by now? Perhaps that solves the issues we're facing but I don't get an option to update.

**Comment by djoven89** [comment]
Hi @wirdo89 ,

The solution is in the same forum's thread that you answered. We recommend you to give more details about your behaviour and wait until one user help you with your goal.

The link is: https://forum.zentyal.org/index.php/topic,33589.msg110860.html

Best regards.
