### ISSUE TITLE
Vacation responder missing after Zentyal upgrade to 6.1

### ISSUE THREAD

**Issue by FatPopDoWop01** [zentyal/zentyal#1941]
Upgraded a client's Zentyal server from 6.0 to 6.1 (Development Edition) last weekend, and one user tried to activate Vacation for this weekend and it is now missing. It was working perfectly in previous version, but now is not even an available option.

**Comment by FatPopDoWop01** [comment]
This was not a fault in the software. Rather it was a changed setting which may have been a result of the upgrade scripts. I fixed this by editing /usr/share/zentyal/stubs/sogo/sogo.conf.mas and changing SOGoVacationEnabled = NO;
 to 
SOGoVacationEnabled = YES;
 and then stopping and starting the SOGo Webmail module in the Zentyal Module Status page. Logging into the SOGo webmail interface and going to Settings, Mail, you can now see the Vacation option.

**Comment by Neustradamus** [comment]
@FatPopDoWop01: Upgraded script problem?

**Comment by FatPopDoWop01** [comment]
When Zentyal upgrades anything it runs more than just apt, and I was wondering if those parts specific to Zentyal may have caused the perceived settings change during the upgrade?
