### ISSUE TITLE
Issue with inheritance on shared folders

### ISSUE THREAD

**Issue by killmasta93** [zentyal/zentyal#1942]
**Describe the bug**
I create the folder inside shares, called test folder then i go to a windows server which is in the domain to disable the inheritance and only want that folder to be shared with the user test and the admin but i get the error permission denied

**Screenshots**
![image](https://user-images.githubusercontent.com/13953629/73139100-5bc1df80-4038-11ea-9890-a76c01d8b3ed.png)

**Zentyal OS (please complete the following information):**
 - Version: 6.1
 - Version of the module which has the bug: samba

samba share conf
```

[shares]
    path = /data
    browseable = yes
    force create mode = 0660
    force directory mode = 0660
    valid users = @"Domain Users"
    read list = 
    write list = @"Domain Users"
    admin users = 
    vfs objects = acl_xattr full_audit recycle shadow_copy2
#    full_audit:failure = connect opendir disconnect unlink mkdir rmdir open rename
full_audit:prefix = %u|%I|%S
full_audit:failure = connect
full_audit:success = mkdir rename unlink rmdir pwrite pread connect disconnect
full_audit:facility = local5
full_audit:priority = notice
shadow: snapdir = .zfs/snapshot
shadow: sort = desc
shadow: format = _%Y-%m-%d_%H:%M:%S
shadow: snapprefix = ^pyznap
shadow: delimiter = _
shadow:localtime = no
    recycle: excludedir = /tmp|/var/tmp
    recycle: directory_mode = 0700
    recycle: inherit_nt_acl = Yes
    recycle: keeptree = Yes
    recycle: versions = Yes
    recycle: repository = RecycleBin
```

**Comment by killmasta93** [comment]
it was  ZFS issue as the samba share is on ZFS

**Comment by Neustradamus** [comment]
@killmasta93: The solution?

**Comment by killmasta93** [comment]
oh sorry forgot to mention ran these commands on zentyal which has the disk ZFS

```
zfs set acltype=posixacl data
zfs set aclinherit=passthrough data
zfs set xattr=sa data

```
