### ISSUE TITLE
Add support for Wireguard VPN

### ISSUE THREAD

**Issue by renne** [zentyal/zentyal#1945]
**Is your feature request related to a problem? Please describe.**
OpenVPN, IPSec, etc. are complicated to configure and the outdated encryption algorithms are performance hogs.

**Describe the solution you'd like**
Add support for [Wireguard VPN](https://www.wireguard.com/) in Zentyal web-interface.

**Describe alternatives you've considered**
OpenVPN, IPSec, Cisco AnyConnect.

**Additional context**
[Installation on Ubuntu](https://www.wireguard.com/install/)
[Quick Start](https://www.wireguard.com/quickstart/)
[Usage](https://www.linode.com/docs/networking/vpn/set-up-wireguard-vpn-on-ubuntu/)
[Protocol and Cryptography](https://www.wireguard.com/protocol/)
[Formal Verification](https://www.wireguard.com/formal-verification/)

**Comment by brunolorente** [comment]
Hi @renne,

First of all, many thanks for your time.
We have evaluated this several times, but we decided to maintain OpenVPN because it's a standard ,very stable and maintained project.

best regards!

**Comment by Neustradamus** [comment]
@brunolorente: Maybe a bug because OpenVPN and WireGuard can work and it is important to have the new solution!

**Comment by anunci89** [comment]
Wireguard its a kernel VPN its generic.
and very simple and transparent.

-> https://github.com/burghardt/easy-wg-quick

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89: Can you change your vision and add this feature?

**Comment by nefta** [comment]
Hello, good evening.
I have installed Wireguard with Pivpn in Zentyal and it works perfectly in Zentyal 7.
But in version 8 Wireguard is active and everything is fine, but the Wireguard pair does not connect to the part of
124 B received (this part hangs), 31.47 KiB sent (only the sending works fine)
Does anyone know what could be the cause of this?
