### ISSUE TITLE
Can't install zentyal-samba on 18.04.4 - libauthen-krb5-easy-perl is not installable

### ISSUE THREAD

**Issue by mrPsycho** [zentyal/zentyal#1946]
**Describe the bug**
After fresh install of ubuntu server 18.04.4 and using https://wiki.zentyal.org/wiki/Installation_Guide#Zentyal_Installer_script it is not possible to install zentyal-samba. 

**To Reproduce**
1. go to ubuntu.com and download http://releases.ubuntu.com/18.04.4/ubuntu-18.04.4-live-server-amd64.iso
2. install server with default settings
3. reboot and login to clean system
4. try to run 
```
curl -s download.zentyal.com/install | sudo sh
sudo apt install zentyal-samba
```
5. see error:
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 zentyal-samba : Depends: libauthen-krb5-easy-perl but it is not installable
E: Unable to correct problems, you have held broken packages.
```
**Expected behavior**
It is installing without any problems. 

**Screenshots**
Same error on UI:
![image](https://user-images.githubusercontent.com/883964/74603947-bdb6b780-50c1-11ea-9084-5431484a5dc9.png)

**Zentyal OS (please complete the following information):**
 - Version: 6.1
 - Version of the module which has the bug: Idk, it is not installing.
 - Modules installed: 
```
zentyal-core/unknown,now 6.1.2 all [installed]
zentyal-software/unknown,now 6.1 all [installed]
```

**Comment by lukaspavelka** [comment]
i can confirm this bug on ubuntu 18.04 with installation of 

> root@vps:~# apt-get install zentyal-samba
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  zentyal-samba : Depends: libauthen-krb5-easy-perl but it is not installable
> E: Unable to correct problems, you have held broken packages.

_______________________________________________

> root@vps:~# apt-get install libauthen-krb5-easy-perl
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> Package libauthen-krb5-easy-perl is not available, but is referred to by another package.
> This may mean that the package is missing, has been obsoleted, or
> is only available from another source
> 
> E: Package 'libauthen-krb5-easy-perl' has no installation candidate

________________________________________________

> 
> root@vps:~# apt-get install -y libauthen-krb5-perl
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> libauthen-krb5-perl is already the newest version (1.9-5build3).
> 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
>

**Comment by Neustradamus** [comment]
Any news?

**Comment by affenrakete** [comment]
You can install it by changing  the source list.

/etc/apt/source.list.d/zentyal-archive.list

from
deb http://packages.zentyal.org/zentyal 6.1 main

to
deb http://packages.zentyal.org/zentyal 6.1 main extra

At least the 'extra' bit was missing in my case.

**Comment by affenrakete** [comment]
The 'Zentyal Installer script' is missing the 'extra' bit too.
But I did not find the file, to make a commit. 

_http://download.zentyal.com/install_

> #!/bin/sh
> 
> VERSION=6.1
> 
> echo "deb http://packages.zentyal.org/zentyal $VERSION main" > /etc/apt/sources.list.d/zentyal-archive.list
> 
> wget -q http://keys.zentyal.org/zentyal-$VERSION-packages.asc -O /etc/apt/trusted.gpg.d/zentyal-packages.asc
> 
> apt update
> 
> apt remove -y netplan.io
> 
> DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends zentyal && echo "
> 
> You can access the Zentyal Web Interface at:
> 
>  * https://<zentyal-ip-address>:8443/
> 
> "

**Comment by brunolorente** [comment]
Hi @mrPyscho,

Many thanks for reporting the issue. The script was updated to use the new Zentyal 6.2
