### ISSUE TITLE
Web-interface PPPoE dialog rejects hashtag in username

### ISSUE THREAD

**Issue by renne** [zentyal/zentyal#1947]
Our ISP uses hashtags in the PPPoE usernames. The Zentyal web-interface rejects hashtags in the PPPoE username. Zentyal ISO-image was 6.1. Since upgrading version is Zentyal 6.1.2

This makes Zentyal unusable with PPPoE uplinks (25 Million = 73% of the german internet sockets are xDSL with PPPoE). ISPs have to rent the last mile of xDSL sockets from Deutsche Telekom GmbH which leads to the username scheme `<user-ID>#<ISP-ID>@bsa-vdsl`

**Comment by brunolorente** [comment]
Hi @renne ,
I'm personally going to investigate about this, but **just for administrative reasons**... could you open a new issue using the feature request template?

**I think this could be a good enhancement**, so, **please use the template** and then I will glad to add it to our roadmap.

Best regards!

**Comment by Neustradamus** [comment]
@renne: Have you found a solution for it?
