### ISSUE TITLE
Ipsec/L2TP VPN don't start after boot or reboot. Commercial 6.1.2 up to date

### ISSUE THREAD

**Issue by attyhu** [zentyal/zentyal#1951]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Zentyal OS (please complete the following information):**
 - Version: [e.g. 5.0, 5.1, 6.0, 6.1]
 - Version of the module which has the bug [e.g. zentyal-dns-5.0.3]
 - Modules installed [e.g. DNS, DC, Jabber]

**Other OS (please complete the following information):**
 - OS: [e.g. Windows 10]
 - Version: [e.g. build 18363]

**Additional context**

**Comment by djoven89** [comment]
Thanks for your report. Based on this, unfortunately there isn’t enough information to confirm if this is a bug or not and to analyse the causes. Please fill in the bug report template with maximum information possible. On the other hand, if you have a valid support subscription, please open a support ticket in the Zentyal Support Portal. If you have lost your login credentials, please contact sales (at) zentyal.com to recover them.
