### ISSUE TITLE
Upgrade strategy

### ISSUE THREAD

**Issue by kmate95** [zentyal/zentyal#1953]
This is actually my new favorite script to completely brick and destroy a Linux installation. I won't even try to salvage it...

Didn't even notice it was running while trying to fix a bug with the Samba module.
It blew past the pinned packages that kept the system running on the testing branch. 
After installing  perl5.30 most of Zentyal was completely bricked, so the `autoremove --purge` cleaned it up nicely. With all the outdated packages purged this way and no longer available from repositories, it's kind of beyond saving.

Most of /etc reset nicely like on a new install. It's kind of random where it removed and where it purged the packages, but no trace of work I've done in the past months were left. (I have etckeeper, but since this beautiful software rewrites half of /etc on every boot, it was not the most useful tool. )  

It actually took me more than 2 hours to notice as it did this silently without asking or showing anything. I didn't even notice it was started. I noticed it when my $EDITOR turned into vim on a new session.

https://github.com/zentyal/zentyal/blob/b7ec4e572d10281cd30c2912ccc55326f74e69a7/main/core/src/scripts/release-upgrade#L167
```
apt-get autoremove --purge -y -o DPkg::Options::="--force-confdef"
dpkg --configure -a --force-confdef
apt-get -f install -y -o DPkg::Options::="--force-confdef"
```

The only thing untouched were the data on the shared HDDs. I suggest a background task to delete a random file or folder every minute from there too.

**Comment by brunolorente** [comment]
Assuming you have hit an issue with your upgrade. In general terms our recommendation is to follow these steps with the upgrades: https://doc.zentyal.org/en/upgrade.html

If you want to report an issue, please follow the bug report template. Best regards.
