### ISSUE TITLE
Unable to create subdomain

### ISSUE THREAD

**Issue by kahootali** [zentyal/zentyal#1954]
**Describe the bug**
I have created a Domain in zentyal `stakater.io` and added its hostnames like `app.test.cluster.stakater.io` and directed it to an IP and it is working fine. 

When i locally run `dig app.test.cluster.stakater.io +short` I am able to get the IP. 

But now I want to have a subdomain like `test.cluster.stakater.io` and add hostnames there as I need it for SRV records. When I add a subdomain `test.cluster.stakater.io` and add a hostname `app2` and add an IP there, I am unable to connect to it.

Now, when I run `dig app2.test.cluster.stakater.io +short`, it doesn't return any IP. 

Zentyal: 6.1

**Comment by brunolorente** [comment]
Hi @kahootali ,

It could be related with https://github.com/zentyal/zentyal/issues/1952 but I'm not sure if I understood you, so... please, could you give us more feedback?

Many thanks for your time!

**Comment by kahootali** [comment]
Actually the issue is I have a domain `stakater.io` in my Zentyal server, and I want to add sub-domains. E.g.One use case is I want to have `*.apps.test.clusters.stakater.io` hostname but it is not allowed to add `*.apps.test.clusters` in `stakater.io` domain, it gives an error, so I tried to add another domain in the domains page of `apps.test.clusters.stakater.io` and add a hostname with `*` entry and add IP address, but I am unable to process it, 
When I run `dig url.apps.test.clusters.stakater.io short+` it is unable to return the IP address. 

This is one use case, I want to add subdomains in main domain in Zentyal

**Comment by Neustradamus** [comment]
@kahootali: Can you test with the last fix and confirm if it is solved or not?

**Comment by kahootali** [comment]
@Neustradamus Sorry didn't get you, what do you mean by last fix? The last I tried it didn't work.

**Comment by Neustradamus** [comment]
@kahootali: Here: https://github.com/zentyal/zentyal/commits/master

**Comment by Neustradamus** [comment]
@kahootali: It is not solved?
Can you confirm?

**Comment by Neustradamus** [comment]
@kahootali: It is not solved?
Can you confirm?

**Comment by kahootali** [comment]
@Neustradamus Sorry, I stopped working on this and this setup is now Paused, so i couldn't test it, can't confirm. You can either close it and if this issue occurs again, i will re-open it

**Comment by brunolorente** [comment]
many thanks thanks for your time @kahootali and @Neustradamus !

**Comment by Neustradamus** [comment]
@brunolorente: Solved?
