### ISSUE TITLE
Errors running "restore-backup" manually.

### ISSUE THREAD

**Issue by Facsimiler** [zentyal/zentyal#1956]
**Describe the bug**
I experienced an error configuring _Zentyal_, and now have a non-working machine (this is not the bug I'm reporting). In particular, networking on the machine is non-operative. I need to restore the previous configuration from a backup file, which I have available. However, when I attempt to run the `restore-backup` command from the command line, I am getting a number of errors.

I have tried running this command as `root`, and as user `ebox`. I get the same errors each time.

**To Reproduce**
1. Gain access to the machine via the console and open a root shell with: `sudo -s -H` (or, alternatively, use `sudo -s -H -u ebox` to get a shell for user `ebox`).
2. Execute the command: `/usr/share/zentyal/restore-backup /var/lib/zentyal/conf/backups/2020-03-06-124456.tar`
3. Refer to error output from this command below.

What I see is the following:

```
Can't locate object method "throw" via package "Can't locate object method "throw" via package "Can't locate object method "throw" via package "read file '/var/lib/zentyal/tmp//backup.yHpCKB/eboxboxup/size' - sysopen: Permission denied at /usr/share/perl5/EBox/Backup.pm line 935.
" (perhaps you forgot to load "read_file '/var/lib/zentyal/tmp//backup.yHpCKB/eboxboxup/size' - sysopen: Permission denied at /usr/share/perl5/EBox/Backup.pm line 935.
"?) at /usr/share/perl5/EBox/Backup.pm line 938.
" (perhaps you forgot to load "Can't locate object method "throw" via package "read_file '/var/lib/zentyal/tmp//backup.yHpCKB/eboxboxup/size' - sysopen: Permission denied at /usr/share/perl5/zentyal/EBox/Backup.pm line 935.
" (perhaps you forgot to load "read_file '/var/lib/zentyal/tmp//backup.yHpCKB/eboxboxup/size' - sysopen: Permission denied at /usr/share/perl5/zentyal/EBox/Backup.pm line 935.
"?) at /usr/share/perl5/EBox/Backup.pm line 938.
"?) at /usr/share/perl5/Ebox/Backup.pm line 1235.
" (perhaps you forgot to load "Can't locate object method "throw" via package "Can't locate object method "throw" via package "read_file '/var/lib/zentyal/tmp//backup.yHpCKB/eboxboxup/size' - sysopen: Permission denied at /usr/share/perl5/zentyal/EBox/Backup.pm line 935.
" (perhaps you forgot to load "read_file '/var/lib/zentyal/tmp//backup.yHpCKB/eboxboxup/size' - sysopen: Permission denied at /usr/share/perl5/EBox/Backup.pm line 935.
"?) at /usr/share/perl5/EBox/Backup.pm line 938.
" (perhaps you forgot to load "Can't locate object method "throw" via package "read_file '/var/lib/zentyal/tmp//backup.yHpCKB/eboxboxup/size' - sysopen: Permission denied at /usr/share/perl5/zentyal/EBox/Backup.pm line 935.
" (perhaps you forgot to load "read_file '/var/lib/zentyal/tmp//backup.yHpCKB/eboxboxup/size' - sysopen: Permission denied at /usr/share/perl5/zentyal/EBox/Backup.pm line 935.
"?) at /usr/share/perl5/EBox/Backup.pm line 938.
"?) at /usr/share/perl5/Ebox/Backup.pm line 1235.
"?) at /usr/share/zentyal/restore-backup line 111.
```

The extracted backup is then deleted, and the restore fails.

This is clearly a nested error, with **throw** appearing to be broken in the _Perl_ scripts. So each failure of an attempt to throw an exception results in another throw failure.

However, the root cause appears to be an inability of the `restore-backup` script to read the `size` file extracted from the archive. I have manually extracted all of the configuration files from the archive, and they are all owned by `ebox:ebox` and all are readable, including `size`.

**Expected behavior**
I expected _Zentyal_ to restore the configuration and restart, resulting in a working system.

**Screenshots**
I'm unable to provide these. I only have console access to the machine in question.

**Zentyal OS (please complete the following information):**
 - Version: 6.1
 - Version of the module which has the bug: Core (I'm guessing) 6.1.2
 - Modules installed: antivirus (6.1.1), ca (6.1), core (6.1.2), dhcp (6.1), dns (6.1.1), firewall (6.1), network (6.1.1), ntp (6.1), openvpn (6.1), radius (6.1), samba (6.1.2), software (6.1), virt (6.1).

**Other OS (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04.4 LTS 64-bit

**Additional context**
Can't think of anything else. I have tried manually editing and unpacking the archive, and everything is fine. It appears the _Perl_ script cannot read any of the files, even though it ought to be able to.

Since networking is down, it has occurred to me that that might be a part of the problem.

I'll keep working at this, but if anyone has any suggestions, I'd appreciate them.

**Comment by brunolorente** [comment]
Hi @Facsimiler ,

We tried to reproduce it but we couldn't. Did you check if your system's packages are right? Concretely, some perl packages as 'libtrycatch-perl'. I personally fix this issue long time ago...

If you wish, you can contact with sales@zentyal.com and send them the configuration backup and we will do some extra tests.

I'm aware to your PR, I'll will implement it coming soon, probably at the same time that we release Zentyal Server 6.2 in a few days...

Best regards, and many many thanks for your time, thanks! :)

**Comment by Facsimiler** [comment]
@brunolorente Thanks for looking into this, Bruno. I was able to get this resolved by backing up key Perl scripts, manually patching them, then replacing the patched scripts with the backups. I've not looked into this too much more. It appeared that the necessary Perl packages were present.

The root cause seemed to be a permission issue, with some files in the backup being owned by `root.root`, instead of by `ebox.ebox`, and then that was being compounded by the inability to throw and catch exceptions.

I'll try to look into this some more when I get the chance.
