### ISSUE TITLE
Error restarting DNS module after restoring 4.2.12 to 6.1.2

### ISSUE THREAD

**Issue by peptoniet** [zentyal/zentyal#1958]
**Describe the bug**
After restoring from 4.2.12 backup over clean 6.1.2, user dns-_hostname_ is not in DnsAdmins group, thus failing dns module restart request.  Also, it appears that user dns-_hostname_ has password expired after restoring.

**To Reproduce**
1. Install clean 6.1.2 system
2. Restore 4.2.12 backup
3. Try to restart dns module
4. GUI shows error restarting module.

**Expected behavior**
After restore, dns-_hostname_ user should be included in DnsAdmins group.

**Zentyal OS (please complete the following information):**
 - Version: 6.1.2
 - Version of the module which has the bug: zentyal-dns-6.1.1
 - Modules installed: Certification Authority, Core, DHCP Server, DNS Server, Domain Controller and File Sharing, Firewall, Mail, NTP Service, Network Configuration, Software Management, VPN, Web Mail

**Other OS (please complete the following information):**
 - OS: Ubuntu 18.04.4

**Additional context**
I solved by issing these commands:
samba-tool user setexpiry dns-_hostname_ --noexpiry
samba-tool group addmembers DnsAdmins dns-_hostname_

**Comment by brunolorente** [comment]
Hi @peptoniet ,

We are aware of this behaviour but we determine that this is a common task for a system administrator when is performing the maintenance of the Zentyal server.

To help system administrators with the maintenance and tasks debugging, we developed a new feature called 'System status report' which provide useful information about the status of the Zentyal server, which includes the users who belong to the DnsAdmin group or the password expiration of the special dns users. 

In the following link you can see more details about this feature:

* https://doc.zentyal.org/en/maintenance.html#smart-admin

Best regards, and many thanks for your time!

**Comment by peptoniet** [comment]
Dear Bruno,
Thank you very much for your explanation.
I could bear that an administrator would have to handle the expiration, altough it is an INTERNAL and ESSENTIAL account for the system to work, so I think is not acceptable to just pass the responsability to others...
On the other side, it is unbearable that an INTERNAL and ESSENTIAL account does not restore to the ESSENTIAL group were it belongs, rendering it useless and bringing down the functionality.
Why would you not accept what is obvious? You have a faulty restore procedure.  Just take the error and correct it.  It takes two lines of code.  We all developers do it all the time...
At the very minimum, you could provide a readable error, and warn about the account not being added to the group were it belongs, because it is essential.
