### ISSUE TITLE
samba status unknow after update zentyal to 6.1.2

### ISSUE THREAD

**Issue by bemark16** [zentyal/zentyal#1961]
we have a domain transferred from a windows AD.
Samba don't run correctly after we update zentyal to 6.1.2
zentyal.log shows:
&#39; at La petición DNS falló: query timed out (usando servidores de nombres , /etc/resolv.conf fue
&#39;# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
# and managed by Zentyal.
#
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
#
&#39; at /usr/share/perl5/EBox/Module/LDAP.pm line 106
EBox::Module::LDAP::_dnsResolve('EBox::Samba=HASH(0x5612e7886040)', 'abraracurcix.garsaco.local') called at /usr/share/perl5/EBox/Module/LDAP.pm line 155
EBox::Module::LDAP::_connectToSchemaMaster('EBox::Samba=HASH(0x5612e7886040)') called at /usr/share/perl5/EBox/Module/LDAP.pm line 275
EBox::Module::LDAP::_loadSchemasFiles('EBox::Samba=HASH(0x5612e7886040)', 'ARRAY(0x5612e851cb60)') called at /usr/share/perl5/EBox/Module/LDAP.pm line 267
EBox::Module::LDAP::_loadSchemas('EBox::Samba=HASH(0x5612e7886040)') called at /usr/share/perl5/EBox/Module/LDAP.pm line 341
EBox::Module::LDAP::_performSetup('EBox::Samba=HASH(0x5612e7886040)') called at /usr/share/perl5/EBox/Samba.pm line 671
EBox::Samba::_regenConfig('EBox::Samba=HASH(0x5612e7886040)') called at /usr/share/perl5/EBox/Module/Base.pm line 234
eval {...} at /usr/share/perl5/EBox/Module/Base.pm line 233
EBox::Module::Base::save('EBox::Samba=HASH(0x5612e7886040)') called at /usr/share/perl5/EBox/GlobalImpl.pm line 648
eval {...} at /usr/share/perl5/EBox/GlobalImpl.pm line 647
EBox::GlobalImpl::saveAllModules('EBox::GlobalImpl=HASH(0x5612e3170e50)', 'progress', 'EBox::ProgressIndicator=HASH(0x5612e66c2bb8)') called at /usr/share/perl5/EBox/Global.pm line 95
EBox::Global::AUTOLOAD('EBox::Global=HASH(0x5612e2755f48)', 'progress', 'EBox::ProgressIndicator=HASH(0x5612e66c2bb8)') called at /usr/share/zentyal/global-action line 32
eval {...} at /usr/share/zentyal/global-action line 30
2020/04/17 16:44:53 ERROR> GlobalImpl.pm:652 EBox::GlobalImpl::saveAllModules - Failed to save changes in module samba: La petición DNS falló: query timed out (usando servidores de nombres
, /etc/resolv.conf fue
&#39;# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
# and managed by Zentyal.
#
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
#
&#39;
2020/04/17 16:44:53 INFO> Base.pm:231 EBox::Module::Base::save - Restarting service for module: logs
2020/04/17 16:44:54 ERROR> GlobalImpl.pm:727 EBox::GlobalImpl::saveAllModules - The following modules failed while saving their changes, their state is unknown: samba  at The following modules failed while saving their changes, their state is unknown: samba  at /usr/share/perl5/EBox/GlobalImpl.pm line 727
EBox::GlobalImpl::saveAllModules('EBox::GlobalImpl=HASH(0x5612e3170e50)', 'progress', 'EBox::ProgressIndicator=HASH(0x5612e66c2bb8)') called at /usr/share/perl5/EBox/Global.pm line 95
EBox::Global::AUTOLOAD('EBox::Global=HASH(0x5612e2755f48)', 'progress', 'EBox::ProgressIndicator=HASH(0x5612e66c2bb8)') called at /usr/share/zentyal/global-action line 32
eval {...} at /usr/share/zentyal/global-action line 30
2020/04/17 16:44:55 INFO> SyncDaemon.pm:340 EBox::Samba::SyncDaemon::run - Samba sync daemon started
2020/04/17 16:45:59 INFO> GlobalImpl.pm:616 EBox::GlobalImpl::saveAllModules - Saving config and restarting services:
2020/04/17 16:45:59 INFO> GlobalImpl.pm:714 EBox::GlobalImpl::saveAllModules - Changes saved successfully

**Comment by brunolorente** [comment]
Hi @bemark16 ,
This is really hard to read, please, use the provided template when you're going to open a new issue. 

I'm going to close this, I'll be pendinng of you to check this on a new "well formed" ticket.

Many thanks!
