### ISSUE TITLE
Can Zentyal Support Master Master Configuration.

### ISSUE THREAD

**Issue by CarBee** [zentyal/zentyal#1965]
Can Zentyal support Master , Master configuration?
When the PDC is down the Secondary cannot be made as a primary one. There are instances where we cannot get a backup of configurations and cannot restore the PDC. Please let us know how we could able to proceed. Or can this be cluster enabled?

**Comment by brunolorente** [comment]
Hi @CarBee ,

Could you please re-create the issue using the provided issue template?

Many thanks for your time!

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89: Have you looked: https://github.com/zentyal/zentyal/issues/1991?
