### ISSUE TITLE
After Upgrade to Zentyal 6.2 antivirus stopped

### ISSUE THREAD

**Issue by husisusi** [zentyal/zentyal#1968]
I just Upgrade from 6.1 to Zentyal 6.2 and everything seems to be working...
I noticed that the Antivirus has stopped and i can not start/restart it:
![grafik](https://user-images.githubusercontent.com/8606735/81498249-19a96a80-92c4-11ea-8db2-3edc48227155.png)
clamav.log:
Sun May 10 13:41:56 2020 -> Client disconnected (FD 10)
Sun May 10 13:42:01 2020 -> Client disconnected (FD 10)
Sun May 10 13:42:07 2020 -> Client disconnected (FD 10)
Sun May 10 13:42:12 2020 -> Client disconnected (FD 10)
Sun May 10 13:42:17 2020 -> Client disconnected (FD 10)

**Comment by brunolorente** [comment]
Hi @husisusi ,

We are already working on this, also I've to advice you: Please, follow the provided template to open new issues.

On the other hand, I'm going to close this because we are working on https://github.com/zentyal/zentyal/issues/1970 take a look if you want.

Thanks for your time!
