### ISSUE TITLE
Backup (commercial) adding /root/ to path using rsync while not configured.

### ISSUE THREAD

**Issue by wirdo89** [zentyal/zentyal#1972]
It seems that in either the last or the one before that zentyal adds /root/ in front of the destination path.

 Attempt 4 failed. BackendException: Error running 'rsync -e 'ssh  -oBatchMode=yes '  **admin@XXXXXXXX:share/MD0_DATA/zentyal/**': returned 23, with output:

 rsync: change_dir "**/root/share/MD0_DATA/zentyal**" failed: No such file or directory (2)
 rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1668) [Receiver=3.1.2]

Above causes zentyal to be unable to backup to a nas (for example a qnap) since the /share folder isn't in /root
Is there a workaround until this is fixed perhaps?

**Version: 6.1.3**

**Comment by djoven89** [comment]
Hi @wirdo89 ,

Please, use the provided template when you're going to open a new issue.

I'm going to close this, I'll be pendinng of you to check this on a new "well formed" ticket.

Best regards, Daniel Joven.
