### ISSUE TITLE
Antivirus 6.2.1 not works properly after update

### ISSUE THREAD

**Issue by sipi58** [zentyal/zentyal#1974]
After closing the #1970 and #1973 bug reports, the Antivirus 6.2.1 update was released but it not works properly. Antivirus not works.

After the update, the clamav-daemon seems to be running
systemctl status clamav-daemon
● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (running) since Thu 2020-06-04 20:49:21 CEST; 15h ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://www.clamav.net/documents/
 Main PID: 20825 (clamd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/clamav-daemon.service
           └─20825 /usr/sbin/clamd --foreground=true

jún 05 02:43:11 srv01 clamd[20825]: Fri Jun  5 02:43:11 2020 -> SelfCheck: Database status OK.

But the web console shows Antivirus module is not running

![Screenshot_20200605_121645](https://user-images.githubusercontent.com/62344094/83867595-f5f20c80-a729-11ea-84f2-b4cf3916203d.png)

And according to the command line, the Antivirus module is not running
sudo zs antivirus status
Zentyal: status module antivirus:                       [ STOPPED ]

If I start the Antivirus module from the command line or on the web console, it will not start.
sudo zs antivirus start
 * Restarting Zentyal module: antivirus                                                                                                [ OK ] 
sudo zs antivirus status
Zentyal: status module antivirus:                       [ STOPPED ]

The clamav daemon will stop and signal an error
systemctl status clamav-daemon
● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (running) since Fri 2020-06-05 12:47:39 CEST; 21s ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://www.clamav.net/documents/
 Main PID: 20363 (clamd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/clamav-daemon.service
           └─20363 /usr/sbin/clamd --foreground=true

jún 05 12:47:54 srv01 clamd[20363]: Fri Jun  5 12:47:54 2020 -> *Client disconnected (FD 10)
jún 05 12:48:00 srv01 clamd[20363]: Fri Jun  5 12:47:59 2020 -> *Client disconnected (FD 10)

And it can't be restarted
systemctl status clamav-daemon
● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (running) since Fri 2020-06-05 12:51:14 CEST; 1s ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://www.clamav.net/documents/
  Process: 23265 ExecStartPre=/bin/chown clamav /run/clamav (code=exited, status=0/SUCCESS)
  Process: 23264 ExecStartPre=/bin/mkdir /run/clamav (code=exited, status=1/FAILURE)
 Main PID: 23266 (clamd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/clamav-daemon.service
           └─23266 /usr/sbin/clamd --foreground=true

jún 05 12:51:14 srv01 systemd[1]: Starting Clam AntiVirus userspace daemon...
jún 05 12:51:14 srv01 mkdir[23264]: /bin/mkdir: cannot create directory ‘/run/clamav’: File exists
jún 05 12:51:14 srv01 systemd[1]: Started Clam AntiVirus userspace daemon.

I need to stop clamav-daemon and need to delete the /run/clamav directory after that I can restart the clamav-daemon.
sudo systemctl start clamav-daemon
systemctl status clamav-daemon
● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (running) since Fri 2020-06-05 12:57:08 CEST; 8s ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://www.clamav.net/documents/
  Process: 27624 ExecStartPre=/bin/chown clamav /run/clamav (code=exited, status=0/SUCCESS)
  Process: 27623 ExecStartPre=/bin/mkdir /run/clamav (code=exited, status=0/SUCCESS)
 Main PID: 27625 (clamd)
    Tasks: 1 (limit: 4915)
   CGroup: /system.slice/clamav-daemon.service
           └─27625 /usr/sbin/clamd --foreground=true

jún 05 12:57:08 srv01 systemd[1]: Starting Clam AntiVirus userspace daemon...
jún 05 12:57:08 srv01 systemd[1]: Started Clam AntiVirus userspace daemon.

But the web console and command line show Antivirus module is still not running.

Zentyal 6.2
Antivirus module 6.2.1

Ubuntu 18.04.4 64 bit

#1970 and 1973 bug not fixed correctly and reports closed too soon. Please fix it as soon as possible.

Thank you for your help.

**Comment by djoven89** [comment]
Hi @sipi58 ,

Zentyal runs this command to determine if the daemon is running:

`
systemctl status 'clamav-daemon' | grep 'Active: active (running)'
`

Please, try to do the following steps:

**1.** Disable the Antivirus module.

**2.** Make sure that the daemon 'clamav-daemon' is stopped and disabled. In case it is not, do it yourself.

```
systemctl stop clamav-daemon
systemctl disable clamav-daemon
```

**3.** After that, enable the module again through the Webadmin.

**4.** Check the status of the module and its daemon.

**5.** Finally, make sure that the ClamAV database is up-to-date.

`freshclam`

Best regards, Daniel Joven.

**Comment by sipi58** [comment]
Hi @djoven89 ,

thank you for your advice, I have implemented the suggested actions but nothing has changed...

The clamav-daemon shows FD10 error...
systemctl status clamav-daemon
● clamav-daemon.service - Clam AntiVirus userspace daemon
   Loaded: loaded (/lib/systemd/system/clamav-daemon.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/clamav-daemon.service.d
           └─extend.conf
   Active: active (running) since Fri 2020-06-05 19:35:55 CEST; 4min 51s ago
     Docs: man:clamd(8)
           man:clamd.conf(5)
           https://www.clamav.net/documents/
 Main PID: 27502 (clamd)
    Tasks: 2 (limit: 4915)
   CGroup: /system.slice/clamav-daemon.service
           └─27502 /usr/sbin/clamd --foreground=true

jún 05 19:39:55 srv01 clamd[27502]: Fri Jun  5 19:39:55 2020 -> *Client disconnected (FD 10)
jún 05 19:40:01 srv01 clamd[27502]: Fri Jun  5 19:40:01 2020 -> *Client disconnected (FD 10)

Virus databeses are up to date and clamav-daemon check show it's running
sudo systemctl status clamav-daemon | grep 'Active: active (running)'
   Active: active (running) since Fri 2020-06-05 19:35:55 CEST; 10min ago

But webadmin shows it is NOT RUNNING. In reality, it really doesn’t run, there is no virus filtering.

What could be the solution?

Thank you for your help.

**Comment by husisusi** [comment]
@sipi58, did you try to uninstall the module restart and install it again?
it works for me.

**Comment by sipi58** [comment]
Hi,

I found strange things... clamav-* default user is clamav by ubuntu package but Zentyal override this to root for run clamav-daemon but clamav-freshclam run by clamav user.

The /run/clamav directory is owned by clamav:root by ubuntu package. The owner can write it  but root group cannot write it. Permission are drwxr-xr-x!

This is because /etc/systemd/system/clamav-daemon.service.d/extend.conf contains the following:
[Service]
ExecStartPre=-/bin/mkdir /run/clamav
ExecStartPre=/bin/chown clamav /run/clamav

This means that it creates the /run/clamav directory each time it starts and assigns the clamav user.

Which user should run the clamav daemon?

Another problem is that the amavis user must be a member of the clamav group to run Mailfilter. Am I correct?

But this is not true! Should I now add the amavis user to the clamav group?

Where and how many differences are there that I did not discover yet?

Can someone help who programmed Zentyal pre and post modifications scripts?

@husisusi , I would have tried but because of the addictions I didn't dare do it ... How can I do this without another problem? This Zentyal is my own live system ...

Thanks to everyone for their help. I hope someone will be able to help ...

**Comment by sipi58** [comment]
Finally, I tried to remove the Antivirus and Mailfilter module using webadmin.
I was confident that this would safely remove the two faulty modules.
Under webadmin Software Management, Zentyal Components, on the Delete tab, I selected the Antivirus and Mailfilter modules and removed them.
I restarted the server and under webadmin Software Management, Zentyal Components on the Install tab I selected the Antivirus and Mailfilter modules and installed them.
Then I enabled the Antivirus and Mailfilter modules under the webadmin Module Status, Module Status Configuration.
I think it works well now, but I'm still testing the Antivirus and Mailfilter modules.

@husisusi , thank you for your advice and help.

**Comment by sipi58** [comment]
I hurried the thing.

While I was trying to test the operation of the Antivirus the webadmin announced that the Antivirus module had stopped.

There is a recurring error in clamav.log:
Sat Jun  6 16:40:25 2020 -> Client disconnected (FD 10)

What's happening? Make hopping mad...

Please help me...

**Comment by sipi58** [comment]
Reinstall...
