### ISSUE TITLE
Text file for latest version of 6.2.0 missing at URL http://update.zentyal.org/last-6.2.txt

### ISSUE THREAD

**Issue by zentyal-scottdr** [zentyal/zentyal#1977]
**Describe the bug**
Due to the above text file not being published, Dashboard displays that a update is available, even though latest version is installed.

**To Reproduce**
1. Go to 'Webadmin Desktop'
2. View  General Information widget and Core version, displays "6.2.0 ( available)

**Expected behavior**
Part of the cron.daily scripts updates the local file /var/lib/zentyal/latestversion from the expected file URL:http://update.zentyal.org/last-6.2.txt. If this file was correct the test in SysInfo.pm at Line 316 would be true.

**Zentyal OS (please complete the following information):**
 - Version: 6.2]
webadmin nginx

**Additional context**
I did report this via forums 3 days ago https://forum.zentyal.org/index.php/topic,34985.0.html
![Zentyal 620 issue](https://user-images.githubusercontent.com/66560644/83971668-6177dd80-a8d4-11ea-9217-26d2984c7bf4.JPG)

**Comment by brunolorente** [comment]
Hi @zentyal-scottdr 
The issue has been fixed, also, a new version of Zentyal core is available.

Many thanks for your time!

**Comment by zentyal-scottdr** [comment]
👍

________________________________

**Comment by rortega2-github** [comment]
I wanted to comment, in order to see 6.2.1 I had to do:
as root echo 6.2.1 > /var/lib/zentyal/latestversion
