### ISSUE TITLE
zentyal-core issue after libssl install

### ISSUE THREAD

**Issue by rubenszolt** [zentyal/zentyal#1978]
**Describe the bug**
zentyal-core issue after libssl install

**To Reproduce**
1. Update all packages
2. but after libssl package update it receive the next error: 
See error: 
dpkg: cycle found while processing triggers:
 chain of packages whose triggers are or may be responsible:
  zentyal-core -> zentyal-core -> zentyal-core
 packages' pending triggers which are or may be unresolvable:
  zentyal-core: /usr/lib/ssl
dpkg: error processing package zentyal-core (--configure):
 triggers looping, abandoned
Errors were encountered while processing:
 zentyal-core
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Zentyal OS (please complete the following information):**
 - Version: [6.0, 6.1 6.2]
 - Version of the module which has the bug [zentyal-core]
 - Modules installed [Network,Firewall,Antivirus,Certification Authority,DNS,Logs,NTP,VPN,Domain Controller and File Sharing, RADIUS]

**Comment by djoven89** [comment]
Hi @rubenszolt ,

Unfortunately, sometimes the packages aren't installed properly when the server is updated, and it requires to fix those broken packages manually (like your case). You just need to run the following command:

```
sudo dpkg --configure -a
```

**NOTE:** Depending of the number of broken packages, the above command needs to be executed more than once.

Best regards, Daniel Joven.

**Comment by rubenszolt** [comment]
Thanks Daniel, I know how I can resolve, not this is the question, And it is very interesting that you cannot reporoduce this issue,  because on my all (10) servers aparead on all 5 és 6 versions. The problem is the zentyal-core, because of this libssl it cannot configuring, and is broken. On zentyal forum anothers it have the same issue please investigate because it is very easy to close.
