### ISSUE TITLE
Zentyal not updating reverse lookup Zone

### ISSUE THREAD

**Issue by seederp2p** [zentyal/zentyal#1980]
On your Windows domain machine do on a CMD ipconfig /registerdns.

A Record will be updated correctly.

Reverse record will NOT.

In my example my workstation is 192.168.21.41 / 24
however in the syslog it shows up this:

client @0x7f2754100c10 192.168.21.41#50367: updating zone '168.192.in-addr.arpa/IN': update failed: not authoritative for update zone (NOTAUTH)

The correct zone should be 21.168.192.in-addr.arpa I believe.
By the way, my DC's are in different networks than my workstations.

The zone 21.168.192.in-addr.arpa exists. It was created via samba-tool and I also tried via RSAT. Same results.

Thanks!

**Comment by Neustradamus** [comment]
@seederp2p: It has been solved?
