### ISSUE TITLE
DHCP dual efi and non-efi architecture PXE boot

### ISSUE THREAD

**Issue by vesb** [zentyal/zentyal#1983]
Recently I was trying to setup a home PXEBoot server via Zentyal and found that you can only use a single `filename` in `DHCP->Advanced options->Thin Client->File path`. Due to the fact that I have both old non-efi and new efi machines I had to modify `/usr/share/zentyal/stubs/dhcp/subnet.mas` to append `.efi` to `filename` when architecture of dhcp client is efi one (`if option architecture = 00:07`)

The question is - do you want this `feature` so I would open a PR or not? :)

P.S. Thank you for your work and time - I really love Zentyal and I use it for the home network since years!

**Comment by djoven89** [comment]
Hi @vesb ,

It sounds great. You can either create a PR or just explain us how you configured the DHCP stub, then, we will analyze the changes and we will add it to the roadmap.

Thank you for contributing!

Best regards, Daniel Joven.

**Comment by HikariKnight** [comment]
I made a .mas for this exact thing earlier this year that i have been testing out with good success on my FOG server that provides the PXE images, you are all free to use it and integrate it into the codebase as i have no idea how to integrate it into the frontend itself so my pxeboot.mas currently has the bios/legacy bootfile hardcoded and the efi bootfile be the one set by the frontend.
https://gist.github.com/HikariKnight/c2ffeef1d656dfbaf8dc610a55aa6143

**Comment by vesb** [comment]
Hello! :)

I know it is pretty late but here is the change explained:
- code:
```
### /usr/share/zentyal/stubs/dhcp/subment.mas
...

% if ($options{filename}) {
        if option architecture = 00:07 {
            filename    "<% $options{filename} %>.efi";
        } else {
            filename    "<% $options{filename} %>";
        }
% }
% }
</%def>

### EOF
```
- story:
just added the inner `if option architecture = 00:07` so I could reuse WEB UI's filename but appending `.efi` to it. This way, when an EFI machine requests pxeboot filename, Zentyal will detect it via `architecture = 00:07` check and serve EFI compatible file, otherwise for non-EFI machine it will serve the WEB UI's filename as is.

Thank you! :)

**Comment by Neustradamus** [comment]
@vesb: It has been solved in Zentyal?
If not the ticket needs to be open.
