### ISSUE TITLE
Unable to install Zentyal Squid

### ISSUE THREAD

**Issue by vahursuvi** [zentyal/zentyal#1988]
**Describe the bug**
Hi
Its impossible to install Zentyal Squid. I have same problem with two machines - so I am filling this bug report. Installing zentyal-squid ends with error:
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up zentyal-squid (6.2.0) ...
Can't use an undefined value as an ARRAY reference at /usr/share/perl5/EBox/Module/Base.pm line 285.
dpkg: error processing package zentyal-squid (--configure):
 installed zentyal-squid package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 zentyal-squid
E: Sub-process /usr/bin/dpkg returned an error code (1)

The same problem was described here also:
https://forum.zentyal.org/index.php?topic=34811.0
I was able to install zentyal-squid with fallowing commands (this is direct copy from forum - I changed my squid versions)
sudo  /usr/share/zentyal/initial-setup --no-restart squid 6.1.1
sudo zs squid restart || true
sudo dpkg-trigger --no-await zentyal-core

**To Reproduce**
Try to install zentyal-squid module.

**Comment by djoven89** [comment]
Hi @vahursuvi  ,

I couldn't reproduce this issue. I installed the Proxy module in two different environments and in both cases, the module was installed correctly. Below you have the two environments that I configured to tried to reproduce this issue:

**1.** In a very basic environment with only the '**Network**' and '**Firewall**' modules installed and configured.

**2.** In an advance environment which was configured as Mail server.

Could you please provide more information about your Zentyal server and its configuration?

Finally, did you check if your Zentyal server was up-to-date? did you check if you had any broken package? did you analyze the log files (apt/, syslog, zentyal/zentyal.log, dpkg.log, zentyal/software.log)?

Best regards, Daniel Joven.

**Comment by JamesUsmar** [comment]
I have this issue too and it does happen rebuild after rebuild using the Zentyal Package install process. Any ideas?
