### ISSUE TITLE
Can't access shared folder without mapping

### ISSUE THREAD

**Issue by Zyzto** [zentyal/zentyal#1992]
**Describe the bug**
I can't access the shared folder without mapping in it first to the device on Windows 10/7

**To Reproduce**
1.enable sharing
2.make one shared folder
3.acl give access
4.on windows in windows explorer file manager type //zentyal.domain/sharename

**Expected behavior**
To be able to access without mapping the drive first

**Zentyal OS (please complete the following information):**
 - Version: 6.2

**Other OS (please complete the following information):**
 - OS: windows 10 / 7

**Comment by djoven89** [comment]
Hi @Zyzto ,

I have tried to reproduce your issue in a clean Windows 7 and everything worked as expected. I tried with a Windows 7 joined to the Domain Controller and other Windows 7 machine which doesn't belong to the Domain Controller, and both cases worked correctly.

Which error/message do you get?

Finally, I suppose it is a typo but the path should be '**\\\zentyal.domain\sharename**'

Best regards, Daniel Joven.

**Comment by Zyzto** [comment]
@djoven89 

the issue was I couldn't access it through direct path, and I think yes I made typo :D.

I tried it on both win10/7. maybe it's my local setup.
I didn't think of trying one outside the domain but it works from outside. if Input `\\<domainIP>\<sharename>`.
so I did it with ip cause it's not on the same dns.

so I thought why not use the IP even tho it resolves domain name, and guess what it worked for some reason.


![image](https://user-images.githubusercontent.com/13531154/96863549-b6755400-146f-11eb-84fe-998ee82dcb08.png)

![image](https://user-images.githubusercontent.com/13531154/96863376-76ae6c80-146f-11eb-9dc3-5073d02012bf.png)

**Comment by djoven89** [comment]
Hi @Zyzto ,

Instead of use the domain name, could you please try with the FQDN of the server? Something like: `\\zentyal.somedomain.lan\\test`.

Best regards, Daniel Joven.

**Comment by Zyzto** [comment]
> Hi @Zyzto ,
> 
> Instead of use the domain name, could you please try with the FQDN of the server? Something like: `\\zentyal.somedomain.lan\\test`.
> 
> Best regards, Daniel Joven.

it worked, this is the solution. I tried also `\\zentyal\test` alone and it worked
