### ISSUE TITLE
Configuration report date is 1970-01-01 01:00:00

### ISSUE THREAD

**Issue by ProBackup-nl** [zentyal/zentyal#1994]
**Describe the bug**
Configuration report date is set to `1970-01-01 01:00:00`. 

**To Reproduce**
1. Go to 'System'
2. Click on 'Configuration backup'
3. Scroll down to 'Configuration Report'
4. Click on 'Generate and download report file'
5. Extract the downloaded file
6. Have a look at file `eboxbackup\date` (19 bytes)

**Expected behavior**
The real backup date is expected, like:
```
$ date
ma 12 okt 2020 18:26:31 CEST
```
**Zentyal OS:**
 - Version: 6.2
 - Version of the module which has the bug: 6.2.0
 - Modules installed: sysinfo network firewall antivirus audit dns global logs mail mailfilter ntp samba software sogo webadmin

**Comment by Neustradamus** [comment]
@ProBackup-nl, @brunolorente, @djoven89: Please look the PR: #2004.
Thanks to @flopezgr.

**Comment by brunolorente** [comment]
Hi @ProBackup-nl,

The format is correct, the PR #2004 fix the issue.

On the other hand, the issue format you followed is OK, you just need to "follow" the issue template.

Many thanks for your time!
