### ISSUE TITLE
Documentation: reference to Appendix A: returns page without content

### ISSUE THREAD

**Issue by ProBackup-nl** [zentyal/zentyal#1995]
**Describe the bug**
Documentation https://doc.zentyal.org/en/appendix-c.html#id6 refers to "Appendix A: Test environment with VirtualBox" which links to the empty page https://doc.zentyal.org/en/appendix-a.html#virtualbox-ref

**To Reproduce**
1. Go to 'https://doc.zentyal.org/en/appendix-c.html#id6'
2. Click on 'Appendix A: Test environment with VirtualBox'
3. See that the result is a page without content

**Expected behavior**
I expected a documentation page about a Virtualbox development system installation.

**Screenshots**
![Appendix A_ Test environment with VirtualBox — Zentyal 6 2 Documentation](https://user-images.githubusercontent.com/515451/95888017-da0a1180-0d80-11eb-9c0c-06b5bf6883da.png)

**Comment by djoven89** [comment]
Hi @ProBackup-nl ,

Thank you for reporting the issue, we have confirmed it and added it to the roadmap.

Best regards, Daniel.

**Comment by djoven89** [comment]
The behavior was fixed in the latest documentation.

Thank you @ProBackup-nl for your feedback.

Best regards, Daniel Joven.
