### ISSUE TITLE
Zero Logon Vulnreability

### ISSUE THREAD

**Issue by ethanjosephscott** [zentyal/zentyal#1997]
Hey Gang.

I have applied the Zero Logon Vulnerability patch to my own servers, but I was wondering if the Zentyal team could put these changes into play as well.  I have included a link that covers the affected versions, and config fixes for Zentyal's version of samba.

Thank You

https://access.redhat.com/articles/5435971

**Comment by djoven89** [comment]
Hi @ethanjosephscott ,

Thank you for reporting this Vulnerability.

Developers Team have informed us that they already knew about this CVE, however developers team considered that this is a system administrator task. The recommended solution by Samba team could cause some issues in certain environments. Also, the CVE can be fixed applying a certain setting.

Thank you again for your contribution.

Best regards, Daniel Joven.
