### ISSUE TITLE
Dashboard Widgets are gone and can not be restored

### ISSUE THREAD

**Issue by chapderprinz** [zentyal/zentyal#1998]
After update to Zentyal Version 6.1 last year i missed all the dashboard widgets. Update to Zentyal 6.2 does not change anything.

Behavior:
- click on widget configuration
- click on system information
- drag a widget, module status for example, to the dashboard
- widget opens until i release the mouse button. When i release the mouse buttton the dashboard is still empty

So i can't position any widget on the dashoard, no matter which browser i use (Firefox / MS Edge..)
You can watch the behavior in the attached gif file..

![Zentyal_Widgets](https://user-images.githubusercontent.com/73845920/97898012-924f2800-1d37-11eb-88bc-f6bf1611b848.gif)

System: 
Zentyal 6.2 Core 6.2.4
Client: Windows 10 / Ubuntu 18
Broser: Firefox 82.0.2 / Microsoft Edge

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89: Have you progressed on this issue?

**Comment by djoven89** [comment]
Hi @chapderprinz ,

Which messages do you get in the log file '**/var/log/zentyal/zentyal.log**' when you try to add the widgets?

Best regards, Daniel Joven.

**Comment by chapderprinz** [comment]
Hi Daniel,

Trying to add widgets to the dashboard does **not** generate any entry in the log file /var/log/zentyal/zentyal.log

The only files, which are changed while trying to add widgets, are the access.log and the uwsgi.log. You will find those files with the last entryies (login -> try to add widgets -> logout) in the attachment.

[access.log](https://github.com/zentyal/zentyal/files/5735043/access.log)

[uwsgi.log](https://github.com/zentyal/zentyal/files/5735042/uwsgi.log)

Regards, Charles

**Comment by djoven89** [comment]
Hi @chapderprinz ,

After some tests I could reproduce the bug. We have added it to the roadmap.

Thank you for reporting the bug.

Best regards, Daniel Joven.

**Comment by chapderprinz** [comment]
Hi Daniel,

do you like to change status to roadmap ?

Thx
Charles

**Comment by Neustradamus** [comment]
@djoven89: Any news?

**Comment by chapderprinz** [comment]
Hi Bruno,

i just took over the changes from Fix #1998 into the dashboard.js file of my 6.2 installation. Everything works fine.

Thanks a lot !

Greets from the Baltic Sea
Charles

**Comment by Neustradamus** [comment]
@chapderprinz: Where is the fix?

**Comment by chapderprinz** [comment]
@Neustradamus 
just click on the word "Fix" in the last post of brunotalente or you will find it here:
https://github.com/zentyal/zentyal/commit/05024637da8b3b099aa4b609865d7be45270eea2

Charles

**Comment by sradas** [comment]
Changing dashboard.js didn't make possible to return widgets, but when I login from Edge as oppose to FF, I could drag&drop widgets again.
