### ISSUE TITLE
Export users/groups from Zentyal 5.0

### ISSUE THREAD

**Issue by RomyxBaps** [zentyal/zentyal#2007]
Hello everyone,

I need to export all the users/groups from a Zentyal Server in 5.0 Version. 
I need at least Username, Name, LastName, Password (encrypted ?), Groups.

Is it possible to have a tool to do that ? I tried a lot of things but none really works.
The best was pdbedit but when i import the file, i have an error saying : 
`build_sam_account: smbpasswd database is corrupt!  username uer with uid 65 is not in unix passwd database!`

**Comment by RomyxBaps** [comment]
I saw there are some script but for v6 and i'm on the v5. 
Is there scripts for this version to export user without password will be still great.

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89: Can you help @RomyxBaps?

I think that the goal is to export data and import after in a new version...

**Comment by RomyxBaps** [comment]
Hello @Neustradamus yes it one of the reasons.
Have a backup specillay for the users/groups is another.

**Comment by djoven89** [comment]
Hi @RomyxBaps ,

You can use the scripts from Zentyal 6 to export all the domain users and groups, however, sorry to inform you that the passwords are not exported.
If you want to use the scripts, [here](https://raw.githubusercontent.com/zentyal/zentyal/master/main/samba/src/scripts/groups-export.pl) you have the link to the script for domain groups, and [here](https://raw.githubusercontent.com/zentyal/zentyal/master/main/samba/src/scripts/users-export.pl) for domain users, just please, read [here](https://doc.zentyal.org/en/directory.html#limitations-on-import-and-export) the limitation of the scripts.

Best regards, Daniel Joven.

**Comment by RomyxBaps** [comment]
Hi,
Okay, i will try. Thank you for the help :).
