### ISSUE TITLE
Recent change to nginx.conf.mas breaks webadmin

### ISSUE THREAD

**Issue by maarten256** [zentyal/zentyal#2012]
**Describe the bug**
In zentyal-core 6.2.5, a change was delivered to main/core/stubs/nginx.conf.mas. This caused webadmin to stop working with a certificate error:

nginx[4584]: nginx: [emerg] SSL_CTX_use_PrivateKey_file("/var/lib/zentyal/conf/ssl/ssl.key") failed (SSL: error:0B080074:x509 certificate routines:X509_check_private_key:key values mismatch)

I manually changed nginx.conf.mas from:

        ssl_certificate /var/lib/zentyal/conf/ssl/ssl.pem;
        ssl_certificate_key /var/lib/zentyal/conf/ssl/ssl.key;

to:

        ssl_certificate /var/lib/zentyal/conf/ssl/ssl.pem;
        ssl_certificate_key /var/lib/zentyal/conf/ssl/ssl.pem;

and webadmin started working again.

**To Reproduce**
1. Upgrade zentyal-core to 6.2.5
2. Observe that webadmin no longer runs

**Expected behavior**
The webadmin module continues to work after upgrade.
 
**Screenshots**
N/A

**Zentyal OS (please complete the following information):**
 - Version: 6.2.5
 - Version of the module which has the bug zentyal-core 6.2.5
 - Modules installed DNS, DHCP, Firewall, CA, VPN

**Other OS (please complete the following information):**
 - OS: Ubuntu
 - Version: Ubuntu 18.04.5

**Additional context**
Same/similar issue is discussed on the forum:

https://forum.zentyal.org/index.php/topic,35112.0.html

**Comment by Neustradamus** [comment]
@maarten256, @brunolorente, @djoven89: It is linked to:
- https://github.com/zentyal/zentyal/blob/master/main/core/stubs/nginx.conf.mas#L115

And there are:
- https://github.com/zentyal/zentyal/blob/master/main/virt/src/scripts/certconf#L5
- https://github.com/zentyal/zentyal/blob/master/main/virt/src/scripts/certconf#L10

**Comment by maarten256** [comment]
Looks like nginx.conf.mas was modified in this commit:

https://github.com/zentyal/zentyal/commit/59f8f4e2fa92b726205ef0c479ae8da5db032c70

Which appears to be related to a problem in zentyal-virt (which I do not have installed). Perhaps the changes in this commit only work if one has the zentyal-virt component installed?

**Comment by brunolorente** [comment]
Hi @maarten256, 

At the moment we couldn't reproduce the issue, could you please give us more feedback? I would appreciate info about CA module status and setup and the same for the Virt module.

**Comment by Neustradamus** [comment]
@brunolorente: If you remove ssl/ssl.key, it is normal that ssl/ssl.key code does not work.
- https://github.com/zentyal/zentyal/issues/2012#issuecomment-753557508

**Comment by maarten256** [comment]
Here is a listing of what I currently have installed on my server:

```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                     Version                   Architecture              Description
+++-========================================-=========================-=========================-=====================================================================================
ii  zentyal                                  6.2.0ubuntu1              all                       Zentyal - Core metapackage
ii  zentyal-ca                               6.2.1                     all                       Zentyal - Certification Authority
ii  zentyal-common                           5.0.12                    all                       transitional dummy package
ii  zentyal-core                             6.2.5                     all                       Zentyal - Core
ii  zentyal-dhcp                             6.2.1                     all                       Zentyal - DHCP Server
ii  zentyal-dns                              6.2.0                     all                       Zentyal - DNS Server
ii  zentyal-firewall                         6.2.0                     all                       Zentyal - Firewall
ii  zentyal-network                          6.2.0                     all                       Zentyal - Network Configuration
ii  zentyal-ntp                              6.2.0                     all                       Zentyal - NTP Service
ii  zentyal-objects                          5.0.10                    all                       transitional dummy package
ii  zentyal-openvpn                          6.2.0                     all                       Zentyal - VPN
ii  zentyal-services                         5.0.10                    all                       transitional dummy package
ii  zentyal-software                         6.2.0                     all                       Zentyal - Software Management
```
I do not have the virtualization manager installed. My CA is running with self-signed certificates.

When zentyal-core was updated to 6.2.5, I got the change to nginx.conf.mas, which appears to have broken my installation. I'd expect that running with the virtualization manager might prevent the issue from cropping up.

**Comment by chapderprinz** [comment]
Hi all,

i can confirm the behavior like described by maarten256 in the first post. After updating the server this morning webadmin stops working. After I manually changed nginx.conf.mas line 115 (ssl.key to ssl.pem) and restart the webadmin module everything works fine.

There is no error entry in var/log/zentyal.log but the var/log/nginx/error.log shows the key value mismatch: 

[error.log](https://github.com/zentyal/zentyal/files/5774967/error.log)

Best regards
Charles

**Comment by gabrieletassoni** [comment]
I can confirm that changing that .mas file works as a workaround.
I read in a comment the mention to the zentyal virt package can prevent this behavior, I have it installed and after today's update, the problem arose, so, having the virt package installed or not changes nothing to the reproducibility of the bug.

Best regards,
Gabriele

**Comment by Foosec** [comment]
I can confirm aswell.
Altho my problem arose after i changed services certificate common name.

The edit fixes the issue.

**Comment by brunolorente** [comment]
Tomorrow we'll probably release new versions both virt and core fixing this.

**Comment by Neustradamus** [comment]
@brunolorente: There was a problem in 2018:
- https://github.com/zentyal/zentyal/commit/1eb244f9292cb3d64a67807ddbffb625132bf7fe#diff-f262dc15fd6a8e87e45bc45dfea44a2528ae976717786ca316dd9d6c115ab7e1

**Comment by djoven89** [comment]
Hi,

The packages '**zentyal-core**' and '**zentyal-virt**' have been released. The bug is fixed, just remember, restart the 'webadmin' module after upgrade the package 'zentyal-core' in case the issue persists, below you have the necessary commands:

```
## To confirm that the certificate ends with 'pem' instead of 'key'
sudo grep ssl_certificate_key /var/lib/zentyal/conf/nginx.conf

## In case the change wasn't applied to the running service
sudo zs webadmin restart
```

Best regards, Daniel Joven.

**Comment by maarten256** [comment]
My server is up and running on zentyal-core 6.2.6 and webadmin is working out of the box so I consider this issue resolved.
