### ISSUE TITLE
Support for Ubuntu Server 20.04

### ISSUE THREAD

**Issue by JuanDCG** [zentyal/zentyal#2016]
**Is your feature request related to a problem? Please describe.**
My problem is while install zentyal from sources on ubuntu server 20.04

**Describe the solution you'd like**
I would like work with zentyal and ubuntu 20.04

**My Steps**
echo "deb http://packages.zentyal.org/zentyal 6.2 main extra" >> /etc/apt/sources.list

wget -q http://keys.zentyal.org/zentyal-6.2-packages.asc -O- | sudo apt-key add -

sudo apt-get update && sudo apt-get install zentyal

**Additional context**
` sudo dpkg --configure -a
Setting up zentyal-core (6.2.5) ...
Can't locate object method "setPort" via package "EBox::WebAdmin" at -e line 9.
Connection DB Error: Access denied for user 'zentyal'@'localhost' (using password: YES)
dpkg: error processing package zentyal-core (--configure):
 installed zentyal-core package post-installation script subprocess returned error exit status 255
dpkg: dependency problems prevent configuration of zentyal-software:
 zentyal-software depends on zentyal-core (>= 6.2.0); however:
  Package zentyal-core is not configured yet.
 zentyal-software depends on zentyal-core (<< 7.0.0); however:
  Package zentyal-core is not configured yet.

dpkg: error processing package zentyal-software (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of zentyal:
 zentyal depends on zentyal-core; however:
  Package zentyal-core is not configured yet.
 zentyal depends on zentyal-software; however:
  Package zentyal-software is not configured yet.

dpkg: error processing package zentyal (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 zentyal-core
 zentyal-software
 zentyal`

**Comment by Neustradamus** [comment]
@JuanDCG: There will be a 7.0 Zentyal based on Ubuntu 20.04 :)
Please look branches:
- https://github.com/zentyal/zentyal/branches
- https://github.com/zentyal/zentyal/commits/feature/ubuntu20

I have requested some updates in more:
- https://github.com/zentyal/zentyal/issues/2014
- https://github.com/zentyal/zentyal/issues/2009

And always the missing Let's Encrypt part:
- https://github.com/zentyal/zentyal/issues/2015

**Comment by djoven89** [comment]
Hi @JuanDCG ,

Each major version of Zentyal is based on a specific Ubuntu version, for example:

* Zentyal 7.x -> Ubuntu 20.04
* Zentyal 6.x -> Ubuntu 18.04
* Zentyal 5.x -> Ubuntu 16.04

So, if you want to use the latest version of Ubuntu with Zentyal, you will need to use Zentyal 7.0, which in this moment, it is a beta version.

You can download Zentyal 7.0 from [here](http://download.zentyal.com/.beta/) or if you want to add its repository in your current Ubuntu 20.04, you just need to adjust the version '**7.0**' instead of '**6.2**' in your first two steps.

Best regards, Daniel Joven.

**Comment by JuanDCG** [comment]
I've been changed that two steps to 7.0 and the output is that:

`Setting up zentyal-core (7.0.0) ...
Can't locate object method "setPort" via package "EBox::WebAdmin" at -e line 9.
Connection DB Error: Access denied for user 'zentyal'@'localhost' (using password: YES)
dpkg: error processing package zentyal-core (--configure):
 installed zentyal-core package post-installation script subprocess returned error exit status 255
dpkg: dependency problems prevent configuration of zentyal-software:
 zentyal-software depends on zentyal-core (>= 7.0.0); however:
  Package zentyal-core is not configured yet.
 zentyal-software depends on zentyal-core (<< 7.1.0); however:
  Package zentyal-core is not configured yet.

dpkg: error processing package zentyal-software (--configure):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of zentyal:
 zentyal depends on zentyal-core; however:
  Package zentyal-core is not configured yet.
 zentyal depends on zentyal-software; however:
  Package zentyal-software is not configured yet.

dpkg: error processing package zentyal (--configure):
 dependency problems - leaving unconfigured
No apport report written because the error message indicates its a followup error from a previous failure.
         No apport report written because the error message indicates its a followup error from a previous failure.
                  Processing triggers for libc-bin (2.31-0ubuntu9.1) ...
Processing triggers for systemd (245.4-4ubuntu3.3) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for install-info (6.7.0.dfsg.2-5) ...
Errors were encountered while processing:
 zentyal-core
 zentyal-software
 zentyal
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by JuanDCG** [comment]
@djoven89 ping

**Comment by Neustradamus** [comment]
@brunolorente, @djoven89: Please read @JuanDCG comments.

**Comment by gahatyari** [comment]
> Hi @JuanDCG ,
> 
> Each major version of Zentyal is based on a specific Ubuntu version, for example:
> 
> * Zentyal 7.x -> Ubuntu 20.04
> * Zentyal 6.x -> Ubuntu 18.04
> * Zentyal 5.x -> Ubuntu 16.04
> 
> So, if you want to use the latest version of Ubuntu with Zentyal, you will need to use Zentyal 7.0, which in this moment, it is a beta version.
> 
> You can download Zentyal 7.0 from [here](http://download.zentyal.com/.beta/) or if you want to add its repository in your current Ubuntu 20.04, you just need to adjust the version '**7.0**' instead of '**6.2**' in your first two steps.
> 
> Best regards, Daniel Joven.


even after making the changed its giving same error..
didn't work....

**Comment by Neustradamus** [comment]
Maybe good to create a new ticket?
