### ISSUE TITLE
Dashboard reports CORE version update available when it is current.

### ISSUE THREAD

**Issue by rortega2-github** [zentyal/zentyal#2017]
**Describe the bug**
In Dashboard > General Information > Core Version, it reports "available" even if CORE is current.

**To Reproduce**
1. After upgrading CORE version, Go to Dashboard > General Information > Core Version, it reports "available" even if CORE is current.

**Expected behavior**
In Dashboard > General Information > Core Version, it should only list the installed CORE version and not mention update is available.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/65912418/104766505-90ceb280-571f-11eb-9400-0e4b3e4fc389.JPG)

**Zentyal OS (please complete the following information):**
 - Version: 6.2.6 (upgraded from 6.2.5)
 - Version of the module which has the bug: CORE?
 - Modules installed: Network, Firewall, DHCP, DNS, Logs, VPN

**Other OS (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04.5 LTS

**Additional context**
Updating /var/lib/zentyal/latestversion with any content, I usually list the version (ie 6.2.6) will make the "available" go away.  It appears that after upgrade the file is cleared (file is there, just without any content).

**Comment by djoven89** [comment]
Hi @rortega2-github ,

Thank you for reporting this behaviour. We have updated the content of the link '**http://update.zentyal.org/last-6.2.txt**'. 

As an additional information, there is a cronjob located at '**/etc/cron.daily/zentyal**' which download the content of the above link and stores it in '**/var/lib/zentyal/latestversion**'.

Best regards, Daniel Joven.
