### ISSUE TITLE
Zentyal 4.2 Samba started failed, LDAP bind error

### ISSUE THREAD

**Issue by ronz03130815** [zentyal/zentyal#2022]
chown 'ebox:ebox' '/var/lib/zentyal/conf/samba.keytab'
chmod 400 '/var/lib/zentyal/conf/samba.keytab'
2021/01/26 05:12:54 DEBUG> Sudo.pm:189 EBox::Sudo::_root - /usr/share/perl5/EBox/Samba/SetUidGidNumbers.pm (pid: 5663) - /sbin/status 'ebox.redis'
2021/01/26 05:12:54 ERROR> LDAP.pm:196 EBox::Module::LDAP::_connectToSchemaMaster - Error binding to schama master LDAP: The wrong password was supplied or the SASL credentials could not be processed
 at Error binding to schama master LDAP: The wrong password was supplied or the SASL credentials could not be processed
 at /usr/share/perl5/EBox/Module/LDAP.pm line 196
EBox::Module::LDAP::_connectToSchemaMaster('EBox::Samba=HASH(0x6173a50)') called at /usr/share/perl5/EBox/Module/LDAP.pm line 275
EBox::Module::LDAP::_loadSchemasFiles('EBox::Samba=HASH(0x6173a50)', 'ARRAY(0x4dcc808)') called at /usr/share/perl5/EBox/Module/LDAP.pm line 267
EBox::Module::LDAP::_loadSchemas('EBox::Samba=HASH(0x6173a50)') called at /usr/share/perl5/EBox/Module/LDAP.pm line 341
EBox::Module::LDAP::_performSetup('EBox::Samba=HASH(0x6173a50)') called at /usr/share/perl5/EBox/Samba.pm line 689
EBox::Samba::_regenConfig('EBox::Samba=HASH(0x6173a50)', 'restart', 1, 'restartModules', 1) called at /usr/share/perl5/EBox/Module/Service.pm line 999
eval {...} at /usr/share/perl5/EBox/Module/Service.pm line 998
EBox::Module::Service::restartService('EBox::Samba=HASH(0x6173a50)', 'restartModules', 1) called at /usr/share/perl5/EBox/Util/Init.pm line 127
eval {...} at /usr/share/perl5/EBox/Util/Init.pm line 125
EBox::Util::Init::moduleAction('samba', 'restartService', 'start') called at /usr/share/perl5/EBox/Util/Init.pm line 87
EBox::Util::Init::start at /etc/rc2.d/S20zentyal line 35
main::main at /etc/rc2.d/S20zentyal line 80
2021/01/26 05:12:54 ERROR> Service.pm:1001 EBox::Module::Service::restartService - Error restarting service: Error binding to schama master LDAP: The wrong password was supplied or the SASL credentials could not be processed
2021/01/26 05:12:54 ERROR> Service.pm:1003 EBox::Module::Service::restartService - Error binding to schama master LDAP: The wrong password was supplied or the SASL credentials could not be processed
 at Error binding to schama master LDAP: The wrong password was supplied or the SASL credentials could not be processed
 at /usr/share/perl5/EBox/Module/Service.pm line 1003
EBox::Module::Service::restartService('EBox::Samba=HASH(0x6173a50)', 'restartModules', 1) called at /usr/share/perl5/EBox/Util/Init.pm line 127
eval {...} at /usr/share/perl5/EBox/Util/Init.pm line 125
EBox::Util::Init::moduleAction('samba', 'restartService', 'start') called at /usr/share/perl5/EBox/Util/Init.pm line 87
EBox::Util::Init::start at /etc/rc2.d/S20zentyal line 35
main::main at /etc/rc2.d/S20zentyal line 80

any ideas?

**Comment by mrPsycho** [comment]
i still have same issues, reported it on forum and gh. 

but still not solved, cause not so critical.

**Comment by ronz03130815** [comment]
I used to type this fixed:
_sudo samba-tool domain passwordsettings set --max-pwd-age=0
sudo samba-tool user setpassword Administrator_
then change Administrator password via Zentyal user module (same password above)
then 
_sudo reboot_
but not work for now

**Comment by djoven89** [comment]
Hi @ronz03130815 ,

I'm sorry but i'm going to close the issue. You didn't follow the template and also, you are reporting an issue related to an unsupported version. Please, use the [forum](https://forum.zentyal.org/index.php/board,10.0.html) to manage this issue.

Best regards, Daniel Joven.

**Comment by Neustradamus** [comment]
Please add the fix here...

**Comment by ronz03130815** [comment]
> Please add the fix here...

i didnt have the fix yet, the workround i tried worked before(see my last post), but not now.

**Comment by Neustradamus** [comment]
Maybe good to create a new ticket?

**Comment by dabsoft22** [comment]
@ronz03130815  
Could you find a solution?
I have the same problem and we couldn't solve it.
Thank you very much if I can give a solution help us
