### ISSUE TITLE
Zentyal 7.0 Problems updating GRUB after the end of the first stage of the installation

### ISSUE THREAD

**Issue by Amado8509** [zentyal/zentyal#2027]
Installation carried out in a virtual machine (Oracle_VM_VirtualBox-6.1.18)

After more than 30 simulations with various configurations the same thing continues to happen to me (Problems when updating and installing the zentyal 7.0 GRUB) just when the first stage of the installation finishes before restarting for the first time.
As additional information, I have checked the CRC of the ISO and it is correct in addition to executing the integrity of the disk with correct results as well.

And I only get this error in Zentyal version 7.0 (in previous versions 6.2, 6.0, 5.1,) everything works perfectly for me.

Also perform an installation of Ubuntu 20.04 Server LTS and 20.10 too in the same virtual machine correctly, also Ubuntu 20.04 for Desktop with the same satisfactory result.

Please check Zentyal 7.0 iso with CRC code: 34904549
and MD5: 1A6E657F5D10AA18FA95191B715FBFD9

![2021-02-02_124605](https://user-images.githubusercontent.com/78289589/106861850-55773200-6694-11eb-9d5b-258e26a228a7.jpg)
![2021-02-02_130249](https://user-images.githubusercontent.com/78289589/106861865-5ad47c80-6694-11eb-8c3e-91a0d3df6395.jpg)
![2021-02-04_024930](https://user-images.githubusercontent.com/78289589/106861900-64f67b00-6694-11eb-92b6-df17dc3c04ff.jpg)

![81F06D78-5B99-477E-8D9F-1955776ABA0C](https://user-images.githubusercontent.com/78289589/106986566-9ffeba00-6739-11eb-8736-a1c63fb7db5c.jpeg)
![E0630494-FCB9-4D3E-9FD0-74D26A8A2098](https://user-images.githubusercontent.com/78289589/106986568-a12fe700-6739-11eb-9fcc-04d5002b0c1f.jpeg)
![798B3A24-3F91-4173-9FB4-BF84A2E65722](https://user-images.githubusercontent.com/78289589/106986569-a1c87d80-6739-11eb-9cb3-8dbc69631118.jpeg)
![683FE755-E68D-44D1-9871-C0067A2546D0](https://user-images.githubusercontent.com/78289589/106986910-5fec0700-673a-11eb-97c6-749749168d95.jpeg)

**Comment by starklnx** [comment]
Such bullshit!

**Comment by Amado8509** [comment]
> Such bullshit!

This problem is real and it has appeared in all the facilities!  that I have done in virtual machines!  even though I have changed the parameters on each new installation!  I have also installed (virtual box) on two different PCs and the result is the same!

**Comment by starklnx** [comment]
VMware 7.x, Isolated VLAN without Internet... and same bullshit!.. I'm angry... With love from Mother Russia... =)

**Comment by Amado8509** [comment]
> VMware 7.x, Isolated VLAN without Internet... and same bullshit!.. I'm angry... With love from Mother Russia... =)
—————————————————



What do you say? What works well? I tried VMware too, and I get the same grub error! Even the Zentyal 6.2 version has been working perfectly, right in this version 7.0 is that it causes me mistakes! So far all previous versions, bring the basics for installations without the Internet in the middle of the process of it! Perhaps this version is very strictly dependent on the Internet in this part of the process? Normally it works with the basic packages and should run correctly assuming that everything was fine!

**Comment by JuanDCG** [comment]
I have the same problem on **bare metal**.

I'm installing zentyal 7.0.iso from cd disk and after all the process right I have this error

**Comment by Amado8509** [comment]
Update 2:  After installing Zentyal 7.0 from the ISO but giving you access to the Internet, I was able to complete the correct installation of the GRUB, although it is not supposed to happen because for a basic installation it should work perfectly from the ISO without the need for Internet access! Once you restart, the Zentyal administration website does not work and has errors!

**Comment by djoven89** [comment]
Hi guys,

You're right, there is a bug with offline installations, as @Amado8509 said, the installation should work without Internet access.

Developers Team have been informed and as soon as possible they will analyze the bug. In the meantime, I'm afraid that you will need to install Zentyal with Internet access during the installation.

Thank you all for your feedback.

Best regards, Daniel Joven.

**Comment by Neustradamus** [comment]
@Amado8509, @starklnx, @JuanDCG: Can you confirm that it has been solved?

**Comment by Amado8509** [comment]
Yes ! that it has been solved In last update !
Everything is ok! Thanks you !

**Comment by starklnx** [comment]
> @Amado8509, @starklnx, @JuanDCG: Can you confirm that it has been solved?

Tnx! It's work for me. Installation without Internet finished succesfully.

**Comment by Amado8509** [comment]
Yes , is solved! All work fine!
