### ISSUE TITLE
Unable to install Zentyal Squid

### ISSUE THREAD

**Issue by JamesUsmar** [zentyal/zentyal#2030]
SQUID Service will not configure and start. Error ‘Can’t use an undefined value as ARRAY reference at /usr/share/perl5/EBox/Module/Base.pm line 285’

It does happen rebuild after rebuild using the Zentyal Package install process, on top of Ubuntu 20.04.1 LTS. Any ideas?

PS: This has been previously reported here: https://forum.zentyal.org/index.php/topic,35121.0/prev_next,prev.html#new
and closed issue 1988 here: https://github.com/zentyal/zentyal/issues/1988

**Comment by djoven89** [comment]
Hi @JamesUsmar ,

Can you provide us more details? Did you get that error in the initial configuration wizard? Which modules did you install? Can you run the following command and send us the output?

```
dpkg -l | grep 'zentyal'
```

Finally, for future reports, please, make sure to use the template.

Best regards, Daniel Joven.

**Comment by JamesUsmar** [comment]
Hi

I just went through the Web Menu to install the 'HTTP Proxy'... nothing special.

**The error:**
james@zentyal:~$ sudo dpkg --configure -a
[sudo] password for james: 
Setting up zentyal-squid (7.0.0) ...
Can't use an undefined value as an ARRAY reference at /usr/share/perl5/EBox/Module/Base.pm line 285.
dpkg: error processing package zentyal-squid (--configure):
 installed zentyal-squid package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 zentyal-squid
james@zentyal:~$ 

**The info:** 
james@zentyal:~$ dpkg -l |grep zentyal
ii  zentyal                                    7.0.0ubuntu1                              all          Zentyal - Core metapackage
ii  zentyal-antivirus                          7.0.1                                     all          Zentyal - Antivirus
ii  zentyal-core                               7.0.0                                     all          Zentyal - Core
ii  zentyal-dhcp                               7.0.0                                     all          Zentyal - DHCP Server
ii  zentyal-dns                                7.0.0                                     all          Zentyal - DNS Server
ii  zentyal-firewall                           7.0.0                                     all          Zentyal - Firewall
ii  zentyal-ips                                7.0.0                                     all          Zentyal - Intrusion Prevention System
ii  zentyal-network                            7.0.0                                     all          Zentyal - Network Configuration
ii  zentyal-ntp                                7.0.0                                     all          Zentyal - NTP Service
ii  zentyal-software                           7.0.0                                     all          Zentyal - Software Management
iF  zentyal-squid                              7.0.0                                     all          Zentyal - HTTP Proxy
james@zentyal:~$

Any ideas?

Thank you. James

**Comment by brunolorente** [comment]
Hi @JamesUsmar,

There is a dependency issue with Samba that we are already fixing, you've 2 options, install zentyal-samba (it doesn't matter if module is enabled or not) or try to wait until we finish the patch, I hope it's fixed at the beginning of the following week.

**Comment by brunolorente** [comment]
Hi @JamesUsmar could you please try again?

**Comment by Neustradamus** [comment]
@JamesUsmar: Any news on it?

**Comment by djoven89** [comment]
Closing the issue because we didn't get any feedback since March.

Best regards, Daniel Joven.
