### ISSUE TITLE
Unable to install Zentyal IDS on updated Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by JamesUsmar** [zentyal/zentyal#2032]
Following a Package install of Zentyal 7.0 on an updated Ubuntu 20.04.1 LTS I found that Suricata is no longer supported for the IDS. any ideas?

**Comment by djoven89** [comment]
Hi @JamesUsmar ,

Thank you for reporting the issue, we have modify the unattended script. [Here](http://download.zentyal.com/install) you have the URL to the script, in you case, you just need to run the following commands to be able to install the IPS module:

```
apt-get update
apt-get install gnupg2 -y
echo "deb http://ppa.launchpad.net/oisf/suricata-stable/ubuntu focal main" >> /etc/apt/sources.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D7F87B2966EB736F
```

Best regards, Daniel Joven.

**Comment by JamesUsmar** [comment]
Hi @djoven89 

Super!

I can confirm that doing the following worked to install IDS without errors, manually.
(Albeit enabling the module meant I couldn't get out on to the WAN - one of the default rules must be blocking?)

sudo apt-get update
sudo apt-get install gnupg2 -y
chmod the /etc/apt/sources.list to make editable
sudo echo "deb http://ppa.launchpad.net/oisf/suricata-stable/ubuntu focal main" >> /etc/apt/sources.list
chmod /etc/apt/sources.list back
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys D7F87B2966EB736F
sudo apt-get update
Navigate to Zentyal Web Software Update - there are now half a dozen or so BIND9 updates to apply.

Many thanks.
James

**Comment by JamesUsmar** [comment]
PS: Looks like this can be closed?

**Comment by djoven89** [comment]
Hi @JamesUsmar ,

Glad to hear that the issue has been fixed.

Related to your question, a new issue has been created with that behaviour, you can check it out [here](https://github.com/zentyal/zentyal/issues/2035).

Thank you for your feedback.

Best regards, Daniel Joven.
