### ISSUE TITLE
Unable to set 'Enable Transparent DNS cache' in the Zentyal DNS screen

### ISSUE THREAD

**Issue by JamesUsmar** [zentyal/zentyal#2034]
There appears to be a GUI glitch with the radio button to set 'Enable Transparent DNS cache' in the Zentyal DNS screen, which means it will not select 'on'. This is regardless of the permutations of selecting the 'CHANGE' button or radio button itself. 

Workaround: Add some forwarders (eg 8.8.8.8 or 1.1.1.1) and while they haven't been committed with a save, the radio button to Enable the transparent cache is selectable. So select the radio button, Save it all, and it appears to stick.

**Comment by djoven89** [comment]
Hi @JamesUsmar ,

We have checked this behaviour in a Zentyal 7.0 and we couldn't reproduce it. Which web browser and version are you using? What Zentyal modules do you have installed and enabled?

Best regards, Daniel Joven.

**Comment by JamesUsmar** [comment]
Hi @djoven89 

I cannot reproduce the issue either now.
I would have been using Chrome (latest - 88.0.4324.182).

I found all sorts of problems installing Zentyal as a package on top of an updated Ubuntu 20.04.01 LTS. However, I did find it worked when taking the native ISO and immediately (without updating) applying the Zentyal packages. 

Perhaps monitor and see of if others see the problem?

Best wishes, James
  
PS this is the process I went through on a physical i3 6000 series, 8GB RAM, 256 SSD:

Get Ubuntu using a working PC (Windows assumed)

1. - Get the Ubuntu 20.04.1 LTS ISO from https://ubuntu.com/download/desktop
2. - Get RUFUS for Windows to write the ISO to a USB KEY (4GB or bigger) from https://rufus.ie/
3. - Install RUFUS on Windows
4. - Using a Windows box, write the ISO to the USB key, with Rufus.
5. - Make sure the target PC box is ideally connected to the internet and there is a DHCP/DNS server (eg home router) available to give it away out. This helps with drivers etc.
6. - Plug USB key into target box, boot from USB key (might need to toggle BIOS boot order settings pressing ESC or F10 at first Boot)
7. - Follow the install Ubuntu wizard … very easy… DO NOT update the box!!
8. - Get Zentyal Packages installed. So, from a terminal window:

- sudo apt install curl
- curl -s download.zentyal.com/install | sudo sh

Get Zentyal going

1. At this point use the built in Firefox browser and navigate to https://localhost:8443
2. Except the self signed security risk notice Advanced > Accept Risks
3. Login to Zentyal via web page with the user you created. (If you want to get more secure you should create a separate user etc etc)
4. Do NOT install any Zentyal services packages other than Networking at this stage.
5. Simply configure the Ethernet port connected to the WAN router to get an IP address – that is all at this point. (Lesson Learnt installing packages before Zentyal’s update process seems to cause all sort of problems.)
6. Navigate to the Zentyal Software Update page, and update the list at the bottom.
7. I found 100’s of updates and you cannot just Update All’ (Lesson learnt. I think there is a bug here with anything more than around 25 packages in one go, it breaks)
8. Select 20-25 packages at a go, and install them.
9. This is a bit of trial and error, and clearly there is a dependency package list issue in here.
10. I did have to issue the command ‘sudo dpkg --configure -a’ from time to time. Eventually there were no more packages to update. Having re-listed too!
11. At this stage reboot.
12. Update the box

Log back in and bring up a Terminal Window (look in the apps menu)

- sudo apt-get update

Get some useful utilities – personal taste - for stats, lspci, ifconfig, wireshark, htop, iftop etc – helps with debugging hardware, routing etc stuff. Note for higher security you would not really want these to be on the box, specifically. And some may get installed with Zentyal anyway, so you may get the odd not required message.

- sudo apt-get update
- sudo apt-get install -y iftop
- sudo apt-get install -y net-tools
- sudo apt-get install -y pciutils
- sudo apt install gnupg
- sudo apt-get install synaptic
- sudo apt-get install unity-tweak-tool
- sudo apt-get install vim
- sudo add-apt-repository ppa:oguzhaninan/stacer
- sudo apt-get update
- sudo apt-get install stacer
- sudo add-apt-repository -r  ppa:oguzhaninan/stacer
- sudo apt-get update
- sudo apt install iftop
- sudo add-apt-repository ppa:wireshark-dev/stable
- sudo apt-get update
- sudo apt-get install wireshark
- Note: To start wireshark -> sudo wireshark
- sudo apt-get update

- Download Chrome of the web for Ubuntu via the FireFox browser - https://www.google.co.uk/chrome/
- cd Downloads
- sudo apt install ./google-chrome-stable_current_amd64.deb
- wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add –
- sudo apt-get update
- reboot

Now configure Zentyal (Finally!)

- Using Chrome  navigate to https://localhost:8443
- Except the self-signed security risk notice Advanced > Accept Risks etc
- Login to Zentyal
- Add in the DHCP, DNS, NTP and Fireweall subcomponents.

**Comment by djoven89** [comment]
Hi @JamesUsmar ,

Thank you for your detailed comment, I think it is very useful for the community.

Before close the ticket, I would like to comment two personal impressions about your process:

* If the system administrator has enough knowledge in the CLI, I always recommend to install Zentyal without the graphical environment in production, this is basically to reduce hardware resources and system loads.

* Use only the default web browser in the server itself, the reasons are:
  1. To reduce the packages that the server has to maintain.
  2. Because Zentyal can be managed from another machine, for example, in my case I always connect to the Zentyal server through my computer, and I usually use either Chrome or Firefox for Zentyal Webadmin access and terminator for the SSH connections.

As I said, it is just a personal impressions.

Best regards, Daniel Joven.
