### ISSUE TITLE
browsing stoped when enabling IDS on  external interface

### ISSUE THREAD

**Issue by doricece** [zentyal/zentyal#2035]
hello

while using Zentyal 7 as a web proxy server  i notices that  web  browsing is stopped on clients side in case IDS is enabled on  
external interface.

**Comment by djoven89** [comment]
Hi @doricece ,

Thank you for reporting this behaviour, but please, edit the issue and use the template.

Best regards, Daniel Joven.

**Comment by Neustradamus** [comment]
@doricece: Can you look the @djoven89 comment?

**Comment by djoven89** [comment]
Hi @doricece ,

I'm going to close the ticket, please, for future issues or enhancements, use the template.

Related to the IDS problem, you can continue in [this issue].

[this issue]: https://github.com/zentyal/zentyal/issues/2037

Best regards, Daniel Joven.
