### ISSUE TITLE
zentyal-firewall 7.0.0 references /sbin/iptables

### ISSUE THREAD

**Issue by nickpiggott** [zentyal/zentyal#2039]
After upgrading Zentyal from 6.2.7 to 7.0, there was no IP routing between network interfaces

On inspection, iptables was completely blank. Checking the /var/log/zental/zentyal.log there were errors for /sbin/iptables not found.

On my installation of Ubuntu 20.04, there is only /usr/sbin/iptables.

**Patch**
I patched this by creating a symbolic link from /usr/sbin/iptables to /sbin/iptables

**Expected behavior**
zentyal-firewall should locate iptables, rather then assume it is at a fixed location of /sbin/iptables

**Zentyal OS (please complete the following information):**
 - Version: 7.0.0
 - Version of the module which has the bug: zentyal-firewall-7.0.0
 - Modules installed: ca, core, dhcp, dns, firewall, mail, network, ntp, openvpn, samba, software

**Other OS (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version: 20.04

**Comment by brunolorente** [comment]
Hi @nickpiggott,  this is weird because was fixed in https://github.com/zentyal/zentyal/blob/support/6.2/main/core/src/scripts/release-upgrade#L259 this line is executed when the upgrade has been finished successfully could you give us more feedback?

**Comment by nickpiggott** [comment]
I did have terrible problems with the upgrade (from 6.2.8 to 7.0), so it's possible the script aborted before it reached that point.

Zentyal tried to trigger an update of Ubuntu from 18.04 to 20.04. I had a held back package (python3-zope.interface) which caused the upgrade to fail, and the ensuing dist-upgrade then trashed a load of zentyal packages.

So the script is probably fine, and this isn't a bug (so feel free to close), but somehow I managed to get zenytal-firewall installed without the zental release-upgrade completing, and that's where the problem started.

**Comment by nickpiggott** [comment]
**Suggestion**

I see other people are struggling to recover their systems if the Ubuntu upgrade fails. Could you provide more guidance (which is picked up through search) on how to recover, and check that the release-upgrade script can pick up again and complete the upgrade.

My approach of using dist-upgrade trashed a load of zentyal packages, which I can see *should* be handled in the script by holding them back during the upgrade. But I had triggered the release-upgrade script from the GUI and it wasn't clear that I could run it again to recover (potentially).

**Comment by djoven89** [comment]
Hi @nickpiggott ,

Thank you for your feedback.

We would like to inform you before close the ticket that we are working in the official Zentyal 7.0 documentation, which will contain a section called '**Upgrading from earlier versions**' as the previous versions have, however, for this version we are improving that section with more details and common issues. We think that will be released early next week.

Best regards, Daniel Joven.
