### ISSUE TITLE
Update of zentyal-core failed - cycle found in zentyal-core

### ISSUE THREAD

**Issue by arakan94** [zentyal/zentyal#2045]
Update process failed (run from web GUI) with following log entries:

> 2021-04-01 11:43:47> Processing triggers for libc-bin (2.31-0ubuntu9.2) ...
> 2021-04-01 11:43:48> dpkg: cycle found while processing triggers:
> 2021-04-01 11:43:48>  chain of packages whose triggers are or may be responsible:
> 2021-04-01 11:43:48>   zentyal-core -> zentyal-core -> zentyal-core -> zentyal-core -> zentyal-core -> zentyal-core
> 2021-04-01 11:43:48>  packages' pending triggers which are or may be unresolvable:
> 2021-04-01 11:43:48>   zentyal-core: /usr/lib/ssl
> 2021-04-01 11:43:48>   linux-image-5.4.0-70-generic: linux-update-5.4.0-70-generic
> 2021-04-01 11:43:48> dpkg: error processing package zentyal-core (--configure):
> 2021-04-01 11:43:48>  triggers looping, abandoned

Afterwards, I ran `apt upgrade` again from CLI and it seems to have fixed itself:

> 1 not fully installed or removed.
> After this operation, 0 B of additional disk space will be used.
> Do you want to continue? [Y/n] 
> Setting up zentyal-core (7.0.3) ...
> Synchronizing state of apparmor.service with SysV service script with /lib/systemd/systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install disable apparmor
> Processing triggers for zentyal-core (7.0.3) ...
> Restarting Zentyal module: webadmin                                                                                                                                                              
> Restarting Zentyal module: logs

**Zentyal OS (please complete the following information):**
 - Version: 7.0
 - Version of the module which has the bug: zentyal-core-7.0.3

**Comment by djoven89** [comment]
Hi @arakan94,

We are going to close the ticket as duplicated because this issue is reported in [this] ticket.

[this]: https://github.com/zentyal/zentyal/issues/2010

Best regards, Daniel Joven.
