### ISSUE TITLE
Expiration period for deleted mails not working after upgrade to Zentyal 7

### ISSUE THREAD

**Issue by caguiar** [zentyal/zentyal#2047]
**Describe the bug**
Emails in the trash folder are not being deleted upon the expiration period, after upgrade from v6.2 to v7.0.

**To Reproduce**
1. Go to 'Mail -> General'
2. Set 'Expiration period for deleted mails' to 'expired in: 7 days'
3. Problem: emails in the trash folder older than 7 days are not "purged".

**Expected behavior**
Emails in the trash folder should be deleted after 7 days.

**Screenshots**
Here is just a sample of two emails that remain in the trash folder.
![Captura de ecrã 2021-04-10, às 14 01 47](https://user-images.githubusercontent.com/6797296/114270625-58c8ca00-9a05-11eb-8c86-f3facd7bb30e.png)

**Zentyal OS (please complete the following information):**
 - Version: 7.0

**Comment by djoven89** [comment]
Hi @caguiar,

Thank you for reporting this bug and for your help in this [post], we have added it to the roadmap.

[post]: https://forum.zentyal.org/index.php/topic,35186.msg114435.html#msg114435

**Comment by Neustradamus** [comment]
Any news about it?
