### ISSUE TITLE
AD objects missing after joining existing MS domain

### ISSUE THREAD

**Issue by buzzkillingtonne** [zentyal/zentyal#2053]
**Describe the bug**
There are multiple objects missing in the gui section Users and Computers > Manage, Some groups show up, users are not shown in the left pane but show up in the right pane, no computers are shown on the left or right panes with the exception of domain controllers, groups are show only on the left pane and not the right pane. Also users in different OU's are shown when selecting the default users OU.

**To Reproduce**
1. Join an existing windows domain with existing computers, users, and groups.
2. Open the Users and Computers module and the Manage section.
3. Compare against existing Microsoft Domain Controller ADUC snap-in on the Windows DC.
3. Compare against the cli command: $ sudo samba-tool <user/computer/group> list

**Expected behavior**
Users, computers, and groups should be displayed if the exist in the Microsoft DC and in the samba DB.

**Screenshots**
![image](https://user-images.githubusercontent.com/52645729/117236720-83c8f280-ade6-11eb-851f-ece1be20d4d7.png)
![image](https://user-images.githubusercontent.com/52645729/117235936-e620f380-ade4-11eb-9e3b-cef27cc6220b.png)
![image](https://user-images.githubusercontent.com/52645729/117235996-08b30c80-ade5-11eb-8efc-21149517bd48.png)
![image](https://user-images.githubusercontent.com/52645729/117236050-2aac8f00-ade5-11eb-817d-917ce8c42644.png)

**Zentyal OS (please complete the following information):**
 - Version: 7.0.4
 - Version of the module which has the bug: zentyal-samba-7.0.1
 - Modules installed: DNS, DC, RADIUS, Firewall, DHCP

**Other OS (please complete the following information):**
 - OS: Windows Server 2019 Datacenter
 - Version: 17763.1879

**Comment by buzzkillingtonne** [comment]
I'd also like to add i've noticed the same thing with DNS. I can see that DNS records were in fact replicated when joining the domain, however they do not show in the Zentyal DNS console.

I also noticed DNS record changes only replicate from the Windows domain controller to the Zentyal domain controller, but not from the Zentyal DC to the Windows DC. I've noticed this on both creation and deletion of DNS records.

**Comment by djoven89** [comment]
Hi @buzzkillingtonne,

The view '**Users and Computers**' changed in Zentyal 6.1, and the behavour that you are reporting is correct. The left panel only shows the OUs, groups, computers and the domain controllers, all the users are displayed on the right panel, through the OU or in the default `users` container.

There are some special users and groups that are filter out from the view, concretely, all the LDAP objects which contains the attribute `isCriticalSystemObject`, that why you can see all the users and groups through CLI but not in the GUI.

Related to the computers, did you check the `DN` of the domain computer? If you run the command `samba-tool computer list`, do you see the computers? or do you get any output when you run the following command?

```
## Change 'w7computer' for yours and keep the '$'
ldbsearch -H /var/lib/samba/private/sam.ldb 'sAMAccountName=w7computer$'
```

Related to the DNS records, it's correct, in the GUI you won't see the DNS records replicated from another server, you will only see the records that you have configured manually. To see the DNS records that Zentyal has, you will need to use the CLI, below you have an exmaple:

```
## Change 'zentyal-domain.lan' for your domain and 'administrator' for your administrator user
samba-tool dns query 127.0.0.1 zentyal-domain.lan @ ALL -U administrator
```

Finally, to see the replication status, run the following commands and check the results:

```
samba-tool drs showrepl
samba_dnsupdate --all-names --verbose
```

Best regards, Daniel Joven.

**Comment by buzzkillingtonne** [comment]
Thanks! all those commands worked as expected, I'm glad to know that it is at least working correctly.

I can see the computers when I run both commands, so at least I know that the computers exist in the DB. though i'm not sure why the computers don't show up, its not that big of a deal as long as they exist.
