### ISSUE TITLE
Xorg problem after update

### ISSUE THREAD

**Issue by Ruman-Git** [zentyal/zentyal#2054]
GUI Don't start after update some packages, only way to start GUI is login and startX with SU privileges. 
This is the Xorg Log:

[   661.406]
X.Org X Server 1.20.9
X Protocol Version 11, Revision 0
[   661.407] Build Operating System: Linux 4.15.0-140-generic x86_64 Ubuntu
[   661.407] Current Operating System: Linux xxxx-server 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64
[   661.407] Kernel command line: BOOT_IMAGE=/boot/vmlinuz-5.4.0-72-generic root=UUID=3f13b6c3-60dd-43a1-bd35-242a7ac95d57 ro quiet splash net.ifnames=0 biosdevname=0
[   661.409] Build Date: 08 April 2021  12:29:22PM
[   661.411] xorg-server 2:1.20.9-2ubuntu1.2~20.04.2 (For technical support please see http://www.ubuntu.com/support)
[   661.412] Current version of pixman: 0.38.4
[   661.415]    Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
[   661.415] Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[   661.419] (==) Log file: "/home/xxxx/.local/share/xorg/Xorg.1.log", Time: Sun May  9 14:45:01 2021
[   661.421] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[   661.421] (==) No Layout section.  Using the first Screen section.
[   661.421] (==) No screen section available. Using defaults.
[   661.421] (**) |-->Screen "Default Screen Section" (0)
[   661.421] (**) |   |-->Monitor "<default monitor>"
[   661.422] (==) No monitor specified for screen "Default Screen Section".
        Using a default monitor configuration.
[   661.422] (==) Automatically adding devices
[   661.422] (==) Automatically enabling devices
[   661.422] (==) Automatically adding GPU devices
[   661.422] (==) Automatically binding GPU devices
[   661.422] (==) Max clients allowed: 256, resource mask: 0x1fffff
[   661.422] (WW) The directory "/usr/share/fonts/X11/cyrillic" does not exist.
[   661.422]    Entry deleted from font path.
[   661.422] (WW) The directory "/usr/share/fonts/X11/100dpi/" does not exist.
[   661.422]    Entry deleted from font path.
[   661.422] (WW) The directory "/usr/share/fonts/X11/75dpi/" does not exist.
[   661.422]    Entry deleted from font path.
[   661.422] (WW) The directory "/usr/share/fonts/X11/Type1" does not exist.
[   661.422]    Entry deleted from font path.
[   661.422] (WW) The directory "/usr/share/fonts/X11/100dpi" does not exist.
[   661.422]    Entry deleted from font path.
[   661.422] (WW) The directory "/usr/share/fonts/X11/75dpi" does not exist.
[   661.422]    Entry deleted from font path.
[   661.422] (==) FontPath set to:
        /usr/share/fonts/X11/misc,
        built-ins
[   661.422] (==) ModulePath set to "/usr/lib/xorg/modules"
[   661.422] (II) The server relies on udev to provide the list of input devices.
        If no devices become available, reconfigure udev or disable AutoAddDevices.
[   661.422] (II) Loader magic: 0x55d650fce020
[   661.422] (II) Module ABI versions:
[   661.422]    X.Org ANSI C Emulation: 0.4
[   661.422]    X.Org Video Driver: 24.1
[   661.422]    X.Org XInput driver : 24.1
[   661.422]    X.Org Server Extension : 10.0
[   661.427] (++) using VT number 1

[   661.429] (EE) systemd-logind: failed to get session: PID 7304 does not belong to any known session
[   661.432] (II) xfree86: Adding drm device (/dev/dri/card0)
[   661.447] (--) PCI:*(0@0:15:0) 15ad:0405:15ad:0405 rev 0, Mem @ 0xe8000000/134217728, 0xfe000000/8388608, I/O @ 0x00001070/16, BIOS @ 0x????????/131072
[   661.447] (II) LoadModule: "glx"
[   661.447] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[   661.449] (II) Module glx: vendor="X.Org Foundation"
[   661.449]    compiled for 1.20.9, module version = 1.0.0
[   661.449]    ABI class: X.Org Server Extension, version 10.0
[   661.449] (==) Matched vmware as autoconfigured driver 0
[   661.449] (==) Matched modesetting as autoconfigured driver 1
[   661.449] (==) Matched fbdev as autoconfigured driver 2
[   661.449] (==) Matched vesa as autoconfigured driver 3
[   661.449] (==) Assigned the driver to the xf86ConfigLayout
[   661.449] (II) LoadModule: "vmware"
[   661.450] (II) Loading /usr/lib/xorg/modules/drivers/vmware_drv.so
[   661.490] (II) Module vmware: vendor="X.Org Foundation"
[   661.490]    compiled for 1.20.8, module version = 13.3.0
[   661.490]    Module class: X.Org Video Driver
[   661.490]    ABI class: X.Org Video Driver, version 24.1
[   661.490] (II) LoadModule: "modesetting"
[   661.490] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[   661.491] (II) Module modesetting: vendor="X.Org Foundation"
[   661.491]    compiled for 1.20.9, module version = 1.20.9
[   661.491]    Module class: X.Org Video Driver
[   661.491]    ABI class: X.Org Video Driver, version 24.1
[   661.491] (II) LoadModule: "fbdev"
[   661.491] (II) Loading /usr/lib/xorg/modules/drivers/fbdev_drv.so
[   661.491] (II) Module fbdev: vendor="X.Org Foundation"
[   661.491]    compiled for 1.20.1, module version = 0.5.0
[   661.491]    Module class: X.Org Video Driver
[   661.491]    ABI class: X.Org Video Driver, version 24.0
[   661.491] (II) LoadModule: "vesa"
[   661.491] (II) Loading /usr/lib/xorg/modules/drivers/vesa_drv.so
[   661.492] (II) Module vesa: vendor="X.Org Foundation"
[   661.492]    compiled for 1.20.4, module version = 2.4.0
[   661.492]    Module class: X.Org Video Driver
[   661.492]    ABI class: X.Org Video Driver, version 24.0
[   661.492] (II) vmware: driver for VMware SVGA: vmware0405, vmware0710
[   661.492] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[   661.492] (II) FBDEV: driver for framebuffer: fbdev
[   661.492] (II) VESA: driver for VESA chipsets: vesa
[   661.492] xf86EnableIOPorts: failed to set IOPL for I/O (Operation not permitted)
[   661.492] (WW) Falling back to old probe method for modesetting
[   661.492] (EE) open /dev/dri/card0: Permission denied
[   661.492] (WW) Falling back to old probe method for fbdev
[   661.492] (II) Loading sub module "fbdevhw"
[   661.492] (II) LoadModule: "fbdevhw"
[   661.492] (II) Loading /usr/lib/xorg/modules/libfbdevhw.so
[   661.526] (II) Module fbdevhw: vendor="X.Org Foundation"
[   661.526]    compiled for 1.20.9, module version = 0.0.2
[   661.526]    ABI class: X.Org Video Driver, version 24.1
[   661.526] (EE) open /dev/fb0: Permission denied
[   661.526] (WW) VGA arbiter: cannot open kernel arbiter, no multi-card support
[   661.526] (II) vmware(0): Creating default Display subsection in Screen section
        "Default Screen Section" for depth/fbbpp 24/32
[   661.705] (EE) vmware(0): Failed to open drm.
[   661.705] (WW) vmware(0): Disabling 3D support.
[   661.705] (WW) vmware(0): Disabling Render Acceleration.
[   661.705] (WW) vmware(0): Disabling RandR12+ support.
[   661.705] (--) vmware(0): VMware SVGA regs at (0x1070, 0x1071)
[   661.705] (II) Loading sub module "vgahw"
[   661.705] (II) LoadModule: "vgahw"
[   661.706] (II) Loading /usr/lib/xorg/modules/libvgahw.so
[   661.739] (II) Module vgahw: vendor="X.Org Foundation"
[   661.739]    compiled for 1.20.9, module version = 0.1.0
[   661.739]    ABI class: X.Org Video Driver, version 24.1
[   661.764] (EE)
[   661.764] (EE) Backtrace:
[   661.782] (EE) 0: /usr/lib/xorg/Xorg (OsLookupColor+0x13c) [0x55d650f405ac]
[   661.783] (EE) 1: /lib/x86_64-linux-gnu/libpthread.so.0 (funlockfile+0x60) [0x7f0329be741f]
[   661.784] (EE) 2: /lib/x86_64-linux-gnu/libpciaccess.so.0 (pci_io_write8+0x7) [0x7f032a337c17]
[   661.784] (EE) 3: /usr/lib/xorg/modules/libvgahw.so (vgaHWSaveColormap+0x4a) [0x7f0323a36a9a]
[   661.784] (EE) 4: /usr/lib/xorg/modules/libvgahw.so (vgaHWSave+0x35) [0x7f0323a38bb5]
[   661.785] (EE) unw_get_proc_name failed: no unwind info found [-10]
[   661.785] (EE) 5: /usr/lib/xorg/modules/drivers/vmware_drv.so (?+0x0) [0x7f03293b3700]
[   661.785] (EE) 6: /usr/lib/xorg/Xorg (InitOutput+0xb94) [0x55d650e20be4]
[   661.785] (EE) 7: /usr/lib/xorg/Xorg (InitFonts+0x1d4) [0x55d650de2de4]
[   661.786] (EE) 8: /lib/x86_64-linux-gnu/libc.so.6 (__libc_start_main+0xf3) [0x7f0329a050b3]
[   661.786] (EE) 9: /usr/lib/xorg/Xorg (_start+0x2e) [0x55d650dcca2e]
[   661.787] (EE)
[   661.787] (EE) Segmentation fault at address 0x8
[   661.787] (EE)
Fatal server error:
[   661.787] (EE) Caught signal 11 (Segmentation fault). Server aborting
[   661.787] (EE)
[   661.787] (EE)
Please consult the The X.Org Foundation support
         at http://wiki.x.org
 for help.
[   661.787] (EE) Please also check the log file at "/home/xxxx/.local/share/xorg/Xorg.1.log" for additional information.
[   661.787] (EE)
[   661.790] (EE) Server terminated with error (1). Closing log file.

**Comment by djoven89** [comment]
Hi @Ruman-Git,

I'm sorry but i have to close this issue, you didn't follow the template, so, we don't know which version of Zentyal are you using, which packages did you update, which command you run, etc.

By the way, did you try with the keyboard combination: '**CRTL + ALT + F7**' or '**ALT + F7**'?

Best regards, Daniel Joven.
