### ISSUE TITLE
Error while restarting the DNS module

### ISSUE THREAD

**Issue by autmik** [zentyal/zentyal#2058]
Restarting the DNS module gives the following error:
`2021/05/22 20:17:47 ERROR> Service.pm:969 EBox :: Module :: Service :: restartService - Error restarting service: Can't call method "valueByName" on an undefined value at / usr / share / perl5 / EBox / DNS.pm line 1291`

**Comment by djoven89** [comment]
Hi @autmik,

I'm sorry I have to close the issue because you didn't follow the template.

If the issue persists, create a new one and provide all the details you can, just remember to use the template.

Best regards, Daniel Joven.

**Comment by Neustradamus** [comment]
Any news about it?
