### ISSUE TITLE
login via webadmin problem

### ISSUE THREAD

**Issue by tfkuser** [zentyal/zentyal#2059]
Hi,

The problem started two/three weeks ago. Once or twice a day an error appears on the login page of the server's services in the web browser. The problem appears regardless of whether the session is logged out or just the closed web browser page before.

![Zrzut ekranu 2021-05-28 164257](https://user-images.githubusercontent.com/84978346/120002325-3cd4b400-bfc4-11eb-9d01-946206bd4f58.png)

The problem is not related to the user who logs into the website. Tested on 4 different users.
The problem is solved by restarting the "webadmin" service after a terminal connection to the server. After restarting webadmin service is averything ok again.

![Zrzut ekranu 2021-05-28 170529](https://user-images.githubusercontent.com/84978346/120004349-2a5b7a00-bfc6-11eb-855b-0d94ee3967f6.png)

**Describe the bug**
Sorry, an unexpected error has occurred
DBD::mysql::st execute failed: The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. at /usr/share/perl5/EBox/MyDBEngine.pm line 281

After click "Show technical details" show this:

    in EBox::MyDBEngine::unbufferedInsert at /usr/share/perl5/EBox/MyDBEngine.pm line 281

      278:     $sql = (substr($sql, 0, -1)).')';
      279: 
      280:     $self->_prepare($sql);
      281:     my $err = $self->{'sthinsert'}->execute(@vals);
      282:     if (!$err) {
      283:         #throw exception
      284:         EBox::debug ("Error inserting data: $sql\n" .

    Show function arguments
    in EBox::AuditLogging::logSessionEvent at /usr/share/perl5/EBox/AuditLogging.pm line 293

      290:         delete $self->{username};
      291:     }
      292: 
      293:     $self->_db()->unbufferedInsert(TABLE_SESSIONS, \%data);
      294: }
      295: 
      296: sub logShutdown

    Show function arguments
    in EBox::Middleware::Auth::_login at /usr/share/perl5/EBox/Middleware/Auth.pm line 278

      275:             $env->{'psgix.session'}{AuthReason} = 'Incorrect password';
      276:             $self->_cleanSession($env);
      277:             $log->warn("Failed login from: $ip");
      278:             if ($self->app_name eq 'webadmin') {
      279:                 $audit->logSessionEvent($user, $ip, 'fail');
      280:             }
      281:         }

    Show function arguments
    in EBox::Middleware::Auth::call at /usr/share/perl5/EBox/Middleware/Auth.pm line 360

      357:     $env->{'psgix.session'}{app} = $self->app_name;
      358: 
      359:     if ($path eq '/Login/Index') {
      360:         $self->_login($env);
      361:     } elsif ($path eq '/Logout/Logout') {
      362:         # We get here from Logout/Index, once the logout is confirmed.
      363:         $self->_logout($env);

    Show function arguments
    in Plack::Component::__ANON__ at /usr/share/perl5/Plack/Component.pm line 50

       47: sub to_app {
       48:     my $self = shift;
       49:     $self->prepare_app;
       50:     return sub { $self->call(@_) };
       51: }
       52: 
       53: 

    Show function arguments
    in Plack::Middleware::Conditional::call at /usr/share/perl5/Plack/Middleware/Conditional.pm line 16

       13:     my($self, $env) = @_;
       14: 
       15:     my $app = $self->condition->($env) ? $self->middleware : $self->app;
       16:     return $app->($env);
       17: }
       18: 
       19: 1;

    Show function arguments
    in Plack::Component::__ANON__ at /usr/share/perl5/Plack/Component.pm line 50

       47: sub to_app {
       48:     my $self = shift;
       49:     $self->prepare_app;
       50:     return sub { $self->call(@_) };
       51: }
       52: 
       53: 

    Show function arguments
    in EBox::WebAdmin::Middleware::SubAppAuth::call at /usr/share/perl5/EBox/WebAdmin/Middleware/SubAppAuth.pm line 57

       54:             }
       55:         }
       56:     }
       57:     return $self->app->($env);
       58: }
       59: 
       60: 1;

    Show function arguments
    in Plack::Component::__ANON__ at /usr/share/perl5/Plack/Component.pm line 50

       47: sub to_app {
       48:     my $self = shift;
       49:     $self->prepare_app;
       50:     return sub { $self->call(@_) };
       51: }
       52: 
       53: 

    Show function arguments
    in Plack::Middleware::Session::call at /usr/share/perl5/Plack/Middleware/Session.pm line 53

       50: 
       51:     $env->{'psgix.session.options'} = { id => $id };
       52: 
       53:     my $res = $self->app->($env);
       54:     $self->response_cb($res, sub { $self->finalize($env, $_[0]) });
       55: }
       56: 

    Show function arguments
    in Plack::Component::__ANON__ at /usr/share/perl5/Plack/Component.pm line 50

       47: sub to_app {
       48:     my $self = shift;
       49:     $self->prepare_app;
       50:     return sub { $self->call(@_) };
       51: }
       52: 
       53: 

    Show function arguments
    in Plack::Middleware::ReverseProxy::call at /usr/share/perl5/Plack/Middleware/ReverseProxy.pm line 68

       65:         }
       66:     }
       67: 
       68:     $self->app->($env);
       69: }
       70: 
       71: 1;

    Show function arguments
    in EBox::Middleware::UnhandledError::call at /usr/share/perl5/Plack/Component.pm line 50

       47: sub to_app {
       48:     my $self = shift;
       49:     $self->prepare_app;
       50:     return sub { $self->call(@_) };
       51: }
       52: 
       53: 

    Show function arguments
    in Plack::Component::__ANON__ at /usr/share/perl5/Plack/Component.pm line 50

       47: sub to_app {
       48:     my $self = shift;
       49:     $self->prepare_app;
       50:     return sub { $self->call(@_) };
       51: }
       52: 
       53: 
-----------------------

**Zentyal OS:**
 - Version: [6.2.9 upgraded to 7.0.4]
 - Modules installed [e.g. DNS, DC, LOGS, NTP, FIREWALL, NETWORK]

**Other OS:**
 - OS: [e.g. Windows 10, Ubuntu 20.04, Ubuntu 21.04, Linux Mint]
 - WEBBrowsers: [Firefox, Chrome, Brave, Opera, Microsoft Edge]

**Comment by djoven89** [comment]
Hi @tfkuser ,

Thank you for your feedback, but this issue was reported [here].

[here]: https://github.com/zentyal/zentyal/issues/2055

Best regards, Daniel Joven.
