### ISSUE TITLE
Zentyal Mail module chash

### ISSUE THREAD

**Issue by alex2ospina** [zentyal/zentyal#2060]
**Describe the bug**
After upgrade from zentyal 6.2 to 7 the module mail not start.

**error when tray to start**
zs mail start
 * Restarting Zentyal module: mail                                       [fail]
root command samba-tool group addmembers 'Domain Admins' zentyal-mail-(servername) failed.
Error output: ldb_wrap open of secrets.ldb
 string_to_sid: SID zentyal-mail-(servername) is not in a valid format
 ERROR(ldb): Failed to add members "zentyal-mail-(servername)" to group "Domain Admins" - Attribute member already exists for target GUID 86d68681-fa3a-4014-8251-25e3382b24de
   File "/usr/lib/python3/dist-packages/samba/netcmd/group.py", line 245, in run
     samdb.add_remove_group_members(groupname, groupmembers,
   File "/usr/lib/python3/dist-packages/samba/samdb.py", line 320, in add_remove_group_members
     self.modify_ldif(addtargettogroup)
   File "/usr/lib/python3/dist-packages/samba/__init__.py", line 241, in modify_ldif
     self.modify(msg, controls)

Command output: .
Exit value: 255

**Zentyal OS community (7.0.4):**
 - Version: [7.0.4]
 - Modules installed [mail] version 7.0.1

**Comment by djoven89** [comment]
Hi @alex2ospina,

Did you try to remove that user from the domain group `Domain Admins`?

```
sudo samba-tool group removemembers 'Domain Admins' zentyal-mail-name_server
```

**NOTE:** Replace `name_server` for the name of your Zentyal 7.0 server.

Once you did that change, try to restart again the `mail` module.

Best regards, Daniel Joven.

**Comment by djoven89** [comment]
Closing the ticket due to inactivity and because we couldn't reproduce it.

Best regards, Daniel Joven.
