### ISSUE TITLE
error Ldap.pm starting samba module

### ISSUE THREAD

**Issue by buye** [zentyal/zentyal#2061]
Hi guys  after upgrade from version 6 to 7 of Zentyal I have a problem with  samba module. 
Everytime I start or restart the module I've the following error in the log file
Ldap.pm:219 EBox::Ldap::safeConnect - FATAL: Could not connect to samba LDAP server: connect: Permission denied at FATAL: Could not connect to samba LDAP server: connect: Permission denied at /usr/share/perl5/EBox/Ldap.pm line 219
however in the end samba starts anyway.....
The only thing that I've changed from previous version is that I've launched the following command "samba_upgradedns --dns-backend=BIND9_DLZ" and now all files are moved inside bind-dns folder. Could that be the problem?
Is there a way to solve this issue?
Thanks
Carlo

**Comment by djoven89** [comment]
Hi @buye,

I have to close this issue because you didn't use the template. Please, create a new one using the correct format.

Before closing the ticket, below you have some actions that I recommend you to analyze:

1. Check the permissions of the directory `/var/lib/samba/bind-dns/`. Below you have an output from one of our test machines:

```
ls -ld /var/lib/samba/bind-dns/
drwxrwx--- 3 root bind 4096 jun  3 14:05 /var/lib/samba/bind-dns/


ls -lR /var/lib/samba/bind-dns/
/var/lib/samba/bind-dns/:
total 20
drwxrwx--- 3 root bind 4096 jun  2 11:12 dns
-rw-r----- 2 root bind  862 jun  2 11:12 dns.keytab
-rw-r--r-- 1 root root  884 jun  2 11:12 named.conf
-r--r--r-- 1 root root  244 jun  2 11:12 named.conf.update
-rw-r--r-- 1 root root 2051 jun  2 11:12 named.txt

/var/lib/samba/bind-dns/dns:
total 3544
-rw-rw---- 1 root bind 3620864 jun  2 11:12 sam.ldb
drwxrwx--- 2 root bind    4096 jun  2 11:12 sam.ldb.d

/var/lib/samba/bind-dns/dns/sam.ldb.d:
total 27724
-rw-rw---- 1 root bind 7651328 jun  2 11:12 CN%3DCONFIGURATION%2CDC%3DZENTYAL-DOMAIN%2CDC%3DLAN.ldb
-rw-rw---- 1 root bind 9625600 jun  2 11:12 CN%3DSCHEMA%2CCN%3DCONFIGURATION%2CDC%3DZENTYAL-DOMAIN%2CDC%3DLAN.ldb
-rw-rw---- 2 root bind 4694016 jun  3 12:50 DC%3DDOMAINDNSZONES%2CDC%3DZENTYAL-DOMAIN%2CDC%3DLAN.ldb
-rw-rw---- 2 root bind 4694016 jun  2 11:59 DC%3DFORESTDNSZONES%2CDC%3DZENTYAL-DOMAIN%2CDC%3DLAN.ldb
-rw-rw---- 1 root bind 1286144 jun  2 11:12 DC%3DZENTYAL-DOMAIN%2CDC%3DLAN.ldb
-rw-rw---- 2 root bind  421888 jun  3 12:55 metadata.tdb

```

2. Generate a system report and analize it:

```
sudo /usr/share/zentyal/smart-admin-report
```

3. Analyze the log files:

	* /var/log/zentyal/zentyal.log
	* /var/log/syslog
	* /var/log/samba/samba.log

Best regards, Daniel Joven.
