### ISSUE TITLE
Small issue with Vacation Auto-Response

### ISSUE THREAD

**Issue by RHOPKINS13** [zentyal/zentyal#2067]
Ran into a problem with the Vacation Auto-Response. Running Zentyal Development Edition 7.0.

We already set SOGOVacationEnabled = YES in sogo.conf.mas, and we're able to access the vacation settings under sogo. But after turning vacation auto reply on, we tested it, and found that it wasn't working. Looking in the mail error logs, we saw dovecot throwing errors:
`Error: sieve: Failed to initialize script execution: Invalid postmaster_address: invalid address `postmaster' specified for the postmaster_address setting`

By default, under Mail->General->Options, the Postmaster address is set as Local root account. This results in postmaster_address = postmaster in dovecot.conf. Once we set the Postmaster address to "Custom address" and used a valid address in the system (we used administrator@mydomain.com) the vacation auto reply e-mails started working fine.

**To Reproduce**
1. Set SOGOVacationEnabled = YES in sogo.conf.mas
2. Restart SOGo Webmail module
3. Under Mail->General->Mail Server Options, ensure Postmaster address is set to Local root account. Save changes if needed.
4. Log in to SOGo and set up a vacation auto-reply message.
5. Try sending a test e-mail from another account.
6. Observe that no auto-response is sent, and see above dovecot error in /var/log/mail.err.

**Expected behavior**
An e-mail should automatically be sent out in response to e-mails received while vacation auto-reply is turned on.

**Zentyal OS (please complete the following information):**
 - Version: 7.0

**Comment by djoven89** [comment]
Hi @RHOPKINS13 ,

We have confirmed the bug, we have added it to the roadmap.

Thank you for reporting it.

Best regards, Daniel Joven.
