### ISSUE TITLE
Unable to add Additional Domain Controller

### ISSUE THREAD

**Issue by lukewowo** [zentyal/zentyal#2071]
Installed a new Zentyal 7.0.4 twice, and the same results happen when trying to add an Additional Domain Controller to an existing Zentyal 6.2 domain.

![image](https://user-images.githubusercontent.com/6294025/128186185-666fd5ae-8696-418d-910f-73d06d638acc.png)

**Comment by imrelaszlo** [comment]
Maybe this problem is related to my topic: https://github.com/zentyal/zentyal/issues/2051

**Comment by thctlo** [comment]
+1 thats simple wrongly written making it confusing and prone to errors. 

DOMAINNAME should be DNS-DOMAINNAME .. ( the "right" part of the hostname.FQDN ) 
HOSTNAME   should be : SERVER-HOSTNAME   .. ( the "left" part of the hostname.FQDN )  

NETBIOS-DOMAIN = ADDOM or old school .. NT4DOM  ( can be anything, but you can follow this rule. ) 
internal.domain.tld, then INTERNAL is often used at NETBIOS-DOMAINNAME
NETBIOS-HOSTNAME = SERVER-HOSTNAME

please read this one 
[https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou](https://docs.microsoft.com/en-us/troubleshoot/windows-server/identity/naming-conventions-for-computer-domain-site-ou)
There are much more restritions then people think, if you want to setup correctly.
