### ISSUE TITLE
Missing font  japanese language env.

### ISSUE THREAD

**Issue by osakanataro** [zentyal/zentyal#2072]
**Describe the bug**
I installed zentyal , using zentyal-7.0-development-amd64.iso.
Zentyal webui not display japanese font.

**To Reproduce**
1. boot zentyal-7.0-development-amd64.iso
2. Select "Japanese"
3. Install

**Screenshots**
missing font 
![image](https://user-images.githubusercontent.com/1303296/129285936-309de5b8-9ed8-4987-ba95-954e8029ccde.png)

**Zentyal OS (please complete the following information):**
 - Version: 7.0

**Additional context**
I installed fowlloing packages.
`sudo apt install language-pack-ja firefox-locale-ja  fonts-arphic-uming fonts-takao-pgothic`

Then web ui was display normally
![image](https://user-images.githubusercontent.com/1303296/129285916-2bdaf3d0-932f-4772-bcb9-a728a7f0aee9.png)

**Comment by brunolorente** [comment]
Hi @osakanataro thank you very much for your contribution, added to the roadmap!
