### ISSUE TITLE
Zentyal 7 ERROR The client was disconnected by the server because of inactivity

### ISSUE THREAD

**Issue by Krustak** [zentyal/zentyal#2082]
**Describe the bug**
Hello, every time I log in into Zentyal 7 as webadmin and leave session (close browser without loging out) next time I'll try to login back I got Error saying

Sorry, an unexpected error has occurred
DBD::mysql::st execute failed: The client was disconnected by the server because of inactivity. See wait_timeout and interactive_timeout for configuring this behavior. at /usr/share/perl5/EBox/MyDBEngine.pm line 281

**To Reproduce**
1. Login to web interface
2. Close browser without loging out
3. Wait predefined time so session end (dunno what time it is)
4. Try to login back

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/47980734/140470257-f729f35d-eca8-40c3-85cf-51bea8f98c01.jpg)
![Screenshot_2](https://user-images.githubusercontent.com/47980734/140470260-428c9e0d-5518-4f65-b47f-21235aba770d.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/47980734/140470263-76868cd8-03d2-4275-9c0b-94479a374722.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/47980734/140470266-cbb7a49d-6f51-4944-9df8-18df937c81c4.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/47980734/140470270-93272ca2-ae9a-40d9-8e0c-d77c79f3a2ea.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/47980734/140470271-0a97ffb9-4e7a-40e8-a53d-6f8c3e502822.jpg)

**Zentyal OS (please complete the following information):**
 - Version: 7.0.4
 - Version of the module which has the bug - ?
 - Modules installed: Firewall, VPN, NTP, Certificate, Logs, Network

**Comment by RetMC** [comment]
Same here.
Restarting webadmin module fixes the problem (sudo zs webadmin restart)

**Comment by leebd1** [comment]
Im having the same issue as well.

Here is another related reported issue >> https://github.com/zentyal/zentyal/issues/2055

**Comment by leebd1** [comment]
Im trying to understand why Zentyal would have this log service using a user account instead of a service account to perform this service.

**Comment by gigabit** [comment]
Same Error Here, same condition as described above. Did not logout of console.   Reboot is a temp fix. Why has there been no comment from Zentyal on this?

**Comment by nockdown** [comment]
I'm having the same issue too.

Steps to reproduce the behavior:
Login to web interface in incognito mode via Chrome 99.0.4844.51
Loging out
Close browser
Wait predefined time so session end
Try to login back

**Comment by preewo** [comment]
Any fixes ?

**Comment by brunolorente** [comment]
Hi everyone, we are still working on this, closing as duplicated by #2055
