### ISSUE TITLE
acl and user_xattr is required (?)

### ISSUE THREAD

**Issue by fischerscode** [zentyal/zentyal#2086]
**DISCLAIMER: I am absolutely not a (linux) file system expert.**

**Describe the bug**
I am trying to set up zentyal as a VM on an unraid server.
When mounting a (unraid) share in the file system of the VM using 9p, I can not create a zentyal share inside the unraid share.

A read box appears:
```
The mount point '/mnt/myunraidshare' must be mounted with 'acl' option. This is required for permissions to work properly.
```
When adding 'posixacl':
```
The mount point '/mnt/myunraidshare' must be mounted with 'user_xattr' option. This is required for permissions to work properly.
```

**To Reproduce**
1. mount using `mount -t 9p -o trans=virtio myunraidshare /mnt/myunraidshare -oversion=9p2000.L` (also tested with `-oversion=9p2000.L,posixacl`)
2. Click on 'File Sharing'
3. Click on 'ADD NEW'
4. Enter share name
5. Select 'File system path'
6. Enter path '/mnt/myunraidshare'
7. Click 'ADD'

**Expected behavior**
I am naive enough to think it should just be added. Esp. since `setfattr` and `getfattr` work.
Perhaps I am totally wrong, but I assume (no knowledge!) 9p mounts with acl and user_xattr by default, [just like other filesystems](https://github.com/zentyal/zentyal/blob/ac34b2c90bc0b92b7be605a2e4d326834517b724/main/samba/src/EBox/Samba/Model/SambaShares.pm#L436-L439).

**Screenshots**

**Zentyal OS (please complete the following information):**
 - Version: 7.0.4 (Development Edition)
 - 'Domain Controller and File Sharing' 7.0.1
 - Modules installed [e.g. Domain Controller and File Sharing, Core, DNS, Firewall, NTP, Network Configuration, Software Management]

**Other OS (please complete the following information):**
 - Unraid 6.9.2

**Additional context**
As stated above I have no experience regarding linux filesystems, but for me it seems like my configuration should be correct.
For now, I might try to remove the check and see if it works.

**Comment by brunolorente** [comment]
Hi @fischerscode, this is not a bug, probably you'll forget to set the right option during the mounting process (in samba shares config) You'll find the code that manages this behavior in this file: 
`main/samba/src/EBox/Samba/Model/SambaShares.pm`

Please open a new topic in our forum :)
