### ISSUE TITLE
Dovecot: delivered via dovecot service: Error: net_connect_unix(/var/run/dovecot/stats-writer) failed: Permis

### ISSUE THREAD

**Issue by marneu** [zentyal/zentyal#2087]
**Above mentioned error occurs on delivery of mail**

**To Reproduce**
1. Do an install of zentyal 7, configure and try to send mail from an allowed relay
2. Check /var/log/mail.log

**Expected behavior**
No error

**Zentyal OS (please complete the following information):**
 - Version: 7.0.4
 - Modules installed [MAIL etc.]
 - OS: [focal 20.04]

**can be fixed with**
/etc/dovecot/extra.conf:
```
service stats {
  unix_listener stats-reader {
    group = postfix
    mode = 0666
  }
  unix_listener stats-writer {
    group = postfix
    mode = 0666
  }
}
service anvil {
  unix_listener anvil {
    group = postfix
    mode = 0666
  }
}
```

**Comment by brunolorente** [comment]
Hi @marneu,

Thank you very much for your support, could you please open a new PR? I will be glad to merge it :)
