### ISSUE TITLE
How can I login my first time to admin console after install zentyal by ssh shell?

### ISSUE THREAD

**Issue by JuanDCG** [zentyal/zentyal#2089]
**Zentyal OS (please complete the following information):**
 - Version: 7

**Other OS (please complete the following information):**
 - OS: Ubuntu
 - Version: 20.04

**Additional context**
Default password? I try it with other sudoer user but I can't log in.

**Comment by brunolorente** [comment]
Hi @JuanDCG,

Thank you for your comment,  but this is not a bug, could you please open a new topic in our forum? https://forum.zentyal.org/index.php?board=2.0
