### ISSUE TITLE
Can't add more cores to VM , Performance issues

### ISSUE THREAD

**Issue by Stefan-CPlanet** [zentyal/zentyal#2093]
**Describe the bug**
Horrible performance in Windows 10 Virtual machine. Issue is caused by VM only having 1 core dedicated to it. My zentyal server has 12 cores but I am unable to add more to the VM.

**To Reproduce**
1. Install  Zentyal
2. Add amd64 Windows Virtual machine
3. Try to use it, extremely bad performance

**Expected behavior**
A usable virtual machine 

**Screenshots**
<img width="671" alt="Screenshot 2022-05-16 at 16 06 16" src="https://user-images.githubusercontent.com/40995654/168611288-ee4bbc82-a166-4607-a61d-b29b3ce1576c.png">

**Zentyal OS (please complete the following information):**
 - Version: Latest
 - Version of the module which has the bug: latest
 - Modules installed: antivirus, DNS, Active Directory, virtualization manager

**Additional context**
Hello, there is no way to change the number of CPU cores in the GUI. with crontab I see that the qemu script is running with 1 core, but I cannot find where to change it to 2 or more cores.

Please advise
Best regards

**Comment by djoven89** [comment]
Hi @Stefan-CPlanet ,

The type of this issue must be '**Enhancement**' not 'Bug'. Zentyal does not provide an option from GUI to set the number of cores but you can do it through CLI, concretely, you can use the `virsh` command to accomplish the task.

That being said, we are going to close this issue and if you think Zentyal should have this option, please, create a new issue of type '**Enhancement**' following the template.
