### ISSUE TITLE
Problems with samga log

### ISSUE THREAD

**Issue by tiagopradolinux** [zentyal/zentyal#2094]
In samba logs it only shows the actions "Connect" and "Disconnect", actions like "Create Directory", "Write file" and "remove" do not show.
The page is "https://192.168.200.30:8443/Logs/Index?refresh=1&selected=samba_access"
To show these actions is only in the commercial version?
Thanks.

**Zentyal OS (please complete the following information):**
 - Version: 7.0
 - Version of the module which has the bug []
 - Modules installed [DNS, DC]

**Comment by djoven89** [comment]
Hi @tiagopradolinux ,

We have confirmed the bug and added it to the roadmap.

Thank you for reporting this.

**Comment by Rubarius** [comment]
Hello. Will it ever be fixed? Now there is a server on which there are no logs of user actions. Generally there are no logs in the web interface. This is a big problem.

**Comment by peptoniet** [comment]
Hi @Rubarius,
I think, at this point, you are still lucky.
Once I was adviced by mr. @brunolorente to fix a bug by myself (https://github.com/zentyal/zentyal/issues/1958)  I will let you judge by yourself if there is "nothing to do" as mr. brunolorente said.  I will gladly apologize if my report was not a genuine bug.
As far as I know, a roadmap is used for new features.  If you need a roadmap to organize bugs, it concerns me.
Last commit was more than three months ago.
They said they were relocating to the EE.UU. (if I recall correctly)...
