### ISSUE TITLE
webadmin dont save

### ISSUE THREAD

**Issue by fetchman007** [zentyal/zentyal#2102]
**Describe the bug**
the webadmin, right corner above, it always displaying, that he wants to save the changes.
If i click on this , its always try to save it, sometimes it is function. 
The saving screen pops up, and stays. the webadmin is not automatically refreshing himself.
The error is appearing all the time. Need to refresh the browser, and hope the changes are saved by the zentyal. 
Sometimes it did not save it

**Zentyal OS 7.0 on linux 

See the screens shots and might be someone got an idea how to fix this .....

No No NO sweet MS user, I DONT RESINSTALL ANYTHING..........ITS LINUX, have a door to get throught to fix ....... ;-)

Screen 1  >>> orange button...you know it

![z1](https://user-images.githubusercontent.com/110908122/183641486-e4a325ec-0499-4a7d-b4a9-ca414be59a7f.jpg)

Screen 2 >>> this stays until i fresh the browser.
![z2](https://user-images.githubusercontent.com/110908122/183641556-a4b12bc1-64b2-4156-a44a-8dc93148ea4b.jpg)

**Comment by mrPsycho** [comment]
oh, i thought it is something with my setup....
but same story on clean zentyal 7.0, which was downloaded 2 days ago.

**Comment by sydmund** [comment]
Same here. Fresh installation (Proxmox, 8 GB RAM, eth0 internal).

/var/log/zentyal/error.log (first line from finishing an installation, next from "SAVE CHANGES"):

`2022/10/17 01:13:48 [error] 35373#35373: *104 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /SysInfo/CurrentProgress HTTP/1.1", upstream: "uwsgi://unix:///run/zentyal-webadmin/webadmin.sock:", host: "localhost:8443", referrer: "https://localhost:8443/SaveChanges?noPopup=1&save=1&firstTime=1"
2022/10/17 01:22:50 [error] 35373#35373: *493 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.100, server: , request: "POST /SysInfo/Controller/Halt HTTP/1.1", upstream: "uwsgi://unix:///run/zentyal-webadmin/webadmin.sock:", host: "192.168.10.4:8443", referrer: "https://192.168.10.4:8443/SysInfo/View/Halt"
2022/10/17 01:43:35 [error] 2506#2506: *258 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.10.100, server: , request: "POST /SysInfo/CurrentProgress HTTP/1.1", upstream: "uwsgi://unix:///run/zentyal-webadmin/webadmin.sock:", host: "192.168.10.4:8443", referrer: "https://192.168.10.4:8443/"
`

**Comment by sydmund** [comment]
Same here. Fresh installation from iso on VM (Proxmox, 8 GB RAM, eth0 internal).


/var/log/zentyal/error.log (first line from finishing an installation, next from "SAVE CHANGES"):

```
2022/10/17 01:13:48 [error] 35373#35373: *104 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 127.0.0.1, server: , request: "POST /SysInfo/CurrentProgress HTTP/1.1", upstream: "uwsgi://unix:///run/zentyal-webadmin/webadmin.sock:", host: "localhost:8443", referrer: "https://localhost:8443/SaveChanges?noPopup=1&save=1&firstTime=1"
2022/10/17 01:22:50 [error] 35373#35373: *493 upstream prematurely closed connection while reading response header from upstream, client: 192.168.10.100, server: , request: "POST /SysInfo/Controller/Halt HTTP/1.1", upstream: "uwsgi://unix:///run/zentyal-webadmin/webadmin.sock:", host: "192.168.10.4:8443", referrer: "https://192.168.10.4:8443/SysInfo/View/Halt"
2022/10/17 01:43:35 [error] 2506#2506: *258 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 192.168.10.100, server: , request: "POST /SysInfo/CurrentProgress HTTP/1.1", upstream: "uwsgi://unix:///run/zentyal-webadmin/webadmin.sock:", host: "192.168.10.4:8443", referrer: "https://192.168.10.4:8443/
```

**Comment by himala76** [comment]
I got the same issue fresh install  VM (8gb ram) and the physical (6gb ram)computer can't backup due to unsaved status. 
<img width="378" alt="Screenshot 2022-11-22 054857" src="https://user-images.githubusercontent.com/21207347/203295360-5062a5b2-1545-4a0e-8b21-aa195379c727.png">

**Comment by jdkruzr** [comment]
same issue here on three separate recent installs.

**Comment by rubenszolt** [comment]
Confirm the problem, fresh install on 3 servers, cannot finalizing the install, it must refresh the page.
Core version 7.0.5 - no updates.

**Comment by rubencom** [comment]
> 
Thanks the solution, but I'm not install from zentyal ISO, I'm installing from zentyal repository.

**Comment by edubeltran** [comment]
same issues here....any solution for this ?

**Comment by Lumanet2012** [comment]
Hey guys we do have also the same issue but we got some additional infos :

root@mia-ad01:~# zs webadmin status
Zentyal: status module webadmin:                        [ STOPPED ]
root@mia-ad01:~# zs webadmin start
Use of uninitialized value $key in split at /usr/share/perl5/EBox/GlobalImpl.pm line 1398.
 * Restarting Zentyal module: webadmin                                                                                                                           [ OK ]
root@mia-ad01:~# zs webadmin status
Zentyal: status module webadmin:                        [ STOPPED ]
root@mia-ad01:~#

we notice all the normal logging was just fine but when we ran finally on the command line zs webadmin start we saw the issue.

**Comment by Lumanet2012** [comment]
so if I remove the .license file : 

rm /var/lib/zentyal/.license

than I get at least no longer this error... but still won't start the webadmin module 

root@mia-ad01:~# zs webadmin start
 * Restarting Zentyal module: webadmin                                                                                                                           [ OK ]
root@mia-ad01:~# zs webadmin status
Zentyal: status module webadmin:                        [ STOPPED ]
root@mia-ad01:~#

**Comment by DavidJMac** [comment]
I have exactly the same issue on a fresh install, did anyone find a solution?

**Comment by HippyCraig** [comment]
I hav the same issue with the save dialog just sitting there I have refresh the view for it close.    I’m using the community edition 

is this because it doesn’t have a cert?  What else could it be ?

**Comment by gtavargas** [comment]
Greetings,

It happened to me many times
![image](https://user-images.githubusercontent.com/78830344/233225927-98fec9da-850a-43bb-85c6-dab19a80a712.png)

and I solved it like this.
![image](https://user-images.githubusercontent.com/78830344/233226090-dae235b1-b4c4-4da5-bfc7-26fa83ab4658.png)
![image](https://user-images.githubusercontent.com/78830344/233226303-c80f9c03-7acc-4cbd-819e-365ea00daa30.png)
![image](https://user-images.githubusercontent.com/78830344/233226419-1a41c494-d736-4b3e-af2c-ca577b9167f0.png)

I hope I can help you, Have a nice day

**Comment by KerniPL** [comment]
@gtavargas 
Are you sure all changes you made are saved this method? 
In my opinion - no.

**Comment by dkyrgia** [comment]
@gtavargas It worked perfeclty! Thnx m8!

**Comment by edubeltran** [comment]
Tks its work perfectly for me!

**Comment by gabriele-v** [comment]
Any feedback about this? Facing the same issue on a new 7.0 install on Ubuntu 20.04

**Comment by sangamc** [comment]
I have the same issue. It so weird since ive been dealing with it for years and there is no rhyme or reason as to what actually causes it. One day I can install a new server from image and it works perfectly. THen a few hours later install another server on same hardware from image and the page wont save

I usually tail the log and refersh the page once I see that what ever I was saving has saved

**Comment by gokhansonmez** [comment]
I've been dealing with this problem for a very long time, so I gave up using zentyal domains.
The saddest part is that there is no support, there is no support in the forums or here. Since version 5, I download and try every update and when I see that the problem continues, I delete it with disappointment.
