### ISSUE TITLE
Issue on web interface after updating 7

### ISSUE THREAD

**Issue by killmasta93** [zentyal/zentyal#2116]
**Describe the bug**
after updating to zentyal 7 the web interface clicking on any module im getting

![image](https://user-images.githubusercontent.com/13953629/218877315-56e5447e-812c-436a-af9f-97ece726800f.png)

**To Reproduce**
1. Go to zentyal webmin
2. Click on user module

3. See error

**Expected behavior**

**Screenshots**

**Zentyal OS (please complete the following information):**
 - Version: 7
 - Version of the module which has the bug zentyal web 
 - Modules installed DNS/AD

error log
`
[crit] 2192#2192: *942 SSL_write() failed while sending response to client, client: 192.168.7.198, server: , request: "GET /data/js/jquery.jstree.js HTTP/1.1", host: "192.168.3.191:8443", referrer: "https://192.168.3.191:8443/SysInfo/ComponentNotFound"`

**Comment by djoven89** [comment]
Hi @killmasta93 ,

We received no feedback about upgrading issues, so it seems to be an isolated issue. Please, answer the following questions:

1. Did you have any issues during the upgrade?
2. Did you confirm that your Zentyal server is running on Ubuntu 20.04? `lsb_release -a`
3. Are all the zentyal packages in version **7.x**? `dpkg -l | egrep 'zen(tyal|buntu)-'`
3. Do you have any broken packages? `dpkg -l | egrep -v '^ii'`
4. Do you have any errors during a server reboot in the following log files?
   * /var/log/zentyal/zentyal.log
   * /var/log/syslog
5. Do you have any third-party software that is causing this issue?

Best regards, Daniel Joven.

**Comment by djoven89** [comment]
Hi @killmasta93 , thank you for the feedback. For the new problem you are reporting, please, create a new issue following the template. 

**NOTE:** Make sure you explain the steps to replicate the issue and provide all the important information such as if you upgraded Samba due to the Windows 10 bug, relevant configuration files, directory permissions, etc.

Best regards, Daniel Joven.
