### ISSUE TITLE
Not Working Backup and manage users LDAP after update

### ISSUE THREAD

**Issue by jeaneduardo** [zentyal/zentyal#2123]
Hello

We were unable to backup Zentyal after updating 3 servers, I cannot manage users.

Backup
1. Click System > Configuration backup
2. Description Backup
3. Click on Backup button
Outupt error: Some error has happened in Zentyal:

root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesW0Zhom.ldif failed. Error output: Command output: . Exit value: 1

Manager LDAP Users
1. Click Users And Computer > Manage

Output Error:

element not found
we're sorry
The request contains a reference to an element which does not exist
If you typed the page address manually, please check it
Maybe the element was removed and the page address is no longer valid It can also be a parameters cache error, in this case you can navigate again to the page using the left menu
If you need more help, you may want to visit Zentyal homepage for documentation and mailing lists

Screenshots

Backup
![image](https://user-images.githubusercontent.com/8227475/224137867-cd0757c9-8090-4e8e-a693-429459ee9e5d.png)

Users and Computer
![image](https://user-images.githubusercontent.com/8227475/224137683-f1d29ef8-1863-4595-8abb-52be1ac33414.png)

Zentyal OS
 - Core Version: 7.0.5
 - Ubuntu 20.04.5 LTS

**Comment by plvsouza** [comment]
With the automatic security update from SAMBA ( 2: 4.15.13 + dfsg-0ubuntu0.20.04.1 ) there has been a change that affects the Development Edition. The result is error messages such as:

> root command ldbsearch -H /var/lib/samba/private/sam.ldb -s base 'dn' --debug-stderr 2>/dev/null 1>/var/lib/zentyal/tmp/dnsZonesBTPF7h.ldif failed. 

The remedy takes place in /usr/share/perl5/EBox/Ldap.pm in lines 250 and 466:
In my $ cmd are the two entries '--debug-stderr ' to remove, these are no longer supported in the new version. 
Then it is better to restart the server.

Solution originally put by [markus.neubauer](https://forum.zentyal.org/index.php?action=profile;u=159582)

**Comment by jeaneduardo** [comment]
thank you very much

The solution worked

**Comment by Neustradamus** [comment]
@Deslak has done a PR:
- https://github.com/zentyal/zentyal/pull/2122
