### ISSUE TITLE
Update KB5028185 -> RDP Session to W11 not possible

### ISSUE THREAD

**Issue by LorText** [zentyal/zentyal#2132]
After W11 Update KB5028185 RDP Session to W11 Professional is not possible anymore. 
original failure below but german.**(1)**
It says that the authentification server is not reachable. If i uninstall this update everything works fine again.
On Zentyal Core 7.0.5 and 7.0.6 same behavior

If i deselect on remote settings in system settings authentication on network i can connect from windows to windows by rdp but from linux with xrdp to windows including this update KB502815 not.
![Screenshot 2023-07-13 103702](https://github.com/zentyal/zentyal/assets/139433444/973a7c76-d34d-4b8b-afd5-04dc55d1fe65)

**(1)**
[Window Title]
Remotedesktopverbindung

[Content]
Zur Authentifizierung konnte keine Verbindung mit einer Authentifizierungsstelle hergestellt werden. Wenn sie ein Remotedesktopgateway mit einer Smartcard verwenden, versuchen Sie, die Verbindung mithilfe eines Kennworts herzustellen. Wenden Sie sich an den Systemadministrator oder an den technischen Support, um Hilfe zu erhalten.

[^] Details ausblenden  [OK]

[Expanded Information]
Fehlercode: 0x0
Erweiterter Fehlercode: 0x0
Zeitstempel (UTC): 07/13/23 06:22:20 AM
Aktivitäts-ID: ba692b21-d58d-43e8-afaf-3f8942de0200

**To Reproduce**
W11 Update KB5028185 install
after that connection by remote 

**Zentyal OS (please complete the following information):**
 - Version: 7.0
 - Version the installed 
 - Modules installed
Antivirus  7.0.3 
Certification Authority  7.0.1  
Core  7.0.6  
DHCP Server  7.0.2  
DNS Server  7.0.2  
Domain Controller and File Sharing  7.0.3  
Firewall  7.0.0  
NTP Service  7.0.0  
Network Configuration  7.0.0  
Software Management  7.0.0  
VPN  7.0.0 

**Other OS (please complete the following information):**
 - OS: Windows 11
 - Version: 22h2 22621.1992

Thank you very much

**Comment by meiser79** [comment]
https://bugs.launchpad.net/ubuntu/+source/samba/+bug/2027716

**Comment by LorText** [comment]
yes i saw it on samba+ already. That here the bug is already fixed. But in Zenytal updates isnt included right now.
https://samba.plus/de/blog/detail/update-fuer-samba-4184-verfuegbar

**Comment by Neustradamus** [comment]
About Samba problem, it is linked to:
- https://bugzilla.samba.org/show_bug.cgi?id=15418
- https://bugs.launchpad.net/ubuntu/+source/samba/+bug/2027716
- [KB5028166](https://support.microsoft.com/en-us/topic/july-11-2023-kb5028166-os-builds-19044-3208-and-19045-3208-eab49ea6-3133-41c8-845f-a14a329c6c20)
- [KB5028228](https://support.microsoft.com/en-us/topic/july-11-2023-kb5028228-monthly-rollup-b7ee35a2-91ab-4e36-8e46-7c616d1bd4e4)
- [KB5028851](https://support.microsoft.com/en-us/topic/july-11-2023-kb5028851-cumulative-update-for-net-framework-3-5-and-4-8-1-for-windows-11-version-22h2-50ec866f-233e-4f5f-9b5b-4337b13c103c)

**Comment by dajester2013** [comment]
The patch has been posted for a while now - what's the plan for getting it integrated into Zentyal?  Zentyal 7.1 ships with 4.15, but the patch is officially in 4.16+

**Comment by LorText** [comment]
i agree. There was an update available a few days after open this topic for 4.15 but this hasnt fix the problem yet. It seems to be that the change has to come from zentyal dev team to integrate the higher version which has already fixed it for focal.

**Comment by djoven89** [comment]
Hi everyone,

Ubuntu released the fix fourteen hours ago and it is available in Zentyal 7.0. The package version is **2:4.15.13+dfsg-0ubuntu0.20.04.4 .** More information about the time when the package was released and the changes it has [here](https://launchpad.net/ubuntu/+source/samba/2:4.15.13+dfsg-0ubuntu0.20.04.4)

Thank you all for your feedback.
