### ISSUE TITLE
Install Zentyal 7.1 in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by xgonc** [zentyal/zentyal#2143]
Due to this Samba bug https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1993934, is it possible to install Zentyal 7.1 on Ubuntu 22.04 LTS?

Thanks.

**Comment by meiser79** [comment]
Just a user, but I doubt that it's possible. The next version 8.0 should be based on Ubuntu 22.04.

Did you check https://bugs.launchpad.net/ubuntu/+source/samba/+bug/1993934/comments/48?

**Comment by djoven89** [comment]
Hi @xgonc,

@meiser79  is right, Zentyal  7.1 is based on Ubuntu 20.04 as you can see [here](https://wiki.zentyal.org/wiki/Zentyal_7.1_Announcement#Highlights) and Zentyal 8.0 will be based on Ubuntu 22.04.

Before closing the ticket, the bug you mentioned was fixed and released, [here](https://github.com/zentyal/zentyal/issues/2132) you have the link.
