### ISSUE TITLE
Zentyal as additional Ad controller can't add users or edit

### ISSUE THREAD

**Issue by Baltimorepc** [zentyal/zentyal#2144]
cant add users or edit in zentyal as a additional AD controller. if i add from my main Controller which is Samba on linux 22.04 it works fine and does show in Zentyal. so something is talking

**Comment by djoven89** [comment]
Hi Baltimorepc,

I’m going to close the issue and continue in [this](https://github.com/zentyal/zentyal/issues/2075) open ticket you already answered.

**NOTE:** For future issues, please, use the default template so we can analyze the issue you get or enhancements you propose.

Best regards, Daniel Joven.
