### ISSUE TITLE
HTTP Proxy module dont start after squid update

### ISSUE THREAD

**Issue by vjmartins** [zentyal/zentyal#2145]
**Describe the bug**
After update squid to 4.1, http proxy module dont start.
Squid package version: **4.10-1ubuntu1.8**

**systemctl status squid.service** return

> ● squid.service - Squid Web Proxy Server
>      Loaded: loaded (/lib/systemd/system/squid.service; enabled; vendor preset: enabled)
>      Active: failed (Result: timeout) since Wed 2023-11-22 12:16:14 WET; 6min ago
>        Docs: man:squid(8)
>     Process: 78824 ExecStartPre=/usr/sbin/squid --foreground -z (code=exited, status=1/FAILURE)
> 
> nov 22 12:15:32 servidor squid[78824]: Squid Parent: will start 1 kids
> nov 22 12:15:32 servidor squid[78824]: Squid Parent: (squid-1) process 78928 started
> nov 22 12:15:32 servidor squid[78928]: 2023/11/22 12:15:32 kid1| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
> nov 22 12:16:14 servidor systemd[1]: squid.service: start-pre operation timed out. Terminating.
> nov 22 12:16:14 servidor squid[78824]: Squid Parent: squid-1 process 78928 exited due to signal 15 with status 0
> nov 22 12:16:14 servidor squid[78824]: Exiting due to unexpected forced shutdown
> nov 22 12:16:14 servidor squid[78824]: 2023/11/22 12:16:14| Removing PID file (/run/squid.pid)
> nov 22 12:16:14 servidor systemd[1]: squid.service: Control process exited, code=exited, status=1/FAILURE
> nov 22 12:16:14 servidor systemd[1]: squid.service: Failed with result 'timeout'.
> nov 22 12:16:14 servidor systemd[1]: Failed to start Squid Web Proxy Server.

**squid -k check** returns:
> 2023/11/22 12:17:52| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
> 2023/11/22 12:17:52| FATAL: Unable to open configuration file: /etc/squid/squid.conf: (13) Permission denied
> 2023/11/22 12:17:52| Squid Cache (Version 4.10): Terminated abnormally.

**Zentyal OS (please complete the following information):**
 - Version: 7.0.9
 - HTTP Proxy	7.0.2
 - Modules installed : Antivirus, Certification Authority, Core, DHCP Server, DNS Server, Domain Controller, Firewall, Http proxy, NTP Service, Network configuration, Software managemente, VPN

**Comment by vjmartins** [comment]
@djoven89 Any idea?

**Comment by djoven89** [comment]
Hi @vjmartins,

What configuration do you have in the Proxy module?

According to the output, the error is related to permissions:

```
2023/11/22 12:17:52| FATAL: Unable to open configuration file: /etc/squid/squid.conf: (13) Permission denied
```

Below you have the permissions I have in a working Zentyal 7.0. Check if you have the same permissions and owner:

```
## Directory
drwxr-xr-x 3 root root 4096 nov 29 13:58 /etc/squid/

## Files
drwxr-xr-x 2 root root  4096 nov 29 13:55 conf.d
-rw-r--r-- 1 root root 20892 nov 29 13:58 errorpage.css
-rw-r----- 1 root root  3280 nov 29 13:58 squid.conf
```

Also, you can try to restart the module by running `sudo zs squid restart` and then, analyze the log files:

- /var/log/zentyal/zentyal.log
- /var/log/syslog

Best regards, Daniel Joven.

**Comment by vjmartins** [comment]
**What configuration do you have in the Proxy module?**
Now, none. I uninstall the Proxy module, and now, i can't install.

**My folder/files permissions**

> **Directory**
> drwxr-xr-x   3 root       root        4096 nov 28 14:45 squid
> 
> **Files**
> drwxr-xr-x   2 root root   4096 nov 27 14:47 conf.d
> -rw-r--r--   1 root root  20892 nov 22 15:33 errorpage.css
> -rw-r-----   1 root root   9743 nov 22 15:32 squid.conf

I try to install Proxy module again, but give me a error.
I try 
> sudo dpkg --configure -a

and return
> Setcap worked! /usr/lib/squid/pinger is not suid!
> Job for squid.service failed because a timeout was exceeded.
> See "systemctl status squid.service" and "journalctl -xe" for details.
> invoke-rc.d: initscript squid, action "restart" failed.
> ● squid.service - Squid Web Proxy Server
>      Loaded: loaded (/lib/systemd/system/squid.service; enabled; vendor preset: enabled)
>      Active: failed (Result: timeout) since Wed 2023-11-29 14:19:46 WET; 5ms ago
>        Docs: man:squid(8)
>     Process: 745680 ExecStartPre=/usr/sbin/squid --foreground -z (code=exited, status=1/FAILURE)
> 
> nov 29 14:19:03 servidor squid[745680]: Squid Parent: will start 1 kids
> nov 29 14:19:03 servidor squid[745680]: Squid Parent: (squid-1) process 745728 started
> nov 29 14:19:03 servidor squid[745728]: 2023/11/29 14:19:03 kid1| WARNING: BCP 177 violation. Detected non-functional IPv6 loopback.
> nov 29 14:19:46 servidor systemd[1]: squid.service: start-pre operation timed out. Terminating.
> nov 29 14:19:46 servidor squid[745680]: Squid Parent: squid-1 process 745728 exited due to signal 15 with status 0
> nov 29 14:19:46 servidor squid[745680]: Exiting due to unexpected forced shutdown
> nov 29 14:19:46 servidor squid[745680]: 2023/11/29 14:19:46| Removing PID file (/run/squid.pid)
> nov 29 14:19:46 servidor systemd[1]: squid.service: Control process exited, code=exited, status=1/FAILURE
> nov 29 14:19:46 servidor systemd[1]: squid.service: Failed with result 'timeout'.
> nov 29 14:19:46 servidor systemd[1]: Failed to start Squid Web Proxy Server.
> dpkg: erro ao processar o pacote squid (--configure):
>  o subprocesso instalado, do pacote squid, o script post-installation retornou erro do status de saída 1
> dpkg: problemas com dependências impedem a configuração de zentyal-squid:
>  zentyal-squid depende de squid; no entanto:
>  O pacote squid ainda não está configurado.
> 
> dpkg: erro ao processar o pacote zentyal-squid (--configure):
>  problemas com dependências - a deixar por configurar
> Foram encontrados erros enquanto processava:
>  squid
>  zentyal-squid

**Comment by djoven89** [comment]
Hi @vjmartins ,

How many broken packages do you have? And what is the name of those packages? Are Squid and E2guardian installed?

```bash
dpkg -l | egrep -v '^ii'

dpkg -l | egrep 'squid|e2guardian'
```

According to your output, you are getting a timeout. You might check the following:

1. Ensure Squid and E2guardian services are stopped:
    
    ```bash
    sudo systemctl stop squid e2guardian
    sudo systemctl status squid e2guardian
    ```
    
2. Confirm that there is not any Squid or E2guardian process running:
    
    ```bash
    sudo ps -ef | egrep 'squid|e2guardian'
    ```
    
        Kill the process if there is any.
    
3. Check if there is any lock process that might be causing the issue - pay special attention to Zentyal, EBox o Squid processes -:
    
    ```bash
    lslocks
    ```
    
        Kill the process if there is any.
    
4. Ensure the port you used for the module is not in use:
    
    ```bash
    ss -tunpl | grep ':your-port-name'
    ```
    

In case the above will not help you, please, send us the following Squid configuration:

```bash
sudo egrep -v '^($|#)' /etc/squid/squid.conf

sudo cat /etc/squid/conf.d/debian.conf
```

**NOTA:** Make sure there is no private information.

I hope this helps you to identify the issue.

Best regards, Daniel Joven.

**Comment by Neustradamus** [comment]
@vjmartins: Any news on this ticket?

**Comment by Neustradamus** [comment]
@vjmartins: Do not closed an unsolved ticket...
