### ISSUE TITLE
release-upgrade script raises error checking IDS repository

### ISSUE THREAD

**Issue by ciriolomario** [zentyal/zentyal#2146]
During the release upgrade from 7.0.9 to 7.1 the system is raising an error in the step of checking the IPS repository.

The public key for IDS is not found and the script stops

OUTPUT: " The IDS key could not download correctly..."

Here is the IPS_KEY_ID='D7F87B2966EB736F'

P.S.: All the pending updates are done. There is no known issue in the connectivity to internet, everything seems to be ok.

Any idea about how to debug this error?
Thanks a lot

**Comment by djoven89** [comment]
Hi,

I have tested the script and it worked correctly. Perhaps there was a temporal issue with the key server. You can run the following commands to confirm that you can download the key now:

```bash
sudo gpg --keyserver [keyserver.ubuntu.com](http://keyserver.ubuntu.com/) --recv-keys D7F87B2966EB736F
sudo gpg --export D7F87B2966EB736F > /etc/apt/trusted.gpg.d/suricata.gpg
sudo gpg --batch --yes --delete-keys D7F87B2966EB736F
```

**NOTE:** The package `gnupg` must be installed to run the above commands.

Best regards, Daniel Joven.

**Comment by djoven89** [comment]
Hi,

Let’s try another approach:

1. Download the `suricata.gpg` key from [this link](https://we.tl/t-KXjWn6ZAfc).
2. Upload it to your Zentyal server to the path `/etc/apt/trusted.gpg.d/suricata.gpg`
3. Comment the lines from **[357 to 359](https://github.com/zentyal/zentyal/blob/549434a667546bf67e85e4ecac2982a44f70ba77/main/core/src/scripts/release-upgrade#L357)** in the script `/usr/share/zentyal/release-upgrade`
4. Make sure your server is up-to-date.
5. Finally, run the script again:
    
    ```bash
    sudo bash -x /usr/share/zentyal/release-upgrade
    ```
    

**NOTE:** Ensure you have a backup, just in case you need to do a rollback.

Best regards, Daniel Joven.

**Comment by Neustradamus** [comment]
@ciriolomario: Any news on this ticket?

**Comment by ciriolomario** [comment]
Hi,

first of all, sorry for the delay of this feedback.

I tried the approach given by djoven89

It improved a little bit the upgrade process but, unfortunately, it did not solve the issue.

The release-upgrade script run but the prompt said that the file suricata.gpg was not a valid format.
Nevertheless, with some more changes in the release-upgrade script, I managed to complete the upgrade, which apparently was OK.

When I rebooted the server, the initial messages were all OK but at the end I discovered a blocking issue in the web UI: something went wrong with python, and the user interface was completely unusable. 

Due to the fact that I'm not sure this is related to the original problem, I suggest to close this ticket.

I will do more tentatives of upgrade from 7.0.9 to 7.1 in the next weeks and I'm coming back with more precise log information.

Thank you very much for your support.

Best regards.

MC

**Comment by djoven89** [comment]
Hi,

We have no news about any issues with the update from 7.0 and 7.1, in fact, all we have done so far has worked as expected. So we honestly believe this is just an isolated issue.
As you suggested, we are going to close the ticket, If you still have issues with this process in the future, you should create a post in the [forum](https://forum.zentyal.org/) or contact Zentyal’s sales department and explain the situation.

Best regards, Daniel Joven.
