### ISSUE TITLE
Website Development Edition Download links to old version

### ISSUE THREAD

**Issue by GTez** [zentyal/zentyal#2149]
**Describe the bug**
On the mail website: https://zentyal.com/community/ the download link links to https://download02.public.zentyal.com/zentyal-7.0-development-amd64.iso. Instead it should link to: https://download02.public.zentyal.com/zentyal-7.1-development-amd64.iso

**To Reproduce**
1. Go to https://zentyal.com/community/
2. Click on[Download Zentyal Development Edition](https://download02.public.zentyal.com/zentyal-7.0-development-amd64.iso) 
3. See incorrect file downloading 

**Expected behavior**
The latest edition should download

**Comment by Neustradamus** [comment]
@GTez: Same on Sourceforge:
- https://sourceforge.net/projects/zentyal/

**Comment by djoven89** [comment]
Hi @GTez,

Thank you for informing us of that issue, and our apologies for the error. The link has been corrected and you can now download the latest Development version 7.1.

Best regards, Daniel Joven.
