### ISSUE TITLE
Zentyal 8.0 and linux 22.04 install error the network interface naming is not using eth

### ISSUE THREAD

**Issue by Baltimorepc** [zentyal/zentyal#2153]
Zentyal 8.0 and linux 22.04 install error the network interface naming is not using eth

the network interface naming is not using 'eth'. you can ommit this by changing to false the variable 'old_nic_naming'

i have tried everything and even tried searching to add that variable but still can not install

**Comment by djoven89** [comment]
Hi Baltimorepc,

What errors did you get? Can you run the script in debug mode and paste here the output?

```bash
bash -x zentyal_installer_8.0.sh
```

**Comment by Baltimorepc** [comment]
Since the Ethernet interface is ens not ent 
It was throwing that error I’ll I’ll run that command as all. As I get home 
I did a work around and renamed the interface to ent which did work but it’s only temp I couldn’t get it to stay renamed 

And it also won’t connect to my samba domain I was trying  set this up as a secondary ad server and I have a samba Active Directory running on a Linux 22.04 I had this on the old 20.04 and had the same samba issues so I wanted to try a new one and now I have both issues I could really use some help is it different connection central to a samba AD I followed so many videos for creating my samba ad and so far it seems to work but  for zenthal I couldn’t get it to work 

Sent from Yahoo Mail for iPhone


On Monday, March 11, 2024, 6:14 AM, Daniel Joven ***@***.***> wrote:




Hi Baltimorepc,

What errors did you get? Can you run the script in debug mode and paste here the output?
bash -x zentyal_installer_8.0.sh

**Comment by Baltimorepc** [comment]
![image](https://github.com/zentyal/zentyal/assets/141858534/d8f8dffc-270c-4344-8f33-fa3252c56352)

**Comment by Baltimorepc** [comment]
then running it with ur command 
![image](https://github.com/zentyal/zentyal/assets/141858534/cda8fda5-66b3-4840-97d9-132692e1f1fd)

**Comment by Baltimorepc** [comment]
i can post the full shot if you need but they were all green as well just with all the info

**Comment by Baltimorepc** [comment]
i could not figure out how to change the variable to false. When i ran those commands i did get it to work but then updates wouldnt work so i reverted back the snapshot to before i made the changes so i can find a actual fix

**Comment by Baltimorepc** [comment]
when trying to run the 4 commands i get the following error

 sed -i 's/#GRUB_HIDDEN_TIMEOUT=0/GRUB_HIDDEN_TIMEOUT=0/' /target/etc/default/grub
sed: can't read /target/etc/default/grub: No such file or directory

**Comment by Baltimorepc** [comment]
Also another thing that you should be aware of is Since linux is using phase updates now, zentyal also throws an error if there are updates pending even when there phase updates zentyal wont install so since there held back and havent fully phased out

**Comment by Baltimorepc** [comment]
I figured out how tog eat the other method to work but when I try to add zentyal a additional domain controller after a while it fails and says error samba still haven’t been able to get zentyak to connect to my samba Active Directory domain 


Sent from Yahoo Mail for iPhone


On Wednesday, March 13, 2024, 5:37 AM, Daniel Joven ***@***.***> wrote:




Hi @Baltimorepc,

To change the mentioned variable to false you just need to edit the script and change this line to OLD_NIC_NAMING=false.

Regarding the suggested commands, the path of the first command is incorrect, instead of /target/etc/default/grub must be /etc/default/grub, and the rest of the commands are right.

About the updates, I am sorry but I do not understand what you mean. Can you provide me with more details and an example if possible?

Best regards, Daniel Joven.

**Comment by Baltimorepc** [comment]
Thank you. Let me see if i can get you some more info and i will get back to you

**Comment by Baltimorepc** [comment]
When i try to join a Samba domain running 22.04 as an additional Domain Controller i keep getting this error.
![image](https://github.com/zentyal/zentyal/assets/141858534/5a2e5f69-b173-4c85-8dcb-60ffd5d88df6)

**Comment by Baltimorepc** [comment]
i have the log but i had issues and had to manually set up some settings but i can paste the bottom once i change some things for security

**Comment by Baltimorepc** [comment]
HEre is the bottom last part if you need more let me know 

Main Samaba AD Domain1




2024/03/14 00:39:53 INFO> Provision.pm:1289 EBox::Samba::Provision::provisionADC - Joining to domain 'domain1.local' as DC
2024/03/14 00:39:53 ERROR> Sudo.pm:240 EBox::Sudo::_rootError - root command set -e
cp /etc/resolvconf/interface-order /var/lib/zentyal/tmp/resolvbMnuL2
echo zentyal.temp > /etc/resolvconf/interface-order
echo 'search Domain1.local
nameserver domain1 ip address' | resolvconf -a zentyal.temp failed.
Error output: cp: cannot stat '/etc/resolvconf/interface-order': No such file or directory

Command output: .
Exit value: 1 at root command set -e
cp /etc/resolvconf/interface-order /var/lib/zentyal/tmp/resolvbMnuL2
echo zentyal.temp > /etc/resolvconf/interface-order
echo 'search domain1.local
nameserver domain1 ip address' | resolvconf -a zentyal.temp failed.
Error output: cp: cannot stat '/etc/resolvconf/interface-order': No such file or directory

**Comment by djoven89** [comment]
Hi @Baltimorepc ,

This error is different from the bug topic, could you please create a new issue and post there the most relevant part of the log file and also, information on the environment you are trying to set up, in your case, the version of the DC you are trying to join, the version of the ADC, etc. We need to know how to reproduce the issue to fix it.

Regarding this bug issue, we are going to tag it as 'roadmap' because we have to fix the NIC naming message.

Thank you.

**Comment by Baltimorepc** [comment]
I created one for this issue when I first tried zentyal last year and never got it to work and no one ever replied but yes but it’s possible I putnitnon the wrong site I’ll create a new one as soon as I amAble I’ve always got this issue trying to join my samba domain to zentyal so zentya couldBe an additional domain controller but always got that samba error message 


Sent from Yahoo Mail for iPhone


On Friday, March 15, 2024, 8:31 AM, Daniel Joven ***@***.***> wrote:




Hi @Baltimorepc ,

This error is different from the bug topic, could you please create a new issue and post there the most relevant part of the log file and also, information on the environment you are trying to set up, in your case, the version of the DC you are trying to join, the version of the ADC, etc. We need to know how to reproduce the issue to fix it.

Regarding this bug issue, we are going to tag it as 'roadmap' because we have to fix the NIC naming message.

Thank you.

**Comment by djoven89** [comment]
Hi @Baltimorepc ,

We have fixed the typo in [this](https://github.com/zentyal/zentyal/commit/47c85296b3ff81e4a279e4f50b98b483fa20319b) commit.

Thank you again for reporting the issue.
