### ISSUE TITLE
System Load - Web Interface - Core Version 8.0.0

### ISSUE THREAD

**Issue by trvaa** [zentyal/zentyal#2154]
A minor point for correction - non urgent.

The Web Interface is showing the System Load to 11 decimal places.

**Comment by djoven89** [comment]
Hi @trvaa 

We have fixed this issue in [this commit](https://github.com/zentyal/zentyal/commit/eeed7535452feb3e60b3a4d4b407a23e43fe00bc) and we have released the package `zentyal-core 8.0.2` that contains the fix.

Thank you for reporting the bug.

Best regards, Daniel Joven.
