### ISSUE TITLE
Broken packages after 8.0 upgrade

### ISSUE THREAD

**Issue by artitcf** [zentyal/zentyal#2159]
**Describe the bug**
Before update a did a pre-check of 4 zentyal 7.1 installations (latest version) rebooted them and did the pre-check again. No errors found in core, broken packages, mysql and samba ad. After the upgrade i get this message:

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
9 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up zentyal-core (8.0.0) ...
Synchronizing state of apparmor.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apparmor
sed: can't read /etc/apt/apt.conf.d/20auto-upgrades: No such file or directory
dpkg: error processing package zentyal-core (--configure):
 installed zentyal-core package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 zentyal-core
E: Sub-process /usr/bin/dpkg returned an error code (1)

This message is identical on all upgrades of the 4 servers. 

If I do a dpkg -l |egrep -v '^ii|rc' | awk '{if(NR>5)print}'. i get the following: 

iU  zentyal-ca                             8.0.0                                   all          Zentyal - Certification Authority
iF  zentyal-core                           8.0.0                                   all          Zentyal - Core
iU  zentyal-dns                            8.0.0                                   all          Zentyal - DNS Server
iU  zentyal-firewall                       8.0.0                                   all          Zentyal - Firewall
iU  zentyal-network                        8.0.2                                   all          Zentyal - Network Configuration
iU  zentyal-ntp                            8.0.0                                   all          Zentyal - NTP Service
iU  zentyal-samba                          8.0.0                                   all          Zentyal - Domain Controller and File Sharing
iU  zentyal-software                       8.0.0                                   all          Zentyal - Software Management

**To Reproduce**
1. open terminal and do a pre-check on 7.1 
2. if everything is Ok do a upgrade via the upgrade-button in the GUI
3. Wait until everything is finished and reboot the server

**Expected behavior**
U fully upgraded server without errors.

**Screenshots**
cant be attached if necessary 

**Zentyal OS (please complete the following information):**
 - Version: 7.1 to 8.0
 - all 7.1
 - Modules installed ca, core, dns, firewall, network, ntp, antivirus, samba, software

**Other OS (please complete the following information):**
 - Ubintu 20.0.4 LTS to 22LTS

**Additional context**
Had this for all 4 servers. "can't read /etc/apt/apt.conf.d/20auto-upgrades: No such file or directory" 
Typical repairs sudo dpkg --configure --force-confdef -a etc. not working.

**Comment by artitcf** [comment]
I added 20auto-upgrades and 50unattended-upgrades and now I'm stuck that apt would first configure zentyal-core before installing the addition needed package unattended-upgrades, which is currently missing to go on to correct the installation. Error message now is:

0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
11 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Setting up zentyal-core (8.0.0) ...
Synchronizing state of apparmor.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable apparmor
Failed to disable unit: Unit file unattended-upgrades.service does not exist.
dpkg: error processing package zentyal-core (--configure):
 installed zentyal-core package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 zentyal-core
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by trvaa** [comment]
Also see example on forum https://forum.zentyal.org/index.php/topic,35671.0.html

**Comment by madest18** [comment]
I have exactly the same error

**Comment by artitcf** [comment]
**Ok, I have found a way to fix this issue.** 

1. rename the dpkg status file and make an new one: 
   "sudo mv /var/lib/dpkg/status /var/lib/dpkg/status.org"
   "touch /var/lib/dpkg/status"

2. update the system via commandline:
    "sudo apt update"

3. create the 20auto-upgrades file:
    "sudo nano /etc/apt/apt.conf.d/20auto-upgrades"

4. enter the following lines into the file and save:
      APT::Periodic::Update-Package-List "0";
      APT::Periodic::Unattended-Upgrade "0";

5. move the old dpkg status file back
    "sudo mv /var/lib/dpkg/status /var/lib/dpgk/status.new"
    "mv /var/lib/dpkg/status.org /var/lib/dpgk/status" 

6. fix the installation:
    "sudo apt install -f" 

That should fix your installation and repair all packages. If you still have issues with the Antivirus, just disable the module and enable it again. 

This helped fixing my problem and I'm running 8.0 without any issue now. 

Hope this helps. 

Chris
