### ISSUE TITLE
Restoration of Backup Fails Due to Missing Dependency

### ISSUE THREAD

**Issue by orajab** [zentyal/zentyal#2160]
Description:

Upon configuring Zentyal v8 as a standalone domain server with enabled modules including Domain Controller, DNS, DHCP, Firewall, Certificate Authority, and Intrusion Prevention, and subsequently making configurations to DHCP and Firewall, users may encounter an issue during the restoration of a backup file.

When attempting to restore a backup file created under the aforementioned configuration, an error occurs with the following message:

"root command tar jxfp /var/lib/zentyal/tmp//backup.brcZCu/eboxbackup/samba.bak/bind-dns.tar.bz2 -C /var/lib/samba failed. Error output: tar (child): bzip2: Cannot exec: No such file or directory tar (child): Error is not recoverable: exiting now tar: Child returned status 2 tar: Error is not recoverable: exiting now Command output: . Exit value: 2"

This error indicates a failure in executing the tar command due to the absence of the bzip2 utility, which is necessary for decompressing the backup file. As a result, the restoration process fails, preventing users from successfully restoring their server configuration.

Workaround:
To address this issue, users can manually install the bzip2 utility via SSH by running the following command:
`sudo apt-get install bzip2
`
Once the bzip2 utility is installed, users can attempt to restore the backup file again, which should complete successfully.

**To Reproduce**
1-Configure Zentyal v8 as a standalone domain server.
2-Enable the following modules: Domain Controller, DNS, DHCP, Firewall, Certificate Authority, and Intrusion Prevention.
3-Make configurations to DHCP and Firewall, configure CA.
4-Create a backup file.
5-Wipe the server and start over.
6-Enable the same modules and define the same domain name.
7-Update the system components.
8-Attempt to restore the backup file.
9- Encounter the following error:
"root command tar jxfp /var/lib/zentyal/tmp//backup.brcZCu/eboxbackup/samba.bak/bind-dns.tar.bz2 -C /var/lib/samba failed. Error output: tar (child): bzip2: Cannot exec: No such file or directory tar (child): Error is not recoverable: exiting now tar: Child returned status 2 tar: Error is not recoverable: exiting now Command output: . Exit value: 2"

**Expected behavior**
The restoration of the backup file should proceed without errors, allowing the server configuration to be successfully restored to its previous state.

**Screenshots**

**Zentyal OS (please complete the following information):**
 - Version: Zentyal v8.0
 - Version of the module with the bug: Configuration Backup
 -  Modules installed: Domain Controller, DNS, DHCP, Firewall, Certificate Authority, Intrusion Prevention

**Comment by djoven89** [comment]
Hi @orajab ,

We were able to reproduce the issue. As soon as possible we will release the fix.

Thank you for reporting the issue.

Best regards, Daniel Joven.

**Comment by djoven89** [comment]
Hi @orajab ,

We have fixed this issue in [this commit](https://github.com/zentyal/zentyal/commit/eeed7535452feb3e60b3a4d4b407a23e43fe00bc) and we have released the package `zentyal-core 8.0.2` that contains the fix.

Thank you for reporting the bug.

Best regards, Daniel Joven.
