### ISSUE TITLE
Upgrade to 8.0 not blocked due to virt interfaces.

### ISSUE THREAD

**Issue by jrtaylor71** [zentyal/zentyal#2164]
Upgraded from 7.1 to 8.0 and virt interfaces are now stuck in the configuration. Need info on how to remove stuck virt interface. See link below.

https://forum.zentyal.org/index.php/topic,35680.0.html

Should also add code to block upgrade to 8.0 to prevent this from happening.

**Comment by djoven89** [comment]
Hi @jrtaylor71 ,

I have updated the post you mentioned, please, check it out and if the issue persists, update the post.

Regarding the prevention, we added [this section](https://doc.zentyal.org/en/upgrade.html#virtual-interfaces) in the documentation, although, if a new version of the script is released, probably we will add a check, thank you for the suggestion.

Best regards, Daniel Joven.

**Comment by jrtaylor71** [comment]
Manually deleting entries does not solve the problem. File /etc/netplan/netplan.yaml is created from information stored somewhere else and that is where it needs to be removed.

**Comment by djoven89** [comment]
Hi @jrtaylor71 ,

We will create a conditional that blocks the upgrade in case a virtual interface is set to avoid this issue for other people.

Regarding how to fix it, we have updated the issue #2167

**Comment by djoven89** [comment]
[This function](https://github.com/zentyal/zentyal/blob/7.1/main/core/src/scripts/release-upgrade#L102) was added to the script to avoid this issue. Also, we created a [new section](https://doc.zentyal.org/en/upgrade.html#virtual-interfaces) in the documentation,
