### ISSUE TITLE
Zentyal upgrade from 7.1.2 to 8 failed during mysqldump

### ISSUE THREAD

**Issue by Yoda68** [zentyal/zentyal#2166]
**Describe the bug**
got the following error:
22-06-2024 16:03:50 ERROR: Zentyal upgrade FAILED. Could not export Sogo database, full log at /var/log/zentyal/upgrade.log

**To Reproduce**
no clue

**Expected behavior**
mysql should work

**Screenshots**
-

**Zentyal OS (please complete the following information):**
 - Version: 7.1.2
 - Version of the module which has the bug [e.g. zentyal-dns-5.0.3] N/A
 - Modules installed [e.g. DNS, DC, Jabber]

**Other OS (please complete the following information):**
 - OS: ubuntu 20.04  on the way to 22.04 
 - Version: [e.g. build 18363]

**Additional context**
Error occured during release upgrade  - the following mysql command was failing during the upgrade process:
`mysqldump -u root -p<password> sogo`

Messages:
> mysqldump: [Warning] Using a password on the command line interface can be insecure.
> mysqldump: Got error: 1045: Access denied for user 'root'@'localhost' (using password: YES) when trying to connect
    
solution was to change the command in the upgrade script to:
`mysqldump -u root -p<password> -h 127.0.0.1 sogo`

and after commenting the already taken steps in the upgrade script and restarted it:
voila it finished successfully

**Comment by djoven89** [comment]
Hi @Yoda68,

What can you tell me about your MySQL service? Did you tune/modify it in any way? Do you use this service for other purposes?

Also, was your Zentyal 7.1 upgraded before? If so, what was the version of Zentyal you installed at the beginning?

Best regards, Daniel Joven.
