### ISSUE TITLE
Unable to remove virtual interfaces after upgrading to 8.0

### ISSUE THREAD

**Issue by jrtaylor71** [zentyal/zentyal#2167]
Virtual interfaces not removed after upgrade 8.0.

See bug https://github.com/zentyal/zentyal/issues/2164 
and
https://forum.zentyal.org/index.php/topic,35680.0.html

Manually deleting entries does not solve the problem. File /etc/netplan/netplan.yaml is created from information stored somewhere else and that is where it needs to be removed.

**Comment by djoven89** [comment]
Hi @jrtaylor71 ,

The reason why you still have the virtual interface configuration in Netplan is that it is still set in Redis, which is the database that uses Zentyal to store the configuration that is set through the administrator panel. So, you must remove the configuration there. Below you have an example:

1. Open a Redis connection for the network module:
    
    ```bash
    sudo /usr/share/zentyal/redisvi network
    ```
    
2. Find the key `network/conf/interfaces` :
    
    ```json
    network/conf/interfaces: {
       "eth0" : {
          "name" : "eth0",
          "external" : 1,
          "method" : "dhcp"
       },
       "eth2" : {
          "netmask" : "255.255.255.0",
          "virtual" : {
             "database" : {
                "netmask" : "255.255.255.0",
                "name" : "database",
                "address" : "192.168.171.1"
             },
             "webservers" : {
                "netmask" : "255.255.255.0",
                "address" : "192.168.172.1",
                "name" : "webservers"
             }
          },
          "method" : "static",
          "name" : "eth2",
          "external" : 0,
          "address" : "192.168.170.1"
       },
       "eth1" : {
          "name" : "eth1",
          "method" : "static",
          "external" : 0,
          "address" : "192.168.56.31",
          "netmask" : "255.255.255.0",
          "virtual" : {
             "remote" : {
                "name" : "remote",
                "address" : "192.168.59.31",
                "netmask" : "255.255.255.0"
             }
          }
       }
    }
    ```
    
    As you can see, I added three virtual interfaces: **remote** for **eth1**, **webservers,** and **database** for **eth2.**
    
3. Remove the `virtual` keys so the configuration looks like this:
    
    ```json
    network/conf/interfaces: {
       "eth0" : {
          "name" : "eth0",
          "external" : 1,
          "method" : "dhcp"
       },
       "eth2" : {
          "netmask" : "255.255.255.0",
          "method" : "static",
          "name" : "eth2",
          "external" : 0,
          "address" : "192.168.170.1"
       },
       "eth1" : {
          "name" : "eth1",
          "method" : "static",
          "external" : 0,
          "address" : "192.168.56.31",
          "netmask" : "255.255.255.0"
       }
    }
    ```
    
    **NOTE:** If you had a syntax issue when removing, you will get the following message after saving: `Import of modifications failed, restoring the original...`
    
4. Do the same for `network/ro/conf/interfaces`
    
    ```json
    network/ro/interfaces: {
       "eth2" : {
          "netmask" : "255.255.255.0",
          "address" : "192.168.170.1",
          "method" : "static",
          "name" : "eth2",
          "virtual" : {
             "database" : {
                "address" : "192.168.171.1",
                "netmask" : "255.255.255.0",
                "name" : "database"
             },
             "webservers" : {
                "netmask" : "255.255.255.0",
                "address" : "192.168.172.1",
                "name" : "webservers"
             }
          },
          "external" : 0
       },
       "eth1" : {
          "address" : "192.168.56.31",
          "netmask" : "255.255.255.0",
          "external" : 0,
          "virtual" : {
             "remote" : {
                "name" : "remote",
                "netmask" : "255.255.255.0",
                "address" : "192.168.59.31"
             }
          },
          "method" : "static",
          "name" : "eth1"
       },
       "eth0" : {
          "name" : "eth0",
          "method" : "dhcp",
          "external" : 1
       }
    }
    
    ```
    
5. Once you have done the above, restart the network module so the `netplan.yaml` can be generated again.
    
    ```bash
    sudo zs network restart
    ```
    
6. Check the network configuration:
    
    ```bash
    sudo cat /etc/netplan/netplan.yaml
    
    ip -4 a
    ip r s
    ```
    

Let me know the results.

**Comment by jrtaylor71** [comment]
`root@gateway:~# /usr/share/zentyal/redisvi network
399,410d398
<       "virtual" : {
<          "eth02" : {
<             "name" : "eth02",
<             "netmask" : "255.255.255.0",
<             "address" : "10.1.10.1"
<          },
<          "eth01" : {
<             "name" : "eth01",
<             "netmask" : "255.255.255.0",
<             "address" : "10.1.10.254"
<          }
<       },
421,427d408
<       "virtual" : {
<          "eth11" : {
<             "netmask" : "255.255.255.0",
<             "address" : "192.168.183.1",
<             "name" : "eth11"
<          }
<       },
root@gateway:~# zs network restart
 * Restarting Zentyal module: network               `
The virtual interfaces are now gone after the restart. I am good with the formating as I can do some perl and C programing.

**Comment by djoven89** [comment]
Hi @jrtaylor71 , I'm glad that the issue is fixed.
