### ISSUE TITLE
zentyal web admin page not loading

### ISSUE THREAD

**Issue by munagala05** [zentyal/zentyal#2170]
Dear Sir,

zentyal web admin page not loading and i am getting the error 504 Gateway Time-out nginx.

Please help me for resolve the issue.

**Comment by juliocp1976** [comment]
I had this problem 1 month ago and today again on 4 servers with version 7.
And strangely 2 to 3 days later it started working again. Nothing to do. 
I'm also waiting for a solution so this doesn't happen again.

**Comment by gallogabor** [comment]
I did some investigation about the information in #2112, and the assumption appears to be true, the inaccessibility of update.zentyal.org causes the webadmin hanging and getting error 504 from nginx.

If I comment out the new version checking in the sources, then the webadmin Dashboard going to work again, without problems.

The file, which contains this version check is in `/usr/share/perl5/EBox/Dashboard/CGI/Index.pm`
In this file (as of Zentyal 7.1.2), starting at line 267, there is a function `sub _getNewVersionFromCloud`, which downloads a file from `update.zentyal.org` with `wget` (system call). wget normally timeouts in 900 secs, this is far too more than nginx waits for uWSGI answer. Unfortunately, if I set a much sorter timeout for wget (`-T 15`), it does not help. But if I comment out the relevant lines completely (273-278 for Zentyal 7.1.2), then this check it will be breasted, and the webadmin start working.

Of course, after modifying the file, the webadmin uwsgi process need to be killed (it is likely in a stuck state already), then a `zs webadmin restart` needed, too.

**Comment by djoven89** [comment]
Hi,

As [this](https://forum.zentyal.org/index.php/topic,35714.msg115953.html#msg115953) post explained, it was a temporal issue with [update.zentyal.org](http://update.zentyal.org/) that caused the problem.

Also, as Gallogabor explained, Zentyal 8.0 was not affected by [this](https://github.com/zentyal/zentyal/commit/da6fcd411e3a3acea43d8581eb972f3ba901556d#diff-f2da1cfc0ddd16974080efa028f11a9c2c83db2d36b364d89fabc8f70e797da0) implementation.

Sorry for the inconvenience.

**Comment by Kevinsky86** [comment]
> Hi,
> 
> As [this](https://forum.zentyal.org/index.php/topic,35714.msg115953.html#msg115953) post explained, it was a temporal issue with [update.zentyal.org](http://update.zentyal.org/) that caused the problem.
> 
> Also, as Gallogabor explained, Zentyal 8.0 was not affected by [this](https://github.com/zentyal/zentyal/commit/da6fcd411e3a3acea43d8581eb972f3ba901556d#diff-f2da1cfc0ddd16974080efa028f11a9c2c83db2d36b364d89fabc8f70e797da0) implementation.
> 
> Sorry for the inconvenience.

This seems to be an issue once more right now?

**Comment by gallogabor** [comment]
> This seems to be an issue once more right now?

This will be a problem on 6.x and 7.x installations whenever the `update.zentyal.org` website unaccessible.

The permament fix is what I mentioned in [my previous post](https://github.com/zentyal/zentyal/issues/2170#issuecomment-2240007438). That solution implemented in 8.x codebase and can be used on existing 6.x and 7.x installations by modifying the above mentioned `Index.pm` file
