### ISSUE TITLE
[7.x] [CRITICAL] obsoleted configuration option 'dnssec-enable' prevents BIND from starting

### ISSUE THREAD

**Issue by loxK** [zentyal/zentyal#2173]
Zentyal boxes received a new `BIND` version (9.16.48-0ubuntu0.20.04.1) that doesn't anymore support the `dnssec-enable` option. That leads in `BIND`, and also all other services that depend on it, not working (webadmin, samba, email etc.) :

```
juil. 24 10:42:35 zentyal named[2670]: loading configuration from '/etc/bind/named.conf'
juil. 24 10:42:35 zentyal named[2670]: /etc/bind/named.conf.options:19: option 'dnssec-enable' no longer exists
juil. 24 10:42:35 zentyal named[2670]: loading configuration: failure
juil. 24 10:42:35 zentyal named[2670]: exiting (due to fatal error)
```

[Release notes of BIND 9.16.0](https://downloads.isc.org/isc/bind9/9.16.0/RELEASE-NOTES-bind-9.16.0.html) : 

> 
> Removed Features
> 
> The dnssec-enable option has been obsoleted and no longer has any effect. DNSSEC responses are always enabled if signatures and other DNSSEC data are present. [GL #866]

**Zentyal OS:**
 - Version: 7.1.2

**Fix/Workaround**

In order to fix the issue, while waiting for the Zentyal team to fix it in their package :

Make a copy of the stub :

```
sudo mkdir -p /etc/zentyal/stubs/dns
sudo cp /usr/share/zentyal/stubs/dns/named.conf.options.mas /etc/zentyal/stubs/dns
```

Edit the file and replace
```
// DNSSEC configuration
dnssec-enable yes;
dnssec-validation yes;
```

With (as per Zentyal 8.0 configuration) :
```
dnssec-validation auto;
```

Restart DNS service :
```
sudo zs dns restart
```

It should be enough. If not, restart all the Zentyal services :
```
sudo zs restart
```

**Comment by HaraldR42** [comment]
Same here, might affect lots of installations. CloudStrike in small ;-)
Thanks for the fix.

**Comment by FoekevV** [comment]
Just to be 100% sure
I've edited /usr/share/zentyal/stubs/dns/named.conf.options.mas

to 
`<%args>
  @forwarders
  $keytabPath => undef
  @intnet
</%args>

options {
%   if (EBox::Config::boolean('sortlist')) {
        sortlist {
%           foreach my $intnet (@intnet) {
                <% $intnet %>;
%           }
        };
%   }
    directory "/var/cache/bind";

    // If there is a firewall between you and nameservers you want
    // to talk to, you might need to uncomment the query-source
    // directive below.  Previous versions of BIND always asked
    // questions using port 53, but BIND 8.1 and later use an unprivileged
    // port by default.

    //query-source address * port 53;
    //transfer-source * port 53;
    //notify-source * port 53;

    // DNSSEC configuration
    dnssec-enable yes;    
    dnssec-validation auto;

%   if ( @forwarders > 0 ) {
        // If your ISP provided one or more IP addresses for stable
        // nameservers, you probably want to use them as forwarders.
        forward first;
        forwarders {
%           foreach my $forwarder (@forwarders) {
                <% $forwarder %>;
%           }
        };
%   }

%   if (defined $keytabPath) {
        tkey-gssapi-keytab "<% $keytabPath %>";
%   }

    auth-nxdomain no;    # conform to RFC1035

    allow-query { any; };
    allow-recursion { trusted; };
    allow-query-cache { trusted; };
    allow-transfer { internal-local-nets; };
};

logging { category lame-servers { null; }; };
`
But I was not able to restart the services.
I've also tried without the "dnssec-enable yes;   " part

**Comment by BerT666** [comment]
Copy & editing of the ".mas file" works like a charm ;-)

You have to place the edited stub in /etc/zentyal/stubs/(...) !
@FoekevV: The stub files under /usr/share/zentyal/stubs/ are *only* templates and are not used ;-) ==> copy to (...) and edit ;-)

**Comment by djoven89** [comment]
Hi,

We have confirmed the bug in Zentyal 7.0 and 7.1, both versions use the parameter `dnssec-enable` which is no longer available since this night as @loxK explained perfectly.

At this moment, we have published the fix [here](https://github.com/zentyal/zentyal/commit/ec1a37d91efa2cd78ac336c6a84750d5eb00fd8f) for Zentyal 7.1 and released the package [zentyal-dns-7.1.1](https://packages.zentyal.org/zentyal/pool/main/z/zentyal-dns/zentyal-dns_7.1.1_all.deb). 

Regarding applying the fix; unfortunately, this bug affected the DNS resolution, so it arrises two issues:

1. The Zentyal Admin Interface (Webadmin) cannot reach the domain [update.zentyal.org](http://update.zentyal.org/) and because of the lack of this [fix](https://github.com/zentyal/zentyal/commit/da6fcd411e3a3acea43d8581eb972f3ba901556d#diff-f2da1cfc0ddd16974080efa028f11a9c2c83db2d36b364d89fabc8f70e797da0) applied in Zentyal 8.0, the Webadmin is not working.
2. The package that contains the fix cannot be downloaded from the repository.

So, there are two faster ways to apply the fix.

1. Modify [this stub](https://github.com/zentyal/zentyal/commit/ec1a37d91efa2cd78ac336c6a84750d5eb00fd8f#diff-26f36b4fb071bfa7146dac8e7b859cbac27b0b43e5b26b29a0d9d6080a5ed34c) manually (`/usr/share/zentyal/stubs/dns/named.conf.options.mas`) and restart the DNS module (`sudo zs dns restart`) so the DNS resolution is recovered and then, just update the package through the [Zentyal Admin Interface](https://doc.zentyal.org/en/software.html#component-update).
2. Download the package from another computer, upload it to the Zentyal server, and install it.
    
    ```bash
    wget https://packages.zentyal.org/zentyal/pool/main/z/zentyal-dns/zentyal-dns_7.1.1_all.deb
    
    scp zentyal-dns_7.1.1_all.deb yourUserName@yourZentyalIP:
    
    sudo dpkg -i zentyal-dns_7.1.1_all.deb
    ```
    

As soon as possible we will do the same for Zentyal 7.0.

**NOTE:** If you have the mentioned stub configured persistently (`/etc/zentyal/stubs/dns/named.conf.options`), you must update the referred options, otherwise, the issue will remain in your server even after the upgrade.

**Comment by djoven89** [comment]
Hi,

For Zentyal 7.0, [here](https://github.com/zentyal/zentyal/commit/cbaf1458fd0559a4c1ba2fe820640024f0643fe4) is the commit and the released package is [zentyal-dns-7.0.3](https://packages.zentyal.org/zentyal/pool/main/z/zentyal-dns/zentyal-dns_7.0.3_all.deb) . Same actions as my previous comment to apply it.

**Comment by trvaa** [comment]
> Hi,
> 
> We have confirmed the bug in Zentyal 7.0 and 7.1, both versions use the parameter `dnssec-enable` which is no longer available since this night as @loxK explained perfectly.
> 
> At this moment, we have published the fix [here](https://github.com/zentyal/zentyal/commit/ec1a37d91efa2cd78ac336c6a84750d5eb00fd8f) for Zentyal 7.1 and released the package [zentyal-dns-7.1.1](https://packages.zentyal.org/zentyal/pool/main/z/zentyal-dns/zentyal-dns_7.1.1_all.deb).
> 
> Regarding applying the fix; unfortunately, this bug affected the DNS resolution, so it arrises two issues:
> 
> 1. The Zentyal Admin Interface (Webadmin) cannot reach the domain [update.zentyal.org](http://update.zentyal.org/) and because of the lack of this [fix](https://github.com/zentyal/zentyal/commit/da6fcd411e3a3acea43d8581eb972f3ba901556d#diff-f2da1cfc0ddd16974080efa028f11a9c2c83db2d36b364d89fabc8f70e797da0) applied in Zentyal 8.0, the Webadmin is not working.
> 2. The package that contains the fix cannot be downloaded from the repository.
> 
> So, there are two faster ways to apply the fix.
> 
> 1. Modify [this stub](https://github.com/zentyal/zentyal/commit/ec1a37d91efa2cd78ac336c6a84750d5eb00fd8f#diff-26f36b4fb071bfa7146dac8e7b859cbac27b0b43e5b26b29a0d9d6080a5ed34c) manually (`/usr/share/zentyal/stubs/dns/named.conf.options.mas`) and restart the DNS module (`sudo zs dns restart`) so the DNS resolution is recovered and then, just update the package through the [Zentyal Admin Interface](https://doc.zentyal.org/en/software.html#component-update).
> 2. Download the package from another computer, upload it to the Zentyal server, and install it.
>    ```shell
>    wget https://packages.zentyal.org/zentyal/pool/main/z/zentyal-dns/zentyal-dns_7.1.1_all.deb
>    
>    scp zentyal-dns_7.1.1_all.deb yourUserName@yourZentyalIP:
>    
>    sudo dpkg -i zentyal-dns_7.1.1_all.deb
>    ```
> 
> As soon as possible we will do the same for Zentyal 7.0.
> 
> **NOTE:** If you have the mentioned stub configured persistently (`/etc/zentyal/stubs/dns/named.conf.options`), you must update the referred options, otherwise, the issue will remain in your server even after the upgrade.

Great - thanks, What's the procedure for those at 7.1.2 already?

**Comment by djoven89** [comment]
Hi @trvaa ,

The fix only applies to the module DNS, you must check your current version (`dpkg -l zentyal-dns`) and if it `zentyal-dns_7.1.0`, proceed with the mentioned steps. Your current version of zentyal-core (I believe you referred to this) has nothing to do.

**Comment by fcortesjp** [comment]
tried changing the stubs options file but the dns service would not  start and it would hang when use zs dns start
I went the route of the updating the module, made the mistake of using 7.1.1 when I was actually on 7.0.9.. tried the 7.0.3 file now the dpkg -i is stuck at configuring zentyal-dns (7.0.3).. needless to say I want cry!!

**Comment by loxK** [comment]
> tried changing the stubs options file but the dns service would not start and it would hang when use zs dns start I went the route of the updating the module, made the mistake of using 7.1.1 when I was actually on 7.0.9.. tried the 7.0.3 file now the dpkg -i is stuck at configuring zentyal-dns (7.0.3).. needless to say I want to cry!!

You may have done something wrong, you should never change the stubs in `/usr/share/zentyal/stubs`, but copy them to  `/etc/zentyal/stubs` for editing. If you want help add some data (logs, `dpkg -l | grep zentyal`, and so on)

In my case, I used my workaround. Then when the new package came out I got the update like normal updates. I then deleted the stub in `/etc/zentyal/stubs`. Back to normal.

**Comment by btarrh** [comment]
Well, this has become a 🗑️🔥

Create the new directory where the .mas will be stored
`sudo mkdir -p /etc/zentyal/stubs/dns`

Copy **named.conf.options.mas** and place it in its new location
`sudo cp /usr/share/zentyal/stubs/dns/named.conf.options.mas /etc/zentyal/stubs/dns`

Edit and update **named.conf.options.mas** in its new location
`sudo vim /etc/zentyal/stubs/dns/named.conf.options.mas`


Locate this section in **/etc/zentyal/stubs/dns/named.conf.options.mas**
```
     // DNSSEC configuration
     dnssec-enable yes;
     dnssec-validation yes;
```


Update the section by adding the new line above the unwanted three lines and then ignore them
```
     dnssec-validation auto;
#     // DNSSEC configuration
#     dnssec-enable yes;
#     dnssec-validation yes;
```


When done, try restarting the DNS service
`sudo zs dns restart`

If that doesn't work, try restarting all the Zentyal services
`sudo zs restart`

If that doesn't work, just reboot the machine
`sudo shutdown -r now`

If that doesn't work, call a Priest ;-)
