### ISSUE TITLE
zs [modulename] restart or start hangs forever

### ISSUE THREAD

**Issue by gabrieletassoni** [zentyal/zentyal#2174]
**Describe the bug**
1. Updated Zentyal
2. Restarted the server
3. WebAdmin and DNS not working
4. I can login to SSH, issuing a `zs webmin status` and a zs dns status` reads for both *STOPPED*
5. Manually starting or restarting one of the two modules hangs forever, i.e. `zs dns start` and pressing return, just goes one line down and shows nothing for minutes, then I had to CTRL+C to give up.

**Expected behavior**
After a reboot I expect the Zentyal 7.1.2 server would be up and running, but that's not the case, the webadmin is not reachable, port 8443 seems closed and dns (used by other computers on the network) does not work.
I also expect that the `zs` commands to restart or start would work, or at least give errors and not hang just there forever.

**Zentyal OS (please complete the following information):**
 - Version: 7.1.2
 - Version of the module which has the bug:
   - zentyal            7.1.0ubuntu1
   - zentyal-core   7.1.2
   - zentyal-dns    7.1.0
 - Modules installed [e.g. DNS, DC, Jabber]
   - zentyal-all    7.1.0ubuntu1

**Comment by gabrieletassoni** [comment]
After the restart I noted also that from ssh the command `sudo apt update` does not work, I have to add `nameserver 8.8.8.8` manually to `/etc/resolv.conf` and then I can check for updates, but no updates are available, so it looks like I'm on the right version of the zentyal core and modules.

**Comment by djoven89** [comment]
Hi @gabrieletassoni , this issue has already been reported and fixed in #2173 , please, check that issue.

**Comment by gabrieletassoni** [comment]
Ok, thank, I check that, I didn't recognize it could be the same problem since none reported the hang of the zs restart  command, I thought it was something different. 
Checking it and reporting. thanks again.

**Comment by gabrieletassoni** [comment]
Thank you, I can confirm that installing the new zentyal-dns package as per #2173 fixed also the hangs of the `zs [modulename] start` commands.
