### ISSUE TITLE
Zentyal Components > Install: Not showing additional modules

### ISSUE THREAD

**Issue by rpcribari** [zentyal/zentyal#2178]
**Describe the bug**
After finishing the Zentyal 8 initial install, now the Zentyal Components section is empty. I was able to install components at first but now they are gone.

**To Reproduce**
1. Go to Software Management
2. Click on Zentyal Components
3. Click on Install

**Expected behavior**
I was expecting to see the list of additional modules that I could install.

**Zentyal OS (please complete the following information):**
 - Version: 8.0
 - Version of the module which has the bug: Software Management > Zentyal Components
 - Modules installed: Network, Firewall, DHCP, DNS, Logs, NTP, VPN, Domain Controller and File Sharing, Mail, SOGo Webmail

**Screenshots**
![zentyal](https://github.com/user-attachments/assets/d11c3a2a-153a-4065-bf56-b8cbdc04ade6)

**Comment by djoven89** [comment]
Hi  @rpcribari ,

Did you go to other tabs (**Update** or  **Delete**) and click the **Update List** button? Also, if you run `sudo apt update`, can you access the Zentyal repository?

**Comment by rpcribari** [comment]
Running sudo apt update brought it back to life. Thank you!!!

**Comment by rpcribari** [comment]
Great response time.
