### ISSUE TITLE
Error in the module http proxy transparent squid zentyal 8.0

### ISSUE THREAD

**Issue by Chrisdev2330** [zentyal/zentyal#2179]
Describe the bug:

HTTP Proxy module gives squid error at the time of activating it works well in HTTP not transparent but in transparent it gives error.

Zentyal OS (please complete the following information):

Version: 8.0
Modules installed :  DHCP Server, DNS Server, Domain Controller, Firewall, Http proxy, NTP Service, Network configuration, Software  VPN,DNS

![WhatsApp Image 2024-09-30 at 10 41 58 AM](https://github.com/user-attachments/assets/11e5041e-4431-4121-b4ce-c343d10902aa)

**Comment by sergio-sear** [comment]
Hi,

To know the status of your server and modules, you can use the [smart admin report tool.](https://doc.zentyal.org/en/smart-admin.html#system-status-reports) 


Did you analyze the log files after receiving the error??

- '/var/log/zentyal/zentyal.log'
- '/var/log/syslog'

Also, you can revise the config file **/etc/squid/squid.conf**

You can check the service status with the command
```
 sudo systemctl status squid.service
``` 

Regards.

**Comment by francismallmann** [comment]
Same error here.
