### ISSUE TITLE
Proxy not working well with Zentyal Beta 3.2

### ISSUE THREAD

**Issue by mat18** [Zentyal/zentyal#587]
Hi,

I am seeing issues in regard to the Proxy module. I have different time schedules for different groups which in turn have different policies (for testing only). I have the below scenario:

07:00 - 12:00, Monday to Friday - applying strict filter for the morning group
12:01 - 14:00, Monday to Friday - applying break filter for the break group
14:01 - 18:00, Monday to Friday - applying strict filter for the afternoon group.

When the proxy starts with the first one all is good, ie, from 07:00 till 12:00. When the time changes to 12:01, it asks me for the users credentials but does not connect to the proxy server and it is giving me localhost timed out. In order for this to work I have to restart the proxy server over and over again.

**Comment by Neustradamus** [comment]
@mat18: It is solved since the long time?
