### ISSUE TITLE
Invalid HTTP referer on Google Chrome 24.0.1312.40 beta-m

### ISSUE THREAD

**Issue by Diftraku** [Zentyal/zentyal#79]
When trying to use the Dashboard on latest beta version of Google Chrome, invalid HTTP referer errors pop up through out the dashboard.

The problem is that, Chrome sends the referer _without_ the trailing slash and this fails the referer check.

You can easily fix this by changing regexp in line 718 and 719 of Base.pm (https://github.com/Zentyal/zentyal/blob/master/main/core/src/EBox/CGI/Base.pm#L718) to either have a separate or for the missing trailing slash or simply change `\/` to `(?:|\/)`

**Comment by Neustradamus** [comment]
@Diftraku: It is solved since the long time?
