### ISSUE TITLE
[enhancement] general exclusion problem in duplicity since 3.2

### ISSUE THREAD

**Issue by mokkin** [Zentyal/zentyal#857]
Since 3.2 by default everything seems to be excluded in duplicity and you need to include paths manually like it says here:
http://doc.zentyal.org/3.2/en/backup.html#configuration-of-the-directories-and-files-that-are-saved
This has caused a big data loss (especially mails) in my backups since I upgraded to 3.2 in October. Please come back to the old exclusion rules like in 2.0 or 3.0 and don't override user defined rules after upgrading.

Zentyal 3.3 on Ubuntu 12.04 x64
Firefox 26.0 on Korora 19 x 64

**Comment by Neustradamus** [comment]
@mokkin: It is solved since the long time?
